LuaConfig["BaseBallerConfig"] = 
{
	[1001] = 
	{
		id = 1001,
		type = "player",
		name = "name_1001",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player2003.prefab",
		unlock_condition = 1,
		location = "C",
		drawing = "Player/tachie_player2003_0",
		bust = "Player/tachie_player2003_4",
		head = "Player/tachie_player2003_2",
		card_icon = "Player/tachie_player2003_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1002] = 
	{
		id = 1002,
		type = "player",
		name = "name_1002",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player2012.prefab",
		unlock_condition = 1,
		location = "C",
		drawing = "Player/tachie_player2012_0",
		bust = "Player/tachie_player2012_4",
		head = "Player/tachie_player2012_2",
		card_icon = "Player/tachie_player2012_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1003] = 
	{
		id = 1003,
		type = "player",
		name = "name_1003",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player3018.prefab",
		unlock_condition = 1,
		location = "CF",
		drawing = "Player/tachie_player1013_0",
		bust = "Player/tachie_player1013_4",
		head = "Player/tachie_player1013_2",
		card_icon = "Player/tachie_player1013_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="repairman",
		},
		fun_des = "fun_des_repairman",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1004] = 
	{
		id = 1004,
		type = "player",
		name = "name_1004",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player1013.prefab",
		unlock_condition = 1,
		location = "3B",
		drawing = "Player/tachie_player1013_0",
		bust = "Player/tachie_player1013_4",
		head = "Player/tachie_player1013_2",
		card_icon = "Player/tachie_player1013_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cheerleader",
		},
		fun_des = "fun_des_cheerleader",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1005] = 
	{
		id = 1005,
		type = "player",
		name = "name_1005",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player3005.prefab",
		unlock_condition = 1,
		location = "P",
		drawing = "Player/tachie_player3005_0",
		bust = "Player/tachie_player3005_4",
		head = "Player/tachie_player3005_2",
		card_icon = "Player/tachie_player3005_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cleaner",
		},
		fun_des = "fun_des_cleaner",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1006] = 
	{
		id = 1006,
		type = "player",
		name = "name_1006",
		gender = 0,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player1003.prefab",
		unlock_condition = 1,
		location = "1B",
		drawing = "Player/tachie_player1003_0",
		bust = "Player/tachie_player1003_4",
		head = "Player/tachie_player1003_2",
		card_icon = "Player/tachie_player1003_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="salesman",
		},
		fun_des = "fun_des_salesman",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1007] = 
	{
		id = 1007,
		type = "player",
		name = "name_1007",
		gender = 0,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player1005.prefab",
		unlock_condition = 1,
		location = "2B",
		drawing = "Player/tachie_player1005_0",
		bust = "Player/tachie_player1005_4",
		head = "Player/tachie_player1005_2",
		card_icon = "Player/tachie_player1005_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="salesman",
		},
		fun_des = "fun_des_salesman",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1008] = 
	{
		id = 1008,
		type = "player",
		name = "name_1008",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player1012.prefab",
		unlock_condition = 1,
		location = "SS",
		drawing = "Player/tachie_player2004_0",
		bust = "Player/tachie_player2004_4",
		head = "Player/tachie_player2004_2",
		card_icon = "Player/tachie_player2004_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cheerleader",
		},
		fun_des = "fun_des_cheerleader",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1009] = 
	{
		id = 1009,
		type = "player",
		name = "name_1009",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player2004.prefab",
		unlock_condition = 1,
		location = "1B",
		drawing = "Player/tachie_player2004_0",
		bust = "Player/tachie_player2004_4",
		head = "Player/tachie_player2004_2",
		card_icon = "Player/tachie_player2004_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1010] = 
	{
		id = 1010,
		type = "player",
		name = "name_1010",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player2013.prefab",
		unlock_condition = 1,
		location = "SS",
		drawing = "Player/tachie_player2013_0",
		bust = "Player/tachie_player2013_4",
		head = "Player/tachie_player2013_2",
		card_icon = "Player/tachie_player2013_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cashier",
		},
		fun_des = "fun_des_cashier",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1011] = 
	{
		id = 1011,
		type = "player",
		name = "name_1011",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player2005.prefab",
		unlock_condition = 1,
		location = "RF",
		drawing = "Player/tachie_player2005_0",
		bust = "Player/tachie_player2005_4",
		head = "Player/tachie_player2005_2",
		card_icon = "Player/tachie_player2005_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1012] = 
	{
		id = 1012,
		type = "player",
		name = "name_1012",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player3008.prefab",
		unlock_condition = 1,
		location = "CF",
		drawing = "Player/tachie_player3008_0",
		bust = "Player/tachie_player3008_4",
		head = "Player/tachie_player3008_2",
		card_icon = "Player/tachie_player3008_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cashier",
		},
		fun_des = "fun_des_cashier",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1013] = 
	{
		id = 1013,
		type = "player",
		name = "name_1013",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player2006.prefab",
		unlock_condition = 1,
		location = "RF",
		drawing = "Player/tachie_player2006_0",
		bust = "Player/tachie_player2006_4",
		head = "Player/tachie_player2006_2",
		card_icon = "Player/tachie_player2006_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cleaner",
		},
		fun_des = "fun_des_cleaner",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1014] = 
	{
		id = 1014,
		type = "player",
		name = "name_1014",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player3010.prefab",
		unlock_condition = 1,
		location = "C",
		drawing = "Player/tachie_player3010_0",
		bust = "Player/tachie_player3010_4",
		head = "Player/tachie_player3010_2",
		card_icon = "Player/tachie_player3010_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1015] = 
	{
		id = 1015,
		type = "player",
		name = "name_1015",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player2007.prefab",
		unlock_condition = 1,
		location = "P",
		drawing = "Player/tachie_player2007_0",
		bust = "Player/tachie_player2007_4",
		head = "Player/tachie_player2007_2",
		card_icon = "Player/tachie_player2007_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[1016] = 
	{
		id = 1016,
		type = "player",
		name = "name_1016",
		gender = 1,
		quality = "ordinary",
		base_state = "0",
		model = "Role/Baseballer/model_player4002.prefab",
		unlock_condition = 1,
		location = "CF",
		drawing = "Player/tachie_player2007_0",
		bust = "Player/tachie_player2007_4",
		head = "Player/tachie_player2007_2",
		card_icon = "Player/tachie_player2007_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="repairman",
		},
		fun_des = "fun_des_repairman",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=5,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2001] = 
	{
		id = 2001,
		type = "player",
		name = "name_2001",
		gender = 0,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player1006.prefab",
		unlock_condition = 1,
		location = "C",
		drawing = "Player/tachie_player1006_0",
		bust = "Player/tachie_player1006_4",
		head = "Player/tachie_player1006_2",
		card_icon = "Player/tachie_player1006_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2002] = 
	{
		id = 2002,
		type = "player",
		name = "name_2002",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player2009.prefab",
		unlock_condition = 1,
		location = "2B",
		drawing = "Player/tachie_player2009_0",
		bust = "Player/tachie_player2009_4",
		head = "Player/tachie_player2009_2",
		card_icon = "Player/tachie_player2009_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2003] = 
	{
		id = 2003,
		type = "player",
		name = "name_2003",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player4011.prefab",
		unlock_condition = 1,
		location = "SS",
		drawing = "Player/tachie_player2009_0",
		bust = "Player/tachie_player2009_4",
		head = "Player/tachie_player2009_2",
		card_icon = "Player/tachie_player2009_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cashier",
		},
		fun_des = "fun_des_cashier",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2004] = 
	{
		id = 2004,
		type = "player",
		name = "name_2004",
		gender = 0,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player2015.prefab",
		unlock_condition = 1,
		location = "LF",
		drawing = "Player/tachie_player2015_0",
		bust = "Player/tachie_player2015_4",
		head = "Player/tachie_player2015_2",
		card_icon = "Player/tachie_player2015_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cheerleader",
		},
		fun_des = "fun_des_cheerleader",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2005] = 
	{
		id = 2005,
		type = "player",
		name = "name_2005",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player4007.prefab",
		unlock_condition = 1,
		location = "C",
		drawing = "Player/tachie_player4007_0",
		bust = "Player/tachie_player4007_4",
		head = "Player/tachie_player4007_2",
		card_icon = "Player/tachie_player4007_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2006] = 
	{
		id = 2006,
		type = "player",
		name = "name_2006",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player4006.prefab",
		unlock_condition = 1,
		location = "LF",
		drawing = "Player/tachie_player4007_0",
		bust = "Player/tachie_player4007_4",
		head = "Player/tachie_player4007_2",
		card_icon = "Player/tachie_player4007_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="admin",
		},
		fun_des = "fun_des_admin",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2007] = 
	{
		id = 2007,
		type = "player",
		name = "name_2007",
		gender = 0,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player3003.prefab",
		unlock_condition = 1,
		location = "C",
		drawing = "Player/tachie_player3003_0",
		bust = "Player/tachie_player3003_4",
		head = "Player/tachie_player3003_2",
		card_icon = "Player/tachie_player3003_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2008] = 
	{
		id = 2008,
		type = "player",
		name = "name_2008",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player1011.prefab",
		unlock_condition = 1,
		location = "P",
		drawing = "Player/tachie_player1011_0",
		bust = "Player/tachie_player1011_4",
		head = "Player/tachie_player1011_2",
		card_icon = "Player/tachie_player1011_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cashier",
		},
		fun_des = "fun_des_cashier",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2009] = 
	{
		id = 2009,
		type = "player",
		name = "name_2009",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player3006.prefab",
		unlock_condition = 1,
		location = "CF",
		drawing = "Player/tachie_player3006_0",
		bust = "Player/tachie_player3006_4",
		head = "Player/tachie_player3006_2",
		card_icon = "Player/tachie_player3006_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="admin",
		},
		fun_des = "fun_des_admin",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2010] = 
	{
		id = 2010,
		type = "player",
		name = "name_2010",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player2010.prefab",
		unlock_condition = 1,
		location = "RF",
		drawing = "Player/tachie_player2010_0",
		bust = "Player/tachie_player2010_4",
		head = "Player/tachie_player2010_2",
		card_icon = "Player/tachie_player2010_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2011] = 
	{
		id = 2011,
		type = "player",
		name = "name_2011",
		gender = 0,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player3019.prefab",
		unlock_condition = 1,
		location = "P",
		drawing = "Player/tachie_player3019_0",
		bust = "Player/tachie_player3019_4",
		head = "Player/tachie_player3019_2",
		card_icon = "Player/tachie_player3019_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cleaner",
		},
		fun_des = "fun_des_cleaner",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2012] = 
	{
		id = 2012,
		type = "player",
		name = "name_2012",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player2011.prefab",
		unlock_condition = 1,
		location = "2B",
		drawing = "Player/tachie_player2011_0",
		bust = "Player/tachie_player2011_4",
		head = "Player/tachie_player2011_2",
		card_icon = "Player/tachie_player2011_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="guard",
		},
		fun_des = "fun_des_guard",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2013] = 
	{
		id = 2013,
		type = "player",
		name = "name_2013",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player2019.prefab",
		unlock_condition = 1,
		location = "RF",
		drawing = "Player/tachie_player2019_0",
		bust = "Player/tachie_player2019_4",
		head = "Player/tachie_player2019_2",
		card_icon = "Player/tachie_player2019_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cleaner",
		},
		fun_des = "fun_des_cleaner",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2014] = 
	{
		id = 2014,
		type = "player",
		name = "name_2014",
		gender = 0,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player2018.prefab",
		unlock_condition = 1,
		location = "2B",
		drawing = "Player/tachie_player2018_0",
		bust = "Player/tachie_player2018_4",
		head = "Player/tachie_player2018_2",
		card_icon = "Player/tachie_player2018_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2015] = 
	{
		id = 2015,
		type = "player",
		name = "name_2015",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player4003.prefab",
		unlock_condition = 1,
		location = "SS",
		drawing = "Player/tachie_player1010_0",
		bust = "Player/tachie_player1010_4",
		head = "Player/tachie_player1010_2",
		card_icon = "Player/tachie_player1010_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2016] = 
	{
		id = 2016,
		type = "player",
		name = "name_2016",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player1010.prefab",
		unlock_condition = 1,
		location = "1B",
		drawing = "Player/tachie_player1010_0",
		bust = "Player/tachie_player1010_4",
		head = "Player/tachie_player1010_2",
		card_icon = "Player/tachie_player1010_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="guard",
		},
		fun_des = "fun_des_guard",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2017] = 
	{
		id = 2017,
		type = "player",
		name = "name_2017",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player3009.prefab",
		unlock_condition = 1,
		location = "CF",
		drawing = "Player/tachie_player3009_0",
		bust = "Player/tachie_player3009_4",
		head = "Player/tachie_player3009_2",
		card_icon = "Player/tachie_player3009_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2018] = 
	{
		id = 2018,
		type = "player",
		name = "name_2018",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player1008.prefab",
		unlock_condition = 1,
		location = "RF",
		drawing = "Player/tachie_player3009_0",
		bust = "Player/tachie_player3009_4",
		head = "Player/tachie_player3009_2",
		card_icon = "Player/tachie_player3009_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="repairman",
		},
		fun_des = "fun_des_repairman",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2019] = 
	{
		id = 2019,
		type = "player",
		name = "name_2019",
		gender = 0,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player3001.prefab",
		unlock_condition = 1,
		location = "P",
		drawing = "Player/tachie_player3001_0",
		bust = "Player/tachie_player3001_4",
		head = "Player/tachie_player3001_2",
		card_icon = "Player/tachie_player3001_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2020] = 
	{
		id = 2020,
		type = "player",
		name = "name_2020",
		gender = 0,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player2014.prefab",
		unlock_condition = 1,
		location = "2B",
		drawing = "Player/tachie_player2014_0",
		bust = "Player/tachie_player2014_4",
		head = "Player/tachie_player2014_2",
		card_icon = "Player/tachie_player2014_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="secretary",
		},
		fun_des = "fun_des_secretary",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2021] = 
	{
		id = 2021,
		type = "player",
		name = "name_2021",
		gender = 0,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player2017.prefab",
		unlock_condition = 1,
		location = "CF",
		drawing = "Player/tachie_player2017_0",
		bust = "Player/tachie_player2017_4",
		head = "Player/tachie_player2017_2",
		card_icon = "Player/tachie_player2017_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[2022] = 
	{
		id = 2022,
		type = "player",
		name = "name_2022",
		gender = 1,
		quality = "rare",
		base_state = "0",
		model = "Role/Baseballer/model_player3011.prefab",
		unlock_condition = 1,
		location = "1B",
		drawing = "Player/tachie_player3011_0",
		bust = "Player/tachie_player3011_4",
		head = "Player/tachie_player3011_2",
		card_icon = "Player/tachie_player3011_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="guard",
		},
		fun_des = "fun_des_guard",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=10,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3001] = 
	{
		id = 3001,
		type = "player",
		name = "name_3001",
		gender = 1,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player3012.prefab",
		unlock_condition = 1,
		location = "SS",
		drawing = "Player/tachie_player3012_0",
		bust = "Player/tachie_player3012_4",
		head = "Player/tachie_player3012_2",
		card_icon = "Player/tachie_player3012_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="repairman",
		},
		fun_des = "fun_des_repairman",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3002] = 
	{
		id = 3002,
		type = "player",
		name = "name_3002",
		gender = 0,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player2001.prefab",
		unlock_condition = 1,
		location = "1B",
		drawing = "Player/tachie_player2001_0",
		bust = "Player/tachie_player2001_4",
		head = "Player/tachie_player2001_2",
		card_icon = "Player/tachie_player2001_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3003] = 
	{
		id = 3003,
		type = "player",
		name = "name_3003",
		gender = 1,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player4008.prefab",
		unlock_condition = 1,
		location = "1B",
		drawing = "Player/tachie_player4008_0",
		bust = "Player/tachie_player4008_4",
		head = "Player/tachie_player4008_2",
		card_icon = "Player/tachie_player4008_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="repairman",
		},
		fun_des = "fun_des_repairman",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3004] = 
	{
		id = 3004,
		type = "player",
		name = "name_3004",
		gender = 0,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player1001.prefab",
		unlock_condition = 1,
		location = "P",
		drawing = "Player/tachie_player1001_0",
		bust = "Player/tachie_player1001_4",
		head = "Player/tachie_player1001_2",
		card_icon = "Player/tachie_player1001_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cashier",
		},
		fun_des = "fun_des_cashier",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3005] = 
	{
		id = 3005,
		type = "player",
		name = "name_3005",
		gender = 1,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player1007.prefab",
		unlock_condition = 1,
		location = "1B",
		drawing = "Player/tachie_player4010_0",
		bust = "Player/tachie_player4010_4",
		head = "Player/tachie_player4010_2",
		card_icon = "Player/tachie_player4010_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="admin",
		},
		fun_des = "fun_des_admin",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3006] = 
	{
		id = 3006,
		type = "player",
		name = "name_3006",
		gender = 1,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player4010.prefab",
		unlock_condition = 1,
		location = "2B",
		drawing = "Player/tachie_player4010_0",
		bust = "Player/tachie_player4010_4",
		head = "Player/tachie_player4010_2",
		card_icon = "Player/tachie_player4010_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="guard",
		},
		fun_des = "fun_des_guard",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3007] = 
	{
		id = 3007,
		type = "player",
		name = "name_3007",
		gender = 0,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player2002.prefab",
		unlock_condition = 1,
		location = "3B",
		drawing = "Player/tachie_player2002_0",
		bust = "Player/tachie_player2002_4",
		head = "Player/tachie_player2002_2",
		card_icon = "Player/tachie_player2002_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="secretary",
		},
		fun_des = "fun_des_secretary",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3008] = 
	{
		id = 3008,
		type = "player",
		name = "name_3008",
		gender = 0,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player3013.prefab",
		unlock_condition = 1,
		location = "LF",
		drawing = "Player/tachie_player3013_0",
		bust = "Player/tachie_player3013_4",
		head = "Player/tachie_player3013_2",
		card_icon = "Player/tachie_player3013_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3009] = 
	{
		id = 3009,
		type = "player",
		name = "name_3009",
		gender = 0,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player3021.prefab",
		unlock_condition = 1,
		location = "3B",
		drawing = "Player/tachie_player3021_0",
		bust = "Player/tachie_player3021_4",
		head = "Player/tachie_player3021_2",
		card_icon = "Player/tachie_player3021_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="admin",
		},
		fun_des = "fun_des_admin",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3010] = 
	{
		id = 3010,
		type = "player",
		name = "name_3010",
		gender = 1,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player1014.prefab",
		unlock_condition = 1,
		location = "LF",
		drawing = "Player/tachie_player4010_0",
		bust = "Player/tachie_player4010_4",
		head = "Player/tachie_player4010_2",
		card_icon = "Player/tachie_player4010_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="manager",
		},
		fun_des = "fun_des_manager",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3011] = 
	{
		id = 3011,
		type = "player",
		name = "name_3011",
		gender = 0,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player1002.prefab",
		unlock_condition = 1,
		location = "LF",
		drawing = "Player/tachie_player1002_0",
		bust = "Player/tachie_player1002_4",
		head = "Player/tachie_player1002_2",
		card_icon = "Player/tachie_player1002_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3012] = 
	{
		id = 3012,
		type = "player",
		name = "name_3012",
		gender = 1,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player3022.prefab",
		unlock_condition = 1,
		location = "2B",
		drawing = "Player/tachie_player3023_0",
		bust = "Player/tachie_player3023_4",
		head = "Player/tachie_player3023_2",
		card_icon = "Player/tachie_player3023_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cheerleader",
		},
		fun_des = "fun_des_cheerleader",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3013] = 
	{
		id = 3013,
		type = "player",
		name = "name_3013",
		gender = 1,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player3023.prefab",
		unlock_condition = 1,
		location = "3B",
		drawing = "Player/tachie_player3023_0",
		bust = "Player/tachie_player3023_4",
		head = "Player/tachie_player3023_2",
		card_icon = "Player/tachie_player3023_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3014] = 
	{
		id = 3014,
		type = "player",
		name = "name_3014",
		gender = 1,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player1016.prefab",
		unlock_condition = 1,
		location = "SS",
		drawing = "Player/tachie_player3023_0",
		bust = "Player/tachie_player3023_4",
		head = "Player/tachie_player3023_2",
		card_icon = "Player/tachie_player3023_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="guard",
		},
		fun_des = "fun_des_guard",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3015] = 
	{
		id = 3015,
		type = "player",
		name = "name_3015",
		gender = 0,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player3014.prefab",
		unlock_condition = 1,
		location = "RF",
		drawing = "Player/tachie_player3017_0",
		bust = "Player/tachie_player3017_4",
		head = "Player/tachie_player3017_2",
		card_icon = "Player/tachie_player3017_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cleaner",
		},
		fun_des = "fun_des_cleaner",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3016] = 
	{
		id = 3016,
		type = "player",
		name = "name_3016",
		gender = 1,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player2008.prefab",
		unlock_condition = 1,
		location = "2B",
		drawing = "Player/tachie_player2008_0",
		bust = "Player/tachie_player2008_4",
		head = "Player/tachie_player2008_2",
		card_icon = "Player/tachie_player2008_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3017] = 
	{
		id = 3017,
		type = "player",
		name = "name_3017",
		gender = 1,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player3002.prefab",
		unlock_condition = 1,
		location = "3B",
		drawing = "Player/tachie_player3002_0",
		bust = "Player/tachie_player3002_4",
		head = "Player/tachie_player3002_2",
		card_icon = "Player/tachie_player3002_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[3018] = 
	{
		id = 3018,
		type = "player",
		name = "name_3018",
		gender = 0,
		quality = "epic",
		base_state = "0",
		model = "Role/Baseballer/model_player3017.prefab",
		unlock_condition = 1,
		location = "SS",
		drawing = "Player/tachie_player3017_0",
		bust = "Player/tachie_player3017_4",
		head = "Player/tachie_player3017_2",
		card_icon = "Player/tachie_player3017_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=20,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4001] = 
	{
		id = 4001,
		type = "player",
		name = "name_4001",
		gender = 1,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player4004.prefab",
		unlock_condition = 1,
		location = "LF",
		drawing = "Player/tachie_player3011_0",
		bust = "Player/tachie_player3011_4",
		head = "Player/tachie_player3011_2",
		card_icon = "Player/tachie_player3011_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="admin",
		},
		fun_des = "fun_des_admin",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4002] = 
	{
		id = 4002,
		type = "player",
		name = "name_4002",
		gender = 0,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player3016.prefab",
		unlock_condition = 1,
		location = "3B",
		drawing = "Player/tachie_player1004_0",
		bust = "Player/tachie_player1004_4",
		head = "Player/tachie_player1004_2",
		card_icon = "Player/tachie_player1004_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="salesman",
		},
		fun_des = "fun_des_salesman",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4003] = 
	{
		id = 4003,
		type = "player",
		name = "name_4003",
		gender = 0,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player1004.prefab",
		unlock_condition = 1,
		location = "C",
		drawing = "Player/tachie_player1004_0",
		bust = "Player/tachie_player1004_4",
		head = "Player/tachie_player1004_2",
		card_icon = "Player/tachie_player1004_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4004] = 
	{
		id = 4004,
		type = "player",
		name = "name_4004",
		gender = 0,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player3020.prefab",
		unlock_condition = 1,
		location = "P",
		drawing = "Player/tachie_player3020_0",
		bust = "Player/tachie_player3020_4",
		head = "Player/tachie_player3020_2",
		card_icon = "Player/tachie_player3020_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cashier",
		},
		fun_des = "fun_des_cashier",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4005] = 
	{
		id = 4005,
		type = "player",
		name = "name_4005",
		gender = 0,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player3004.prefab",
		unlock_condition = 1,
		location = "C",
		drawing = "Player/tachie_player3004_0",
		bust = "Player/tachie_player3004_4",
		head = "Player/tachie_player3004_2",
		card_icon = "Player/tachie_player3004_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4006] = 
	{
		id = 4006,
		type = "player",
		name = "name_4006",
		gender = 1,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player4001.prefab",
		unlock_condition = 1,
		location = "CF",
		drawing = "Player/tachie_player4001_0",
		bust = "Player/tachie_player4001_4",
		head = "Player/tachie_player4001_2",
		card_icon = "Player/tachie_player4001_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cleaner",
		},
		fun_des = "fun_des_cleaner",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4007] = 
	{
		id = 4007,
		type = "player",
		name = "name_4007",
		gender = 1,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player4009.prefab",
		unlock_condition = 1,
		location = "LF",
		drawing = "Player/tachie_player4009_0",
		bust = "Player/tachie_player4009_4",
		head = "Player/tachie_player4009_2",
		card_icon = "Player/tachie_player4009_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="secretary",
		},
		fun_des = "fun_des_secretary",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4008] = 
	{
		id = 4008,
		type = "player",
		name = "name_4008",
		gender = 1,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player4012.prefab",
		unlock_condition = 1,
		location = "CF",
		drawing = "Player/tachie_player4012_0",
		bust = "Player/tachie_player4012_4",
		head = "Player/tachie_player4012_2",
		card_icon = "Player/tachie_player4012_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="manager",
		},
		fun_des = "fun_des_manager",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4009] = 
	{
		id = 4009,
		type = "player",
		name = "name_4009",
		gender = 1,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player3007.prefab",
		unlock_condition = 1,
		location = "SS",
		drawing = "Player/tachie_player3007_0",
		bust = "Player/tachie_player3007_4",
		head = "Player/tachie_player3007_2",
		card_icon = "Player/tachie_player3007_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="coach",
		},
		fun_des = "fun_des_coach",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4010] = 
	{
		id = 4010,
		type = "player",
		name = "name_4010",
		gender = 0,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player3015.prefab",
		unlock_condition = 1,
		location = "1B",
		drawing = "Player/tachie_player3015_0",
		bust = "Player/tachie_player3015_4",
		head = "Player/tachie_player3015_2",
		card_icon = "Player/tachie_player3015_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="cheerleader",
		},
		fun_des = "fun_des_cheerleader",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4011] = 
	{
		id = 4011,
		type = "player",
		name = "name_4011",
		gender = 1,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player1009.prefab",
		unlock_condition = 1,
		location = "3B",
		drawing = "Player/tachie_player3007_0",
		bust = "Player/tachie_player3007_4",
		head = "Player/tachie_player3007_2",
		card_icon = "Player/tachie_player3007_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="guard",
		},
		fun_des = "fun_des_guard",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4012] = 
	{
		id = 4012,
		type = "player",
		name = "name_4012",
		gender = 1,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player1015.prefab",
		unlock_condition = 1,
		location = "RF",
		drawing = "Player/tachie_player1015_0",
		bust = "Player/tachie_player1015_4",
		head = "Player/tachie_player1015_2",
		card_icon = "Player/tachie_player1015_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="repairman",
		},
		fun_des = "fun_des_repairman",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4013] = 
	{
		id = 4013,
		type = "player",
		name = "name_4013",
		gender = 1,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player4005.prefab",
		unlock_condition = 1,
		location = "LF",
		drawing = "Player/tachie_player1015_0",
		bust = "Player/tachie_player1015_4",
		head = "Player/tachie_player1015_2",
		card_icon = "Player/tachie_player1015_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="admin",
		},
		fun_des = "fun_des_admin",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[4014] = 
	{
		id = 4014,
		type = "player",
		name = "name_4014",
		gender = 0,
		quality = "legend",
		base_state = "0",
		model = "Role/Baseballer/model_player2016.prefab",
		unlock_condition = 1,
		location = "RF",
		drawing = "Player/tachie_player2016_0",
		bust = "Player/tachie_player2016_4",
		head = "Player/tachie_player2016_2",
		card_icon = "Player/tachie_player2016_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = {
			[1]="waiter",
		},
		fun_des = "fun_des_waiter",
		price = {
			[1]="currency",
			[2]="diamond",
			[3]=50,
		},
		cards1_function = nil,
		fun1_des = "",
		cards2_function = nil,
		fun2_des = "",
		cards3_function = nil,
		fun3_des = "",
		cards4_function = nil,
		fun4_des = "",
		cards5_function = nil,
		fun5_des = "",
	},
	[11001] = 
	{
		id = 11001,
		type = "building",
		name = "name_11001",
		gender = -1,
		quality = "ordinary",
		base_state = "0",
		model = "",
		unlock_condition = 1,
		location = "",
		drawing = "Architecture/tachie_build1100201_0",
		bust = "Architecture/tachie_build1100201_4",
		head = "Architecture/tachie_build1100201_4",
		card_icon = "Architecture/tachie_build1100201_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = nil,
		fun_des = "",
		price = nil,
		cards1_function = {
			["match_inc"]=3,
		},
		fun1_des = "fun_des_1300101",
		cards2_function = {
			["match_inc"]=6,
		},
		fun2_des = "fun_des_1300102",
		cards3_function = {
			["match_inc"]=9,
		},
		fun3_des = "fun_des_1300103",
		cards4_function = {
			["match_inc"]=12,
		},
		fun4_des = "fun_des_1300104",
		cards5_function = {
			["match_inc"]=15,
		},
		fun5_des = "fun_des_1300105",
	},
	[12001] = 
	{
		id = 12001,
		type = "building",
		name = "name_12001",
		gender = -1,
		quality = "rare",
		base_state = "0",
		model = "",
		unlock_condition = 1,
		location = "",
		drawing = "Architecture/tachie_build1200201_0",
		bust = "Architecture/tachie_build1200201_4",
		head = "Architecture/tachie_build1200201_4",
		card_icon = "Architecture/tachie_build1200201_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = nil,
		fun_des = "",
		price = nil,
		cards1_function = {
			["combat"]=4,
		},
		fun1_des = "fun_des_1400101",
		cards2_function = {
			["combat"]=8,
		},
		fun2_des = "fun_des_1400102",
		cards3_function = {
			["combat"]=12,
		},
		fun3_des = "fun_des_1400103",
		cards4_function = {
			["combat"]=16,
		},
		fun4_des = "fun_des_1400104",
		cards5_function = {
			["combat"]=20,
		},
		fun5_des = "fun_des_1400105",
	},
	[12002] = 
	{
		id = 12002,
		type = "building",
		name = "name_12002",
		gender = -1,
		quality = "rare",
		base_state = "0",
		model = "",
		unlock_condition = 1,
		location = "",
		drawing = "Architecture/tachie_build1200301_0",
		bust = "Architecture/tachie_build1200301_4",
		head = "Architecture/tachie_build1200301_4",
		card_icon = "Architecture/tachie_build1200301_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = nil,
		fun_des = "",
		price = nil,
		cards1_function = {
			["cus_pro_A"]=4,
		},
		fun1_des = "fun_des_1400201",
		cards2_function = {
			["cus_pro_A"]=8,
		},
		fun2_des = "fun_des_1400202",
		cards3_function = {
			["cus_pro_A"]=12,
		},
		fun3_des = "fun_des_1400203",
		cards4_function = {
			["cus_pro_A"]=16,
		},
		fun4_des = "fun_des_1400204",
		cards5_function = {
			["cus_pro_A"]=20,
		},
		fun5_des = "fun_des_1400205",
	},
	[13001] = 
	{
		id = 13001,
		type = "building",
		name = "name_13001",
		gender = -1,
		quality = "epic",
		base_state = "0",
		model = "",
		unlock_condition = 1,
		location = "",
		drawing = "Architecture/tachie_build1100101_0",
		bust = "Architecture/tachie_build1100101_4",
		head = "Architecture/tachie_build1100101_4",
		card_icon = "Architecture/tachie_build1100101_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = nil,
		fun_des = "",
		price = nil,
		cards1_function = {
			["cus_pro_C"]=2,
		},
		fun1_des = "fun_des_1200101",
		cards2_function = {
			["cus_pro_C"]=4,
		},
		fun2_des = "fun_des_1200102",
		cards3_function = {
			["cus_pro_C"]=6,
		},
		fun3_des = "fun_des_1200103",
		cards4_function = {
			["cus_pro_C"]=8,
		},
		fun4_des = "fun_des_1200104",
		cards5_function = {
			["cus_pro_C"]=10,
		},
		fun5_des = "fun_des_1200105",
	},
	[13002] = 
	{
		id = 13002,
		type = "building",
		name = "name_13002",
		gender = -1,
		quality = "epic",
		base_state = "0",
		model = "",
		unlock_condition = 1,
		location = "",
		drawing = "Architecture/tachie_build1200101_0",
		bust = "Architecture/tachie_build1200101_4",
		head = "Architecture/tachie_build1200101_4",
		card_icon = "Architecture/tachie_build1200101_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = nil,
		fun_des = "",
		price = nil,
		cards1_function = {
			["speedUp_time"]=3,
		},
		fun1_des = "fun_des_1300201",
		cards2_function = {
			["speedUp_time"]=6,
		},
		fun2_des = "fun_des_1300202",
		cards3_function = {
			["speedUp_time"]=9,
		},
		fun3_des = "fun_des_1300203",
		cards4_function = {
			["speedUp_time"]=12,
		},
		fun4_des = "fun_des_1300204",
		cards5_function = {
			["speedUp_time"]=15,
		},
		fun5_des = "fun_des_1300205",
	},
	[14001] = 
	{
		id = 14001,
		type = "building",
		name = "name_14001",
		gender = -1,
		quality = "legend",
		base_state = "0",
		model = "",
		unlock_condition = 1,
		location = "",
		drawing = "Architecture/tachie_build1200401_0",
		bust = "Architecture/tachie_build1200401_4",
		head = "Architecture/tachie_build1200401_4",
		card_icon = "Architecture/tachie_build1200401_4",
		cards_num = "5/10/20/30/45/60/80/100/120",
		employee_function = nil,
		fun_des = "",
		price = nil,
		cards1_function = {
			["sponsor"]=4,
		},
		fun1_des = "fun_des_1400301",
		cards2_function = {
			["sponsor"]=8,
		},
		fun2_des = "fun_des_1400302",
		cards3_function = {
			["sponsor"]=12,
		},
		fun3_des = "fun_des_1400303",
		cards4_function = {
			["sponsor"]=16,
		},
		fun4_des = "fun_des_1400304",
		cards5_function = {
			["sponsor"]=20,
		},
		fun5_des = "fun_des_1400305",
	},
}