LuaConfig["CurrencyConfig"] = 
{
	["diamond"] = 
	{
		id = "diamond",
		id_order = 1,
		icon = "Currency/currency_gem",
		name = "currency_name_10001",
		description = "currency_intro_0001",
		function_des = "currency_func_0002",
		source = "currency_get_0002",
		type = "",
		order = 0,
		max = 99999999,
		initial = 0,
	},
	["cash"] = 
	{
		id = "cash",
		id_order = 2,
		icon = "Currency/currency_cash",
		name = "currency_name_10002",
		description = "currency_intro_0002",
		function_des = "currency_func_0001",
		source = "currency_get_0001",
		type = "",
		order = 0,
		max = 99999999,
		initial = 400,
	},
	["vpcard"] = 
	{
		id = "vpcard",
		id_order = 3,
		icon = "Menu/att_vip",
		name = "currency_name_10003",
		description = "currency_intro_0003",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 99999999,
		initial = 10,
	},
	["leaflet"] = 
	{
		id = "leaflet",
		id_order = 4,
		icon = "Leaflet/I_title_horn",
		name = "currency_name_10004",
		description = "currency_intro_0004",
		function_des = "currency_name_10004",
		source = "currency_name_10004",
		type = "",
		order = 0,
		max = 999,
		initial = 10,
	},
	["leaflet2"] = 
	{
		id = "leaflet2",
		id_order = 5,
		icon = "Currency/currency_newspaper",
		name = "currency_name_10004",
		description = "currency_intro_0042",
		function_des = "currency_name_10004",
		source = "currency_name_10004",
		type = "",
		order = 0,
		max = 999,
		initial = 5,
	},
	["leaflet3"] = 
	{
		id = "leaflet3",
		id_order = 6,
		icon = "Currency/currency_radio",
		name = "currency_name_10004",
		description = "currency_intro_0043",
		function_des = "currency_name_10004",
		source = "currency_name_10004",
		type = "",
		order = 0,
		max = 999,
		initial = 1,
	},
	["exp"] = 
	{
		id = "exp",
		id_order = 7,
		icon = "Currency/currency_experience",
		name = "currency_name_10005",
		description = "currency_intro_0005",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 99999999,
		initial = 0,
	},
	["honor"] = 
	{
		id = "honor",
		id_order = 8,
		icon = "Currency/currency_coin",
		name = "currency_name_10006",
		description = "currency_intro_0006",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 99999999,
		initial = 0,
	},
	["shop_card"] = 
	{
		id = "shop_card",
		id_order = 9,
		icon = "Currency/currency_coin",
		name = "currency_name_10007",
		description = "currency_intro_0007",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["energy"] = 
	{
		id = "energy",
		id_order = 10,
		icon = "Currency/currency_energy",
		name = "currency_name_10008",
		description = "currency_intro_0008",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["plastic"] = 
	{
		id = "plastic",
		id_order = 11,
		icon = "Currency/currency_plastic",
		name = "currency_name_10009",
		description = "currency_intro_0009",
		function_des = "currency_func_0003",
		source = "currency_get_0003",
		type = "base",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["wood"] = 
	{
		id = "wood",
		id_order = 12,
		icon = "Currency/currency_wood",
		name = "currency_name_10010",
		description = "currency_intro_0010",
		function_des = "currency_func_0003",
		source = "currency_get_0003",
		type = "base",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["iron"] = 
	{
		id = "iron",
		id_order = 13,
		icon = "Currency/currency_iron",
		name = "currency_name_10011",
		description = "currency_intro_0011",
		function_des = "currency_func_0003",
		source = "currency_get_0003",
		type = "base",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["fabric"] = 
	{
		id = "fabric",
		id_order = 14,
		icon = "Currency/currency_cloth",
		name = "currency_name_10012",
		description = "currency_intro_0012",
		function_des = "currency_func_0003",
		source = "currency_get_0003",
		type = "base",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["silica"] = 
	{
		id = "silica",
		id_order = 15,
		icon = "Currency/currency_silica",
		name = "currency_name_10013",
		description = "currency_intro_0013",
		function_des = "currency_func_0003",
		source = "currency_get_0003",
		type = "base",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["leather"] = 
	{
		id = "leather",
		id_order = 16,
		icon = "Currency/currency_leather",
		name = "currency_name_10014",
		description = "currency_intro_0014",
		function_des = "currency_func_0003",
		source = "currency_get_0003",
		type = "base",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["nylon"] = 
	{
		id = "nylon",
		id_order = 17,
		icon = "Currency/currency_nylon",
		name = "currency_name_10015",
		description = "currency_intro_0015",
		function_des = "currency_func_0003",
		source = "currency_get_0003",
		type = "base",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["resin"] = 
	{
		id = "resin",
		id_order = 18,
		icon = "Currency/currency_resin",
		name = "currency_name_10016",
		description = "currency_intro_0016",
		function_des = "currency_func_0003",
		source = "currency_get_0003",
		type = "base",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["alloy"] = 
	{
		id = "alloy",
		id_order = 19,
		icon = "Currency/currency_alloy",
		name = "currency_name_10017",
		description = "currency_intro_0017",
		function_des = "currency_func_0003",
		source = "currency_get_0003",
		type = "base",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["carbonfiber"] = 
	{
		id = "carbonfiber",
		id_order = 20,
		icon = "Currency/currency_carbon",
		name = "currency_name_10018",
		description = "currency_intro_0018",
		function_des = "currency_func_0003",
		source = "currency_get_0003",
		type = "base",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["royaljelly"] = 
	{
		id = "royaljelly",
		id_order = 21,
		icon = "Currency/currency_royal",
		name = "currency_name_10019",
		description = "currency_intro_0019",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 1,
		max = 999999,
		initial = 0,
	},
	["powdrink"] = 
	{
		id = "powdrink",
		id_order = 22,
		icon = "Currency/currency_drink",
		name = "currency_name_10020",
		description = "currency_intro_0020",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 2,
		max = 999999,
		initial = 0,
	},
	["calcium"] = 
	{
		id = "calcium",
		id_order = 23,
		icon = "Currency/currency_ca",
		name = "currency_name_10021",
		description = "currency_intro_0021",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 3,
		max = 999999,
		initial = 0,
	},
	["protein"] = 
	{
		id = "protein",
		id_order = 24,
		icon = "Currency/currency_powder",
		name = "currency_name_10022",
		description = "currency_intro_0022",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 4,
		max = 999999,
		initial = 0,
	},
	["eff_tablet"] = 
	{
		id = "eff_tablet",
		id_order = 25,
		icon = "Currency/currency_tablet",
		name = "currency_name_10023",
		description = "currency_intro_0023",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 5,
		max = 999999,
		initial = 0,
	},
	["lecithin"] = 
	{
		id = "lecithin",
		id_order = 26,
		icon = "Currency/currency_lecithin",
		name = "currency_name_10024",
		description = "currency_intro_0024",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 6,
		max = 999999,
		initial = 0,
	},
	["fish_oil"] = 
	{
		id = "fish_oil",
		id_order = 27,
		icon = "Currency/currency_oil",
		name = "currency_name_10025",
		description = "currency_intro_0025",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 7,
		max = 999999,
		initial = 0,
	},
	["voucher1"] = 
	{
		id = "voucher1",
		id_order = 31,
		icon = "Currency/currency_voucher01",
		name = "currency_name_10029",
		description = "currency_intro_0029",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["voucher2"] = 
	{
		id = "voucher2",
		id_order = 32,
		icon = "Currency/currency_voucher02",
		name = "currency_name_10030",
		description = "currency_intro_0030",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["voucher3"] = 
	{
		id = "voucher3",
		id_order = 33,
		icon = "Currency/currency_voucher03",
		name = "currency_name_10031",
		description = "currency_intro_0031",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["additives1"] = 
	{
		id = "additives1",
		id_order = 28,
		icon = "Currency/currency_additives01",
		name = "currency_name_10026",
		description = "currency_intro_0026",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["additives2"] = 
	{
		id = "additives2",
		id_order = 29,
		icon = "Currency/currency_additives02",
		name = "currency_name_10027",
		description = "currency_intro_0027",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["additives3"] = 
	{
		id = "additives3",
		id_order = 30,
		icon = "Currency/currency_additives03",
		name = "currency_name_10028",
		description = "currency_intro_0028",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["coating"] = 
	{
		id = "coating",
		id_order = 34,
		icon = "Currency/currency_coating",
		name = "currency_name_10032",
		description = "currency_intro_0032",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "senior",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["s_alloy"] = 
	{
		id = "s_alloy",
		id_order = 35,
		icon = "Currency/currency_salloy",
		name = "currency_name_10033",
		description = "currency_intro_0033",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "senior",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["nanotube"] = 
	{
		id = "nanotube",
		id_order = 36,
		icon = "Currency/currency_nanotube",
		name = "currency_name_10034",
		description = "currency_intro_0034",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "senior",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["s_plastic"] = 
	{
		id = "s_plastic",
		id_order = 37,
		icon = "Currency/currency_plastic01",
		name = "currency_name_10035",
		description = "currency_intro_0035",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "senior",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["platinor"] = 
	{
		id = "platinor",
		id_order = 38,
		icon = "Currency/currency_platinum",
		name = "currency_name_10036",
		description = "currency_intro_0036",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "senior",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["design"] = 
	{
		id = "design",
		id_order = 39,
		icon = "Currency/currency_drawing",
		name = "currency_name_10037",
		description = "currency_intro_0037",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["star_frag"] = 
	{
		id = "star_frag",
		id_order = 40,
		icon = "Currency/currency_paper",
		name = "currency_name_10038",
		description = "currency_intro_0038",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["gold_coin"] = 
	{
		id = "gold_coin",
		id_order = 41,
		icon = "Currency/currency_gold",
		name = "currency_name_10039",
		description = "currency_intro_0039",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["gemstone"] = 
	{
		id = "gemstone",
		id_order = 42,
		icon = "Currency/currency_gem",
		name = "currency_name_10040",
		description = "currency_intro_0040",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["BattlePass"] = 
	{
		id = "BattlePass",
		id_order = 43,
		icon = "Currency/currency_passport",
		name = "currency_name_10042",
		description = "currency_intro_0041",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["PassEXP"] = 
	{
		id = "PassEXP",
		id_order = 44,
		icon = "Currency/currency_passportexp",
		name = "currency_name_10043",
		description = "currency_intro_0041",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["Activeness"] = 
	{
		id = "Activeness",
		id_order = 45,
		icon = "Shop/C_idle_PassCheck",
		name = "currency_name_10044",
		description = "currency_intro_0041",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["Rune"] = 
	{
		id = "Rune",
		id_order = 49,
		icon = "Currency/currency_additives0202",
		name = "currency_name_10041",
		description = "currency_intro_0006",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["refTimes"] = 
	{
		id = "refTimes",
		id_order = 50,
		icon = "Currency/currency_additives0202",
		name = "currency_name_10041",
		description = "currency_intro_0006",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 10,
		initial = 10,
	},
	["Cardcash"] = 
	{
		id = "Cardcash",
		id_order = 51,
		icon = "Currency/currency_money",
		name = "currency_name_10002",
		description = "currency_intro_0002",
		function_des = "currency_func_0001",
		source = "currency_get_0001",
		type = "",
		order = 0,
		max = 0,
		initial = 0,
	},
	["HamburgerPower"] = 
	{
		id = "HamburgerPower",
		id_order = 52,
		icon = "Currency/currency_passportexp",
		name = "currency_name_HamburgerPower",
		description = "currency_intro_0041",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["Hamburger"] = 
	{
		id = "Hamburger",
		id_order = 53,
		icon = "Currency/currency_hamburger",
		name = "currency_name_Hamburger",
		description = "currency_intro_0041",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "",
		order = 0,
		max = 999999,
		initial = 0,
	},
	["TimeJump"] = 
	{
		id = "TimeJump",
		id_order = 54,
		icon = "Currency/currency_coating",
		name = "currency_name_10032",
		description = "currency_intro_0032",
		function_des = "currency_func_0001",
		source = "currency_get",
		type = "TimeJump",
		order = 8,
		max = 0,
		initial = 0,
	},
}