LuaConfig["EmployeeConfig"] = 
{
	[10010101] = 
	{
		id = 10010101,
		job = "waiter",
		features = {
			[1]="onhook_add_pp_add",
		},
		unlock = {
			[1]="vpcard",
			[2]=280,
		},
		partEvent = "1018001",
		workEvent = "1018001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10010102] = 
	{
		id = 10010102,
		job = "waiter",
		features = {
			[1]="onhook_add_pp_add",
		},
		unlock = {
			[1]="vpcard",
			[2]=800,
		},
		partEvent = "1018101",
		workEvent = "1018101",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10010103] = 
	{
		id = 10010103,
		job = "waiter",
		features = {
			[1]="onhook_add_pp_add",
		},
		unlock = {
			[1]="vpcard",
			[2]=3620,
		},
		partEvent = "1018201",
		workEvent = "1018201",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10010104] = 
	{
		id = 10010104,
		job = "manager",
		features = {
			[1]="Investor_addition",
		},
		unlock = {
			[1]="vpcard",
			[2]=3900,
		},
		partEvent = "1001001",
		workEvent = "1001001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "manager_norm_coat/manager_norm_pants;manager_burly_coat/manager_burly_pants;manager_fat_coat/manager_fat_pants;manager_girl_coat/manager_girl_pants",
		prefeb = "",
	},
	[10020101] = 
	{
		id = 10020101,
		job = "coach",
		features = {
			[1]="bat_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=15,
		},
		partEvent = "1002000",
		workEvent = "1002001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10020102] = 
	{
		id = 10020102,
		job = "coach",
		features = {
			[1]="bat_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=750,
		},
		partEvent = "1002000",
		workEvent = "1002001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10020103] = 
	{
		id = 10020103,
		job = "waiter",
		features = {
			[1]="bat_timecons",
		},
		unlock = {
			[1]="vpcard",
			[2]=4075,
		},
		partEvent = "1003001",
		workEvent = "1003002",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10040101] = 
	{
		id = 10040101,
		job = "guard",
		features = {
			[1]="guard_add",
			[2]="safety_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=150,
		},
		partEvent = "49999",
		workEvent = "41007",
		restEvent = "40001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "guard_norm_coat/guard_norm_pants;guard_burly_coat/guard_burly_pants;guard_fat_coat/guard_fat_pants;guard_girl_coat/guard_girl_pants",
		prefeb = "",
	},
	[10040102] = 
	{
		id = 10040102,
		job = "guard",
		features = {
			[1]="guard_add",
			[2]="safety_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=700,
		},
		partEvent = "49999",
		workEvent = "41007",
		restEvent = "40001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "guard_norm_coat/guard_norm_pants;guard_burly_coat/guard_burly_pants;guard_fat_coat/guard_fat_pants;guard_girl_coat/guard_girl_pants",
		prefeb = "",
	},
	[10040103] = 
	{
		id = 10040103,
		job = "guard",
		features = {
			[1]="guard_add",
			[2]="safety_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=1350,
		},
		partEvent = "49999",
		workEvent = "41007",
		restEvent = "40001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "guard_norm_coat/guard_norm_pants;guard_burly_coat/guard_burly_pants;guard_fat_coat/guard_fat_pants;guard_girl_coat/guard_girl_pants",
		prefeb = "",
	},
	[10040104] = 
	{
		id = 10040104,
		job = "guard",
		features = {
			[1]="guard_add",
			[2]="safety_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=4285,
		},
		partEvent = "49999",
		workEvent = "41007",
		restEvent = "40001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "guard_norm_coat/guard_norm_pants;guard_burly_coat/guard_burly_pants;guard_fat_coat/guard_fat_pants;guard_girl_coat/guard_girl_pants",
		prefeb = "",
	},
	[10040105] = 
	{
		id = 10040105,
		job = "guard",
		features = {
			[1]="guard_add",
			[2]="safety_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=8000,
		},
		partEvent = "49999",
		workEvent = "41007",
		restEvent = "40001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "guard_norm_coat/guard_norm_pants;guard_burly_coat/guard_burly_pants;guard_fat_coat/guard_fat_pants;guard_girl_coat/guard_girl_pants",
		prefeb = "",
	},
	[10050101] = 
	{
		id = 10050101,
		job = "repairman",
		features = {
			[1]="repairman_add",
			[2]="upkeep_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=865,
		},
		partEvent = "50001",
		workEvent = "51001",
		restEvent = "50000",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "repairman_norm_coat/repairman_norm_pants;repairman_burly_coat/repairman_burly_pants;repairman_fat_coat/repairman_fat_pants;repairman_girl_coat/repairman_girl_pants",
		prefeb = "",
	},
	[10050102] = 
	{
		id = 10050102,
		job = "repairman",
		features = {
			[1]="repairman_add",
			[2]="upkeep_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=3405,
		},
		partEvent = "50001",
		workEvent = "51001",
		restEvent = "50000",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "repairman_norm_coat/repairman_norm_pants;repairman_burly_coat/repairman_burly_pants;repairman_fat_coat/repairman_fat_pants;repairman_girl_coat/repairman_girl_pants",
		prefeb = "",
	},
	[10050103] = 
	{
		id = 10050103,
		job = "repairman",
		features = {
			[1]="repairman_add",
			[2]="upkeep_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=3555,
		},
		partEvent = "50001",
		workEvent = "51001",
		restEvent = "50000",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "repairman_norm_coat/repairman_norm_pants;repairman_burly_coat/repairman_burly_pants;repairman_fat_coat/repairman_fat_pants;repairman_girl_coat/repairman_girl_pants",
		prefeb = "",
	},
	[10050104] = 
	{
		id = 10050104,
		job = "repairman",
		features = {
			[1]="repairman_add",
			[2]="upkeep_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=7000,
		},
		partEvent = "50001",
		workEvent = "51001",
		restEvent = "50000",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "repairman_norm_coat/repairman_norm_pants;repairman_burly_coat/repairman_burly_pants;repairman_fat_coat/repairman_fat_pants;repairman_girl_coat/repairman_girl_pants",
		prefeb = "",
	},
	[10050105] = 
	{
		id = 10050105,
		job = "repairman",
		features = {
			[1]="repairman_add",
			[2]="upkeep_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=10000,
		},
		partEvent = "50001",
		workEvent = "51001",
		restEvent = "50000",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "repairman_norm_coat/repairman_norm_pants;repairman_burly_coat/repairman_burly_pants;repairman_fat_coat/repairman_fat_pants;repairman_girl_coat/repairman_girl_pants",
		prefeb = "",
	},
	[10060101] = 
	{
		id = 10060101,
		job = "cleaner",
		features = {
			[1]="cleaner_add",
			[2]="cleanliness_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=80,
		},
		partEvent = "60000",
		workEvent = "61001",
		restEvent = "60001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cleaner_norm_coat/cleaner_norm_pants;cleaner_burly_coat/cleaner_burly_pants;cleaner_fat_coat/cleaner_fat_pants;cleaner_girl_coat/cleaner_girl_pants",
		prefeb = "",
	},
	[10060102] = 
	{
		id = 10060102,
		job = "cleaner",
		features = {
			[1]="cleaner_add",
			[2]="cleanliness_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=650,
		},
		partEvent = "60000",
		workEvent = "61001",
		restEvent = "60001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cleaner_norm_coat/cleaner_norm_pants;cleaner_burly_coat/cleaner_burly_pants;cleaner_fat_coat/cleaner_fat_pants;cleaner_girl_coat/cleaner_girl_pants",
		prefeb = "",
	},
	[10060103] = 
	{
		id = 10060103,
		job = "cleaner",
		features = {
			[1]="cleaner_add",
			[2]="cleanliness_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=3945,
		},
		partEvent = "60000",
		workEvent = "61001",
		restEvent = "60001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cleaner_norm_coat/cleaner_norm_pants;cleaner_burly_coat/cleaner_burly_pants;cleaner_fat_coat/cleaner_fat_pants;cleaner_girl_coat/cleaner_girl_pants",
		prefeb = "",
	},
	[10060104] = 
	{
		id = 10060104,
		job = "cleaner",
		features = {
			[1]="cleaner_add",
			[2]="cleanliness_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=5000,
		},
		partEvent = "60000",
		workEvent = "61001",
		restEvent = "60001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cleaner_norm_coat/cleaner_norm_pants;cleaner_burly_coat/cleaner_burly_pants;cleaner_fat_coat/cleaner_fat_pants;cleaner_girl_coat/cleaner_girl_pants",
		prefeb = "",
	},
	[10060105] = 
	{
		id = 10060105,
		job = "cleaner",
		features = {
			[1]="cleaner_add",
			[2]="cleanliness_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=8000,
		},
		partEvent = "60000",
		workEvent = "61001",
		restEvent = "60001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cleaner_norm_coat/cleaner_norm_pants;cleaner_burly_coat/cleaner_burly_pants;cleaner_fat_coat/cleaner_fat_pants;cleaner_girl_coat/cleaner_girl_pants",
		prefeb = "",
	},
	[10070101] = 
	{
		id = 10070101,
		job = "cashier",
		features = {
			[1]="cashier_add",
			[2]="consume_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=1195,
		},
		partEvent = "70000",
		workEvent = "71002",
		restEvent = "70001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cashier_norm_coat/cashier_norm_pants;cashier_burly_coat/cashier_burly_pants;cashier_fat_coat/cashier_fat_pants;cashier_girl_coat/cashier_girl_pants",
		prefeb = "",
	},
	[10070102] = 
	{
		id = 10070102,
		job = "cashier",
		features = {
			[1]="cashier_add",
			[2]="consume_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=4605,
		},
		partEvent = "70000",
		workEvent = "71002",
		restEvent = "70001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cashier_norm_coat/cashier_norm_pants;cashier_burly_coat/cashier_burly_pants;cashier_fat_coat/cashier_fat_pants;cashier_girl_coat/cashier_girl_pants",
		prefeb = "",
	},
	[10070103] = 
	{
		id = 10070103,
		job = "cashier",
		features = {
			[1]="cashier_add",
			[2]="consume_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=5115,
		},
		partEvent = "70000",
		workEvent = "71002",
		restEvent = "70001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cashier_norm_coat/cashier_norm_pants;cashier_burly_coat/cashier_burly_pants;cashier_fat_coat/cashier_fat_pants;cashier_girl_coat/cashier_girl_pants",
		prefeb = "",
	},
	[10070104] = 
	{
		id = 10070104,
		job = "cashier",
		features = {
			[1]="cashier_add",
			[2]="consume_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=5685,
		},
		partEvent = "70000",
		workEvent = "71002",
		restEvent = "70001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cashier_norm_coat/cashier_norm_pants;cashier_burly_coat/cashier_burly_pants;cashier_fat_coat/cashier_fat_pants;cashier_girl_coat/cashier_girl_pants",
		prefeb = "",
	},
	[10070105] = 
	{
		id = 10070105,
		job = "cashier",
		features = {
			[1]="cashier_add",
			[2]="consume_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=6315,
		},
		partEvent = "70000",
		workEvent = "71002",
		restEvent = "70001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cashier_norm_coat/cashier_norm_pants;cashier_burly_coat/cashier_burly_pants;cashier_fat_coat/cashier_fat_pants;cashier_girl_coat/cashier_girl_pants",
		prefeb = "",
	},
	[10080101] = 
	{
		id = 10080101,
		job = "cheerleader",
		features = {
			[1]="waiter_add",
			[2]="SQI_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=650,
		},
		partEvent = "80000",
		workEvent = "82001",
		restEvent = "80001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cheerleader_norm_coat/cheerleader_norm_pants;cheerleader_burly_coat/cheerleader_burly_pants;cheerleader_fat_coat/cheerleader_fat_pants;cheerleader_girl_coat/cheerleader_girl_pants",
		prefeb = "",
	},
	[10080102] = 
	{
		id = 10080102,
		job = "cheerleader",
		features = {
			[1]="waiter_add",
			[2]="SQI_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=1200,
		},
		partEvent = "80000",
		workEvent = "82001",
		restEvent = "80001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cheerleader_norm_coat/cheerleader_norm_pants;cheerleader_burly_coat/cheerleader_burly_pants;cheerleader_fat_coat/cheerleader_fat_pants;cheerleader_girl_coat/cheerleader_girl_pants",
		prefeb = "",
	},
	[10080103] = 
	{
		id = 10080103,
		job = "cheerleader",
		features = {
			[1]="waiter_add",
			[2]="SQI_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=3977,
		},
		partEvent = "80000",
		workEvent = "82001",
		restEvent = "80001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cheerleader_norm_coat/cheerleader_norm_pants;cheerleader_burly_coat/cheerleader_burly_pants;cheerleader_fat_coat/cheerleader_fat_pants;cheerleader_girl_coat/cheerleader_girl_pants",
		prefeb = "",
	},
	[10080104] = 
	{
		id = 10080104,
		job = "cheerleader",
		features = {
			[1]="waiter_add",
			[2]="SQI_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=4390,
		},
		partEvent = "80000",
		workEvent = "82001",
		restEvent = "80001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cheerleader_norm_coat/cheerleader_norm_pants;cheerleader_burly_coat/cheerleader_burly_pants;cheerleader_fat_coat/cheerleader_fat_pants;cheerleader_girl_coat/cheerleader_girl_pants",
		prefeb = "",
	},
	[10080105] = 
	{
		id = 10080105,
		job = "cheerleader",
		features = {
			[1]="waiter_add",
			[2]="SQI_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=4665,
		},
		partEvent = "80000",
		workEvent = "82001",
		restEvent = "80001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "cheerleader_norm_coat/cheerleader_norm_pants;cheerleader_burly_coat/cheerleader_burly_pants;cheerleader_fat_coat/cheerleader_fat_pants;cheerleader_girl_coat/cheerleader_girl_pants",
		prefeb = "",
	},
	[10090101] = 
	{
		id = 10090101,
		job = "coach",
		features = {
			[1]="pit_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=175,
		},
		partEvent = "1004000",
		workEvent = "1004001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10090102] = 
	{
		id = 10090102,
		job = "coach",
		features = {
			[1]="pit_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=1500,
		},
		partEvent = "1004000",
		workEvent = "1004001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10090103] = 
	{
		id = 10090103,
		job = "waiter",
		features = {
			[1]="pit_timecons",
		},
		unlock = {
			[1]="vpcard",
			[2]=4985,
		},
		partEvent = "1005001",
		workEvent = "1005002",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10100101] = 
	{
		id = 10100101,
		job = "waiter",
		features = {
			[1]="cafe_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=490,
		},
		partEvent = "1006001",
		workEvent = "1006001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10100102] = 
	{
		id = 10100102,
		job = "waiter",
		features = {
			[1]="cafe_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=700,
		},
		partEvent = "1007001",
		workEvent = "1007001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10110101] = 
	{
		id = 10110101,
		job = "salesman",
		features = {
			[1]="salesman_add",
			[2]="ardor_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=1155,
		},
		partEvent = "90000",
		workEvent = "91001",
		restEvent = "90001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "",
		prefeb = "Role/Employee/em_seller",
	},
	[10110102] = 
	{
		id = 10110102,
		job = "salesman",
		features = {
			[1]="salesman_add",
			[2]="ardor_pp",
		},
		unlock = {
			[1]="vpcard",
			[2]=4365,
		},
		partEvent = "90000",
		workEvent = "92001",
		restEvent = "90001",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "",
		prefeb = "Role/Employee/em_seller",
	},
	[10120101] = 
	{
		id = 10120101,
		job = "waiter",
		features = {
			[1]="bath_earnings_A",
		},
		unlock = {
			[1]="vpcard",
			[2]=1860,
		},
		partEvent = "1010001",
		workEvent = "1010001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10130101] = 
	{
		id = 10130101,
		job = "coach",
		features = {
			[1]="run_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=695,
		},
		partEvent = "1008001",
		workEvent = "1008001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10130102] = 
	{
		id = 10130102,
		job = "coach",
		features = {
			[1]="run_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=2500,
		},
		partEvent = "1008001",
		workEvent = "1008001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10130103] = 
	{
		id = 10130103,
		job = "waiter",
		features = {
			[1]="run_timecons",
		},
		unlock = {
			[1]="vpcard",
			[2]=8755,
		},
		partEvent = "1009001",
		workEvent = "1009002",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10140101] = 
	{
		id = 10140101,
		job = "admin",
		features = {
			[1]="bar_extraexp_pp_add",
		},
		unlock = {
			[1]="vpcard",
			[2]=1455,
		},
		partEvent = "1011001",
		workEvent = "1011001",
		restEvent = "",
		strikeEvent = "760001",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "admin_norm_coat/admin_norm_pants;admin_burly_coat/admin_burly_pants;admin_fat_coat/admin_fat_pants;admin_girl_coat/admin_girl_pants",
		prefeb = "",
	},
	[10140102] = 
	{
		id = 10140102,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=200,
		},
		partEvent = "",
		workEvent = "931002",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10140103] = 
	{
		id = 10140103,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=200,
		},
		partEvent = "",
		workEvent = "931004",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10150101] = 
	{
		id = 10150101,
		job = "admin",
		features = {
			[1]="meet_extraexp_pp_add",
		},
		unlock = {
			[1]="vpcard",
			[2]=1770,
		},
		partEvent = "1012001",
		workEvent = "1012001",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "admin_norm_coat/admin_norm_pants;admin_burly_coat/admin_burly_pants;admin_fat_coat/admin_fat_pants;admin_girl_coat/admin_girl_pants",
		prefeb = "",
	},
	[10150102] = 
	{
		id = 10150102,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=1771,
		},
		partEvent = "",
		workEvent = "934002",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10150103] = 
	{
		id = 10150103,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=1772,
		},
		partEvent = "",
		workEvent = "934003",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10160101] = 
	{
		id = 10160101,
		job = "admin",
		features = {
			[1]="phy_extraexp_pp_add",
		},
		unlock = {
			[1]="vpcard",
			[2]=2625,
		},
		partEvent = "1013001",
		workEvent = "1013001",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "admin_norm_coat/admin_norm_pants;admin_burly_coat/admin_burly_pants;admin_fat_coat/admin_fat_pants;admin_girl_coat/admin_girl_pants",
		prefeb = "",
	},
	[10160102] = 
	{
		id = 10160102,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=2626,
		},
		partEvent = "",
		workEvent = "935002",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10160103] = 
	{
		id = 10160103,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=2627,
		},
		partEvent = "",
		workEvent = "935004",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10170101] = 
	{
		id = 10170101,
		job = "admin",
		features = {
			[1]="spa_extraexp_pp_add",
		},
		unlock = {
			[1]="vpcard",
			[2]=1685,
		},
		partEvent = "1014001",
		workEvent = "1014001",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "admin_norm_coat/admin_norm_pants;admin_burly_coat/admin_burly_pants;admin_fat_coat/admin_fat_pants;admin_girl_coat/admin_girl_pants",
		prefeb = "",
	},
	[10170102] = 
	{
		id = 10170102,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=1686,
		},
		partEvent = "",
		workEvent = "936002",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10170103] = 
	{
		id = 10170103,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=1687,
		},
		partEvent = "",
		workEvent = "936003",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10180101] = 
	{
		id = 10180101,
		job = "admin",
		features = {
			[1]="tra_extraexp_pp_add",
		},
		unlock = {
			[1]="vpcard",
			[2]=1610,
		},
		partEvent = "1015001",
		workEvent = "1015001",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "admin_norm_coat/admin_norm_pants;admin_burly_coat/admin_burly_pants;admin_fat_coat/admin_fat_pants;admin_girl_coat/admin_girl_pants",
		prefeb = "",
	},
	[10180102] = 
	{
		id = 10180102,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=1611,
		},
		partEvent = "",
		workEvent = "933002",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10180103] = 
	{
		id = 10180103,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=1612,
		},
		partEvent = "",
		workEvent = "933003",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10180104] = 
	{
		id = 10180104,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=1613,
		},
		partEvent = "",
		workEvent = "933004",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10190101] = 
	{
		id = 10190101,
		job = "admin",
		features = {
			[1]="fit_extraexp_pp_add",
		},
		unlock = {
			[1]="vpcard",
			[2]=2725,
		},
		partEvent = "1016001",
		workEvent = "1016001",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "admin_norm_coat/admin_norm_pants;admin_burly_coat/admin_burly_pants;admin_fat_coat/admin_fat_pants;admin_girl_coat/admin_girl_pants",
		prefeb = "",
	},
	[10190102] = 
	{
		id = 10190102,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=2726,
		},
		partEvent = "",
		workEvent = "932002",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10190103] = 
	{
		id = 10190103,
		job = "",
		features = nil,
		unlock = {
			[1]="vpcard",
			[2]=2727,
		},
		partEvent = "",
		workEvent = "932003",
		restEvent = "",
		strikeEvent = "",
		bodily = "",
		parts = "",
		material = "",
		prefeb = "",
	},
	[10210101] = 
	{
		id = 10210101,
		job = "guard",
		features = {
			[1]="extraview_re_pp_add",
		},
		unlock = {
			[1]="vpcard",
			[2]=1774,
		},
		partEvent = "1017001",
		workEvent = "1017001",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "guard_norm_coat/guard_norm_pants;guard_burly_coat/guard_burly_pants;guard_fat_coat/guard_fat_pants;guard_girl_coat/guard_girl_pants",
		prefeb = "",
	},
	[10260101] = 
	{
		id = 10260101,
		job = "coach",
		features = {
			[1]="cat_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=16587,
		},
		partEvent = "",
		workEvent = "",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10260102] = 
	{
		id = 10260102,
		job = "coach",
		features = {
			[1]="cat_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=21165,
		},
		partEvent = "",
		workEvent = "",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10260103] = 
	{
		id = 10260103,
		job = "waiter",
		features = {
			[1]="cat_timecons",
		},
		unlock = {
			[1]="vpcard",
			[2]=24127,
		},
		partEvent = "",
		workEvent = "",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10270101] = 
	{
		id = 10270101,
		job = "coach",
		features = {
			[1]="box_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=16932,
		},
		partEvent = "",
		workEvent = "",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10270102] = 
	{
		id = 10270102,
		job = "coach",
		features = {
			[1]="box_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=22515,
		},
		partEvent = "",
		workEvent = "",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10270103] = 
	{
		id = 10270103,
		job = "waiter",
		features = {
			[1]="box_timecons",
		},
		unlock = {
			[1]="vpcard",
			[2]=25102,
		},
		partEvent = "",
		workEvent = "",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10280101] = 
	{
		id = 10280101,
		job = "waiter",
		features = {
			[1]="bath_earnings_B",
		},
		unlock = {
			[1]="vpcard",
			[2]=19737,
		},
		partEvent = "",
		workEvent = "",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10290101] = 
	{
		id = 10290101,
		job = "waiter",
		features = {
			[1]="sho_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=17372,
		},
		partEvent = "",
		workEvent = "",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "waiter_norm_coat/waiter_norm_pants;waiter_burly_coat/waiter_burly_pants;waiter_fat_coat/waiter_fat_pants;waiter_girl_coat/waiter_girl_pants",
		prefeb = "",
	},
	[10290102] = 
	{
		id = 10290102,
		job = "coach",
		features = {
			[1]="sho_earnings",
		},
		unlock = {
			[1]="vpcard",
			[2]=22515,
		},
		partEvent = "",
		workEvent = "",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
	[10290103] = 
	{
		id = 10290103,
		job = "coach",
		features = {
			[1]="sho_timecons",
		},
		unlock = {
			[1]="vpcard",
			[2]=24907,
		},
		partEvent = "",
		workEvent = "",
		restEvent = "",
		strikeEvent = "700003",
		bodily = "norm;burly;fat;girl",
		parts = "Body_NM_Body/Body_NM_Leg;Body_SM_Body/Body_SM_Leg;Body/Leg;Body/Leg",
		material = "coach_norm_coat/coach_norm_pants;coach_burly_coat/coach_burly_pants;coach_fat_coat/coach_fat_pants;coach_girl_coat/coach_girl_pants",
		prefeb = "",
	},
}