LuaConfig["FunctionConfig"] = 
{
	["ba_wt"] = 
	{
		id = "ba_wt",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加保安工作时间（单位s）",
		editor_comment3 = "guard_work_num_add",
		unit = "function_unit_s",
		sign = "plus",
		icon = "Function/function_workingup",
		name = "",
		tips = "tip_ba_wt",
	},
	["bj_wt"] = 
	{
		id = "bj_wt",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加保洁员工作时间（单位s）",
		editor_comment3 = "cleaner_work_num_add",
		unit = "function_unit_s",
		sign = "plus",
		icon = "Function/function_workingup",
		name = "",
		tips = "tip_bj_wt",
	},
	["sy_wt"] = 
	{
		id = "sy_wt",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加收银员工作时间（单位s）",
		editor_comment3 = "cashier_work_num_add",
		unit = "function_unit_s",
		sign = "plus",
		icon = "Function/function_workingup",
		name = "",
		tips = "tip_sy_wt",
	},
	["fw_wt"] = 
	{
		id = "fw_wt",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加服务员工作时间（单位s）",
		editor_comment3 = "waiter_work_num_add",
		unit = "function_unit_s",
		sign = "plus",
		icon = "Function/function_workingup",
		name = "",
		tips = "tip_fw_wt",
	},
	["xs_wt"] = 
	{
		id = "xs_wt",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加销售员工作时间（单位s）",
		editor_comment3 = "salesman_work_num_add",
		unit = "function_unit_s",
		sign = "plus",
		icon = "Function/function_workingup",
		name = "",
		tips = "tip_xs_wt",
	},
	["ba_rt"] = 
	{
		id = "ba_rt",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "减少保安休息时间（单位s）",
		editor_comment3 = "guard_rest_num_sub",
		unit = "function_unit_s",
		sign = "minus",
		icon = "Function/function_restdown",
		name = "",
		tips = "tip_ba_rt",
	},
	["bj_rt"] = 
	{
		id = "bj_rt",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "减少保洁员休息时间（单位s）",
		editor_comment3 = "cleaner_rest_num_sub",
		unit = "function_unit_s",
		sign = "minus",
		icon = "Function/function_restdown",
		name = "",
		tips = "tip_bj_rt",
	},
	["sy_rt"] = 
	{
		id = "sy_rt",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "减少收银员休息时间（单位s）",
		editor_comment3 = "cashier_rest_num_sub",
		unit = "function_unit_s",
		sign = "minus",
		icon = "Function/function_restdown",
		name = "",
		tips = "tip_sy_rt",
	},
	["fw_rt"] = 
	{
		id = "fw_rt",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "减少服务员休息时间（单位s）",
		editor_comment3 = "waiter_rest_num_sub",
		unit = "function_unit_s",
		sign = "minus",
		icon = "Function/function_restdown",
		name = "",
		tips = "tip_fw_rt",
	},
	["xs_rt"] = 
	{
		id = "xs_rt",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "减少销售员休息时间（单位s）",
		editor_comment3 = "salesman_rest_num_sub",
		unit = "function_unit_s",
		sign = "minus",
		icon = "Function/function_restdown",
		name = "",
		tips = "tip_xs_rt",
	},
	["r_time"] = 
	{
		id = "r_time",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "减少修理工恢复时间（单位s）",
		editor_comment3 = "repairman_CD_num_sub",
		unit = "function_unit_s",
		sign = "minus",
		icon = "Function/function_retimedown",
		name = "",
		tips = "",
	},
	["eng_num"] = 
	{
		id = "eng_num",
		type = "",
		editor_comment1 = "cardbuild",
		editor_comment2 = "增加加速能量值上限（百分比）",
		editor_comment3 = "speedup_power_pp_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_energy01",
		name = "",
		tips = "tip_topenergy",
	},
	["pla_num"] = 
	{
		id = "pla_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加塑料上限",
		editor_comment3 = "pla_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_plastic01up",
		name = "",
		tips = "tip_topplastic",
	},
	["wood_num"] = 
	{
		id = "wood_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加木材上限",
		editor_comment3 = "wood_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_woodup",
		name = "",
		tips = "tip_topwood",
	},
	["iron_num"] = 
	{
		id = "iron_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加钢铁上限",
		editor_comment3 = "iron_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_ironup",
		name = "",
		tips = "tip_topiron",
	},
	["fab_num"] = 
	{
		id = "fab_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加布料上限",
		editor_comment3 = "fab_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_clothup",
		name = "",
		tips = "tip_topcloth",
	},
	["lea_num"] = 
	{
		id = "lea_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加皮革上限",
		editor_comment3 = "lea_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_leatherup",
		name = "",
		tips = "tip_topleather",
	},
	["sil_num"] = 
	{
		id = "sil_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加硅胶上限",
		editor_comment3 = "sil_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_silicaup",
		name = "",
		tips = "tip_topsilica",
	},
	["nyl_num"] = 
	{
		id = "nyl_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加尼龙上限",
		editor_comment3 = "nyl_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_nylonup",
		name = "",
		tips = "tip_topnylon",
	},
	["res_num"] = 
	{
		id = "res_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加树脂上限",
		editor_comment3 = "res_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_resinup",
		name = "",
		tips = "tip_topresin",
	},
	["alloy_num"] = 
	{
		id = "alloy_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加合金上限",
		editor_comment3 = "alloy_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_alloyup",
		name = "",
		tips = "tip_topalloy",
	},
	["car_num"] = 
	{
		id = "car_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加碳纤维上限",
		editor_comment3 = "car_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_carbonup",
		name = "",
		tips = "tip_topcarbon",
	},
	["pla_sp"] = 
	{
		id = "pla_sp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加塑料恢复速度（单位/min）",
		editor_comment3 = "pla_recover_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_plastic",
		name = "",
		tips = "tip_replasic",
	},
	["wood_sp"] = 
	{
		id = "wood_sp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加木材恢复速度（单位/min）",
		editor_comment3 = "wood_recover_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_wood",
		name = "",
		tips = "tip_rewood",
	},
	["iron_sp"] = 
	{
		id = "iron_sp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加钢铁恢复速度（单位/min）",
		editor_comment3 = "iron_recover_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_iron",
		name = "",
		tips = "tip_reiron",
	},
	["fab_sp"] = 
	{
		id = "fab_sp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加布料恢复速度（单位/min）",
		editor_comment3 = "fab_recover_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_cloth",
		name = "",
		tips = "tip_recloth",
	},
	["lea_sp"] = 
	{
		id = "lea_sp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加皮革恢复速度（单位/min）",
		editor_comment3 = "lea_recover_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_leather",
		name = "",
		tips = "tip_releather",
	},
	["sil_sp"] = 
	{
		id = "sil_sp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加硅胶恢复速度（单位/min）",
		editor_comment3 = "sil_recover_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_silica",
		name = "",
		tips = "tip_resilica",
	},
	["nyl_sp"] = 
	{
		id = "nyl_sp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加尼龙恢复速度（单位/min）",
		editor_comment3 = "nyl_recover_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_nylon",
		name = "",
		tips = "tip_renylon",
	},
	["res_sp"] = 
	{
		id = "res_sp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加树脂恢复速度（单位/min）",
		editor_comment3 = "res_recover_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_resin",
		name = "",
		tips = "tip_reresin",
	},
	["alloy_sp"] = 
	{
		id = "alloy_sp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加合金恢复速度（单位/min）",
		editor_comment3 = "alloy_recover_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_alloy",
		name = "",
		tips = "tip_realloy",
	},
	["car_sp"] = 
	{
		id = "car_sp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加碳纤维恢复速度（单位/min）",
		editor_comment3 = "car_recover_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_carbon",
		name = "",
		tips = "tip_recarbon",
	},
	["peo_num"] = 
	{
		id = "peo_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加同时交易人数上限",
		editor_comment3 = "buyers_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_Tradeup",
		name = "",
		tips = "",
	},
	["zgA"] = 
	{
		id = "zgA",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加展示柜A容量上限",
		editor_comment3 = "showcaseA_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_capacityup",
		name = "",
		tips = "tip_show_stock",
	},
	["zgB"] = 
	{
		id = "zgB",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加展示柜B容量上限",
		editor_comment3 = "showcaseB_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_capacityup",
		name = "",
		tips = "tip_show_stock",
	},
	["zgC"] = 
	{
		id = "zgC",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加展示柜C容量上限",
		editor_comment3 = "showcaseC_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_capacityup",
		name = "",
		tips = "tip_show_stock",
	},
	["equip_matime"] = 
	{
		id = "equip_matime",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "减少所有装备制作时间（百分比）",
		editor_comment3 = "equip_matime_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "",
		name = "",
		tips = "",
	},
	["eng_cost"] = 
	{
		id = "eng_cost",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备交易额外能量花费减少（百分比）",
		editor_comment3 = "energy_cost_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Function/function_exenergydown",
		name = "",
		tips = "",
	},
	["bat_extra"] = 
	{
		id = "bat_extra",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "对球棒消耗体力加成收益(球棒类型装备消耗体力额外花费时装备价值翻倍的基础上再提升）",
		editor_comment3 = "bat_extra_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["clo_extra"] = 
	{
		id = "clo_extra",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "对球衣消耗体力加成收益(球衣类型装备消耗体力额外花费时装备价值翻倍的基础上再提升）",
		editor_comment3 = "clo_extra_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["cap_extra"] = 
	{
		id = "cap_extra",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "对球帽消耗体力加成收益(球帽类型装备消耗体力额外花费时装备价值翻倍的基础上再提升）",
		editor_comment3 = "cap_extra_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["sho_extra"] = 
	{
		id = "sho_extra",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "对球鞋消耗体力加成收益(球鞋类型装备消耗体力额外花费时装备价值翻倍的基础上再提升）",
		editor_comment3 = "sho_extra_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["glo_extra"] = 
	{
		id = "glo_extra",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "对手套消耗体力加成收益(手套类型装备消耗体力额外花费时装备价值翻倍的基础上再提升）",
		editor_comment3 = "glo_extra_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["pro_extra"] = 
	{
		id = "pro_extra",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "对护具消耗体力加成收益(护具类型装备消耗体力额外花费时装备价值翻倍的基础上再提升）",
		editor_comment3 = "pro_extra_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["all_extra"] = 
	{
		id = "all_extra",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "对所有装备消耗体力加成收益",
		editor_comment3 = "all_extra_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["re_pla"] = 
	{
		id = "re_pla",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备制作塑料材料减少",
		editor_comment3 = "pla_recost_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_plastic01",
		name = "",
		tips = "",
	},
	["re_wood"] = 
	{
		id = "re_wood",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备制作木头材料减少",
		editor_comment3 = "wood_recost_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_wood",
		name = "",
		tips = "",
	},
	["re_fab"] = 
	{
		id = "re_fab",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备制作布料材料减少",
		editor_comment3 = "fab_recost_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_cloth",
		name = "",
		tips = "",
	},
	["re_lea"] = 
	{
		id = "re_lea",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备制作皮革材料减少",
		editor_comment3 = "lea_recost_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_leather",
		name = "",
		tips = "",
	},
	["re_iron"] = 
	{
		id = "re_iron",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备制作钢铁材料减少",
		editor_comment3 = "iron_recost_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_iron",
		name = "",
		tips = "",
	},
	["re_sil"] = 
	{
		id = "re_sil",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备制作硅胶材料减少",
		editor_comment3 = "sil_recost_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_silica",
		name = "",
		tips = "",
	},
	["re_nylon"] = 
	{
		id = "re_nylon",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备制作尼龙材料减少",
		editor_comment3 = "nylon_recost_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_nylon",
		name = "",
		tips = "",
	},
	["re_res"] = 
	{
		id = "re_res",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备制作树脂材料减少",
		editor_comment3 = "res_recost_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_resin",
		name = "",
		tips = "",
	},
	["re_alloy"] = 
	{
		id = "re_alloy",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备制作合金材料减少",
		editor_comment3 = "alloy_recost_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_alloy",
		name = "",
		tips = "",
	},
	["re_carb"] = 
	{
		id = "re_carb",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "装备制作碳纤维材料减少",
		editor_comment3 = "carb_recost_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_carbon",
		name = "",
		tips = "",
	},
	["bat_rarity"] = 
	{
		id = "bat_rarity",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "球棒类装备制作出高品质概率提升",
		editor_comment3 = "bat_rarity_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_valueup",
		name = "",
		tips = "",
	},
	["clo_rarity"] = 
	{
		id = "clo_rarity",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "球衣类装备制作出高品质概率提升",
		editor_comment3 = "clo_rarity_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_valueup",
		name = "",
		tips = "",
	},
	["cap_rarity"] = 
	{
		id = "cap_rarity",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "球帽类装备制作出高品质概率提升",
		editor_comment3 = "cap_rarity_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_valueup",
		name = "",
		tips = "",
	},
	["sho_rarity"] = 
	{
		id = "sho_rarity",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "球鞋类装备制作出高品质概率提升",
		editor_comment3 = "sho_rarity_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_valueup",
		name = "",
		tips = "",
	},
	["glo_rarity"] = 
	{
		id = "glo_rarity",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "手套类装备制作出高品质概率提升",
		editor_comment3 = "glo_rarity_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_valueup",
		name = "",
		tips = "",
	},
	["pro_rarity"] = 
	{
		id = "pro_rarity",
		type = "",
		editor_comment1 = "升星表",
		editor_comment2 = "护具类装备制作出高品质概率提升",
		editor_comment3 = "pro_rarity_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_valueup",
		name = "",
		tips = "",
	},
	["cash"] = 
	{
		id = "cash",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "设施每分钟产钱",
		editor_comment3 = "cash_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_offlineCashup",
		name = "",
		tips = "tip_cash",
	},
	["cash_use"] = 
	{
		id = "cash_use",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "客人使用设施付费",
		editor_comment3 = "cash_use_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_cashup",
		name = "",
		tips = "tip_cash_use",
	},
	["vpcard"] = 
	{
		id = "vpcard",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "获得vpcard",
		editor_comment3 = "vpcard_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_vpcard01",
		name = "",
		tips = "tip_vpcard",
	},
	["shop_card"] = 
	{
		id = "shop_card",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "设施每分钟产购物卡",
		editor_comment3 = "shop_card_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_card01",
		name = "",
		tips = "tip_shop_card",
	},
	["honor"] = 
	{
		id = "honor",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "设施每分钟产门票",
		editor_comment3 = "honor_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "",
		name = "",
		tips = "",
	},
	["exp_time"] = 
	{
		id = "exp_time",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "设施产exp所需的时间",
		editor_comment3 = "exp_time_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_exptime",
		name = "",
		tips = "tip_exp_time",
	},
	["exp"] = 
	{
		id = "exp",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "设施产exp",
		editor_comment3 = "exp_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_expget",
		name = "",
		tips = "tip_exp",
	},
	["value_up"] = 
	{
		id = "value_up",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "价值提升",
		editor_comment3 = "value_up_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_valueup",
		name = "",
		tips = "",
	},
	["de_pla"] = 
	{
		id = "de_pla",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "装备制作塑料材料减少",
		editor_comment3 = "de_pla_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_plastic01",
		name = "",
		tips = "",
	},
	["de_wood"] = 
	{
		id = "de_wood",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "装备制作木头材料减少",
		editor_comment3 = "de_wood_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_wood",
		name = "",
		tips = "",
	},
	["de_fab"] = 
	{
		id = "de_fab",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "装备制作布料材料减少",
		editor_comment3 = "de_fab_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_cloth",
		name = "",
		tips = "",
	},
	["de_lea"] = 
	{
		id = "de_lea",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "装备制作皮革材料减少",
		editor_comment3 = "de_lea_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_leather",
		name = "",
		tips = "",
	},
	["de_iron"] = 
	{
		id = "de_iron",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "装备制作钢铁材料减少",
		editor_comment3 = "de_iron_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_iron",
		name = "",
		tips = "",
	},
	["de_sil"] = 
	{
		id = "de_sil",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "装备制作硅胶材料减少",
		editor_comment3 = "de_sil_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_silica",
		name = "",
		tips = "",
	},
	["de_nylon"] = 
	{
		id = "de_nylon",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "装备制作尼龙材料减少",
		editor_comment3 = "de_nylon_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_nylon",
		name = "",
		tips = "",
	},
	["de_res"] = 
	{
		id = "de_res",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "装备制作树脂材料减少",
		editor_comment3 = "de_res_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_resin",
		name = "",
		tips = "",
	},
	["de_alloy"] = 
	{
		id = "de_alloy",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "装备制作合金材料减少",
		editor_comment3 = "de_alloy_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_alloy",
		name = "",
		tips = "",
	},
	["de_carb"] = 
	{
		id = "de_carb",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "装备制作碳纤维材料减少",
		editor_comment3 = "de_carb_num_sub",
		unit = "function_unit_none",
		sign = "minus",
		icon = "Function/function_carbon",
		name = "",
		tips = "",
	},
	["new_drawing"] = 
	{
		id = "new_drawing",
		type = "",
		editor_comment1 = "装备里程碑",
		editor_comment2 = "新图纸",
		editor_comment3 = "new_drawing_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_drawing",
		name = "",
		tips = "",
	},
	["reduce_time"] = 
	{
		id = "reduce_time",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "制作时间缩短(百分比）",
		editor_comment3 = "make_time_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Function/function_producetimedown",
		name = "",
		tips = "",
	},
	["high_rarity"] = 
	{
		id = "high_rarity",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "更高稀有度（百分比）",
		editor_comment3 = "high_rarity_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_valueup",
		name = "",
		tips = "",
	},
	["get_one"] = 
	{
		id = "get_one",
		type = "",
		editor_comment1 = "装备里程碑，装备升星",
		editor_comment2 = "增加多重制作几率（百分比）",
		editor_comment3 = "make_mult_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_multiply",
		name = "",
		tips = "",
	},
	["plastic"] = 
	{
		id = "plastic",
		type = "",
		editor_comment1 = "装备表",
		editor_comment2 = "装备制作材料塑料需求数量",
		editor_comment3 = "plastic_cost_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "Function/function_plastic01",
		name = "",
		tips = "",
	},
	["wood"] = 
	{
		id = "wood",
		type = "",
		editor_comment1 = "装备表",
		editor_comment2 = "装备制作材料木头需求数量",
		editor_comment3 = "wood_cost_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "Function/function_wood",
		name = "",
		tips = "",
	},
	["fabric"] = 
	{
		id = "fabric",
		type = "",
		editor_comment1 = "装备表",
		editor_comment2 = "装备制作材料布料需求数量",
		editor_comment3 = "fabric_cost_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "Function/function_cloth",
		name = "",
		tips = "",
	},
	["leather"] = 
	{
		id = "leather",
		type = "",
		editor_comment1 = "装备表",
		editor_comment2 = "装备制作材料皮革需求数量",
		editor_comment3 = "leather_cost_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "Function/function_leather",
		name = "",
		tips = "",
	},
	["steel"] = 
	{
		id = "steel",
		type = "",
		editor_comment1 = "装备表",
		editor_comment2 = "装备制作材料钢铁需求数量",
		editor_comment3 = "steel_cost_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "Function/function_iron",
		name = "",
		tips = "",
	},
	["silica"] = 
	{
		id = "silica",
		type = "",
		editor_comment1 = "装备表",
		editor_comment2 = "装备制作材料硅胶需求数量",
		editor_comment3 = "silica_cost_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "Function/function_silica",
		name = "",
		tips = "",
	},
	["nylon"] = 
	{
		id = "nylon",
		type = "",
		editor_comment1 = "装备表",
		editor_comment2 = "装备制作材料尼龙需求数量",
		editor_comment3 = "nylon_cost_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "Function/function_nylon",
		name = "",
		tips = "",
	},
	["resin"] = 
	{
		id = "resin",
		type = "",
		editor_comment1 = "装备表",
		editor_comment2 = "装备制作材料树脂需求数量",
		editor_comment3 = "resin_cost_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "Function/function_resin",
		name = "",
		tips = "",
	},
	["alloy"] = 
	{
		id = "alloy",
		type = "",
		editor_comment1 = "装备表",
		editor_comment2 = "装备制作材料合金需求数量",
		editor_comment3 = "alloy_cost_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "Function/function_alloy",
		name = "",
		tips = "",
	},
	["carbonfiber"] = 
	{
		id = "carbonfiber",
		type = "",
		editor_comment1 = "装备表",
		editor_comment2 = "装备制作材料碳纤维需求数量",
		editor_comment3 = "carbonfiber_cost_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "Function/function_carbon",
		name = "",
		tips = "",
	},
	["view_num"] = 
	{
		id = "view_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加观众人数上限",
		editor_comment3 = "view_max_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_audienceup",
		name = "",
		tips = "tip_audienceup",
	},
	["horn_num"] = 
	{
		id = "horn_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "门厅喇叭最大人数",
		editor_comment3 = "horn_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_callpeopleup",
		name = "",
		tips = "tip_callup",
	},
	["parking_num"] = 
	{
		id = "parking_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加停车场车位数",
		editor_comment3 = "parking_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_audienceup",
		name = "",
		tips = "",
	},
	["view_eff"] = 
	{
		id = "view_eff",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "每分钟进入观众",
		editor_comment3 = "view_re_num_add",
		unit = "function_unit_pm",
		sign = "plus",
		icon = "Function/function_audienceup",
		name = "",
		tips = "tip_vie_eff",
	},
	["noads"] = 
	{
		id = "noads",
		type = "",
		editor_comment1 = "SPFunction",
		editor_comment2 = "去广告",
		editor_comment3 = "noads",
		unit = "function_unit_none",
		sign = "none",
		icon = "",
		name = "",
		tips = "",
	},
	["investor"] = 
	{
		id = "investor",
		type = "",
		editor_comment1 = "SPFunction",
		editor_comment2 = "解锁劳斯莱斯老板和老板房",
		editor_comment3 = "investor",
		unit = "function_unit_none",
		sign = "none",
		icon = "",
		name = "",
		tips = "",
	},
	["autocollection"] = 
	{
		id = "autocollection",
		type = "",
		editor_comment1 = "SPFunction",
		editor_comment2 = "解锁自动捡钱机器人",
		editor_comment3 = "autocollection",
		unit = "function_unit_none",
		sign = "none",
		icon = "",
		name = "",
		tips = "",
	},
	["autoclean"] = 
	{
		id = "autoclean",
		type = "",
		editor_comment1 = "SPFunction",
		editor_comment2 = "解锁扫地机器人",
		editor_comment3 = "autoclean",
		unit = "function_unit_none",
		sign = "none",
		icon = "",
		name = "",
		tips = "",
	},
	["autoexpel"] = 
	{
		id = "autoexpel",
		type = "",
		editor_comment1 = "SPFunction",
		editor_comment2 = "解锁警犬",
		editor_comment3 = "autoexpel",
		unit = "function_unit_none",
		sign = "none",
		icon = "",
		name = "",
		tips = "",
	},
	["tour_guide_num"] = 
	{
		id = "tour_guide_num",
		type = "",
		editor_comment1 = "SPFunction",
		editor_comment2 = "导游，提高竞技场观众恢复速度（百分比)",
		editor_comment3 = "tour_guide_num_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "",
		name = "",
		tips = "",
	},
	["bunny_girl"] = 
	{
		id = "bunny_girl",
		type = "",
		editor_comment1 = "SPFunction",
		editor_comment2 = "兔女郎，自动发传单",
		editor_comment3 = "bunny_girl",
		unit = "function_unit_none",
		sign = "none",
		icon = "",
		name = "",
		tips = "",
	},
	["AI"] = 
	{
		id = "AI",
		type = "",
		editor_comment1 = "SPFunction",
		editor_comment2 = "阿尔法go，自动点击激励气泡",
		editor_comment3 = "AI",
		unit = "function_unit_none",
		sign = "none",
		icon = "",
		name = "",
		tips = "",
	},
	["onhook"] = 
	{
		id = "onhook",
		type = "",
		editor_comment1 = "cardbuild",
		editor_comment2 = "增加挂机收益最大时间上限（小时）",
		editor_comment3 = "onhook_num_add",
		unit = "function_unit_h",
		sign = "plus",
		icon = "",
		name = "",
		tips = "",
	},
	["rate"] = 
	{
		id = "rate",
		type = "",
		editor_comment1 = "cardbuild",
		editor_comment2 = "减少所有装备制作时间（百分比）",
		editor_comment3 = "equip_time_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "",
		name = "",
		tips = "",
	},
	["fattyup"] = 
	{
		id = "fattyup",
		type = "",
		editor_comment1 = "cardbuild",
		editor_comment2 = "提高胖游客出现的概率（百分比）",
		editor_comment3 = "fattyup_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "",
		name = "",
		tips = "",
	},
	["leaflet_scope"] = 
	{
		id = "leaflet_scope",
		type = "",
		editor_comment1 = "cardbuild",
		editor_comment2 = "提高喇叭生效范围（百分比）",
		editor_comment3 = "leaflet_scope_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "",
		name = "",
		tips = "",
	},
	["news_re"] = 
	{
		id = "news_re",
		type = "",
		editor_comment1 = "cardbuild",
		editor_comment2 = "提高报纸恢复速度（百分比）",
		editor_comment3 = "news_re_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "",
		name = "",
		tips = "",
	},
	["cusup_bus"] = 
	{
		id = "cusup_bus",
		type = "",
		editor_comment1 = "cardbuild",
		editor_comment2 = "每分钟从镜头外生成一个公交车，来到公交站停下，并从车门处生成N个一定进入俱乐部的游客，这些游客部分进入装备商店，部分进入主大厅",
		editor_comment3 = "cusup_bus_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "",
		name = "",
		tips = "",
	},
	["cusup_tram"] = 
	{
		id = "cusup_tram",
		type = "",
		editor_comment1 = "cardbuild",
		editor_comment2 = "每分钟从镜头外生成一个电车，来到电车站停下，并从车门处生成N个一定进入俱乐部的游客，这些游客部分进入装备商店，部分进入主大厅",
		editor_comment3 = "cusup_tram_num",
		unit = "function_unit_none",
		sign = "none",
		icon = "",
		name = "",
		tips = "",
	},
	["bat_earnings"] = 
	{
		id = "bat_earnings",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加击球房所有产钱设备收益，包括课程收益、设备收益（百分比）",
		editor_comment3 = "bat_earnings_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_add",
	},
	["pit_earnings"] = 
	{
		id = "pit_earnings",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加投球房所有产钱设备收益，包括课程收益、设备收益（百分比）",
		editor_comment3 = "pit_earnings_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_add",
	},
	["run_earnings"] = 
	{
		id = "run_earnings",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加跑步房所有产钱设备收益，包括课程收益、设备收益（百分比）",
		editor_comment3 = "run_earnings_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_add",
	},
	["cat_earnings"] = 
	{
		id = "cat_earnings",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加接球房所有产钱设备收益，包括课程收益、设备收益（百分比）",
		editor_comment3 = "cat_earnings_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_add",
	},
	["box_earnings"] = 
	{
		id = "box_earnings",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加敏捷房所有产钱设备收益，包括课程收益、设备收益（百分比）",
		editor_comment3 = "box_earnings_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_add",
	},
	["sho_earnings"] = 
	{
		id = "sho_earnings",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加力量房所有产钱设备收益，包括课程收益、设备收益（百分比）",
		editor_comment3 = "sho_earnings_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_add",
	},
	["bat_timecons"] = 
	{
		id = "bat_timecons",
		type = "star_timedown",
		editor_comment1 = "roomPos",
		editor_comment2 = "减少击球房所有产钱设备使用时间（百分比）",
		editor_comment3 = "bat_timecons_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Currency/currency_usagetime",
		name = "",
		tips = "tipRoomvalue_disadd",
	},
	["pit_timecons"] = 
	{
		id = "pit_timecons",
		type = "star_timedown",
		editor_comment1 = "roomPos",
		editor_comment2 = "减少投球房所有产钱设备使用时间（百分比）",
		editor_comment3 = "pit_timecons_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Currency/currency_usagetime",
		name = "",
		tips = "tipRoomvalue_disadd",
	},
	["run_timecons"] = 
	{
		id = "run_timecons",
		type = "star_timedown",
		editor_comment1 = "roomPos",
		editor_comment2 = "减少跑步房所有产钱设备使用时间（百分比）",
		editor_comment3 = "run_timecons_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Currency/currency_usagetime",
		name = "",
		tips = "tipRoomvalue_disadd",
	},
	["cat_timecons"] = 
	{
		id = "cat_timecons",
		type = "star_timedown",
		editor_comment1 = "roomPos",
		editor_comment2 = "减少接球房所有产钱设备使用时间（百分比）",
		editor_comment3 = "cat_timecons_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Currency/currency_usagetime",
		name = "",
		tips = "tipRoomvalue_disadd",
	},
	["box_timecons"] = 
	{
		id = "box_timecons",
		type = "star_timedown",
		editor_comment1 = "roomPos",
		editor_comment2 = "减少敏捷房所有产钱设备使用时间（百分比）",
		editor_comment3 = "box_timecons_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Currency/currency_usagetime",
		name = "",
		tips = "tipRoomvalue_disadd",
	},
	["sho_timecons"] = 
	{
		id = "sho_timecons",
		type = "star_timedown",
		editor_comment1 = "roomPos",
		editor_comment2 = "减少力量房所有产钱设备使用时间（百分比）",
		editor_comment3 = "sho_timecons_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Currency/currency_usagetime",
		name = "",
		tips = "tipRoomvalue_disadd",
	},
	["cafe_earnings"] = 
	{
		id = "cafe_earnings",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加茶水间游客使用设备收益（百分比）",
		editor_comment3 = "cafe_earnings_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_add",
	},
	["cafe_timecons"] = 
	{
		id = "cafe_timecons",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "减少茶水间游客使用设备时间（百分比）",
		editor_comment3 = "cafe_timecons_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Currency/currency_usagetime",
		name = "",
		tips = "tipRoomvalue_disadd",
	},
	["bath_earnings_A"] = 
	{
		id = "bath_earnings_A",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加浴室A游客使用设备收益（百分比）",
		editor_comment3 = "bath_earningsA_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_add",
	},
	["bath_timecons_A"] = 
	{
		id = "bath_timecons_A",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "减少浴室A游客使用设备时间（百分比）",
		editor_comment3 = "bath_timeconsA_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Currency/currency_usagetime",
		name = "",
		tips = "tipRoomvalue_disadd",
	},
	["bath_earnings_B"] = 
	{
		id = "bath_earnings_B",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加浴室B游客使用设备收益（百分比）",
		editor_comment3 = "bath_earningsB_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_add",
	},
	["bath_timecons_B"] = 
	{
		id = "bath_timecons_B",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "减少浴室B游客使用设备时间（百分比）",
		editor_comment3 = "bath_timeconsB_pp_sub",
		unit = "function_unit_pp",
		sign = "minus",
		icon = "Currency/currency_usagetime",
		name = "",
		tips = "tipRoomvalue_disadd",
	},
	["Investor_addition"] = 
	{
		id = "Investor_addition",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加兰博基尼老板奖励数量（百分比）",
		editor_comment3 = "investor_addition_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_addboss",
	},
	["Boss_addition"] = 
	{
		id = "Boss_addition",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加劳斯莱斯老板增加奖励（百分比）",
		editor_comment3 = "boss_addition_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_addboss",
	},
	["cleaner_add"] = 
	{
		id = "cleaner_add",
		type = "",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加一名保洁房保洁员",
		editor_comment3 = "cleaner_add_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["guard_add"] = 
	{
		id = "guard_add",
		type = "",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加一名保安房保安",
		editor_comment3 = "guard_add_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["waiter_add"] = 
	{
		id = "waiter_add",
		type = "",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加一名服务员房服务员",
		editor_comment3 = "waiter_add_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["cashier_add"] = 
	{
		id = "cashier_add",
		type = "",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加一名收银房收银员",
		editor_comment3 = "cashier_add_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["repairman_add"] = 
	{
		id = "repairman_add",
		type = "",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加一名修理工房修理工",
		editor_comment3 = "repairman_add_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["salesman_add"] = 
	{
		id = "salesman_add",
		type = "",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加一名销售房销售员",
		editor_comment3 = "salesman_add_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_getup",
		name = "",
		tips = "",
	},
	["cleanliness_pp"] = 
	{
		id = "cleanliness_pp",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加保洁房房间值--清洁度（百分比）",
		editor_comment3 = "cleanliness_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_RoomBuff0002",
		name = "",
		tips = "tipRoomvalue_cleanliness",
	},
	["safety_pp"] = 
	{
		id = "safety_pp",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加保安房房间值--安全度（百分比）",
		editor_comment3 = "safety_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_RoomBuff0001",
		name = "",
		tips = "tipRoomvalue_safety",
	},
	["SQI_pp"] = 
	{
		id = "SQI_pp",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加服务员房房间值--服务质量（百分比）",
		editor_comment3 = "SQI_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_RoomBuff0003",
		name = "",
		tips = "tipRoomvalue_SQI",
	},
	["consume_pp"] = 
	{
		id = "consume_pp",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加收银员房房间值--消费体验（百分比）",
		editor_comment3 = "consume_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_RoomBuff0005",
		name = "",
		tips = "tipRoomvalue_ardor",
	},
	["upkeep_pp"] = 
	{
		id = "upkeep_pp",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加修理工房房间值--保养度（百分比）",
		editor_comment3 = "upkeep_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_RoomBuff0004",
		name = "",
		tips = "tipRoomvalue_upkeep",
	},
	["ardor_pp"] = 
	{
		id = "ardor_pp",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加销售员房房间值--热情度（百分比）",
		editor_comment3 = "ardor_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_RoomBuff0006",
		name = "",
		tips = "tipRoomvalue_consume",
	},
	["onhook_add_pp_add"] = 
	{
		id = "onhook_add_pp_add",
		type = "star_offcash",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加离线挂机收益（百分比）",
		editor_comment3 = "onhook_add_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Currency/currency_cash",
		name = "",
		tips = "tipRoomvalue_get",
	},
	["bar_extraexp_pp_add"] = 
	{
		id = "bar_extraexp_pp_add",
		type = "star_exp",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加酒吧所有设施队员待机exp（百分比）",
		editor_comment3 = "bar_extraexp_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_expget",
		name = "",
		tips = "tipRoomvalue_hook",
	},
	["meet_extraexp_pp_add"] = 
	{
		id = "meet_extraexp_pp_add",
		type = "star_exp",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加会议室所有设施队员待机exp（百分比）",
		editor_comment3 = "meet_extraexp_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_expget",
		name = "",
		tips = "tipRoomvalue_hook",
	},
	["phy_extraexp_pp_add"] = 
	{
		id = "phy_extraexp_pp_add",
		type = "star_exp",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加理疗室所有设施队员待机exp（百分比）",
		editor_comment3 = "phy_extraexp_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_expget",
		name = "",
		tips = "tipRoomvalue_hook",
	},
	["spa_extraexp_pp_add"] = 
	{
		id = "spa_extraexp_pp_add",
		type = "star_exp",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加SPA所有设施队员待机exp（百分比）",
		editor_comment3 = "spa_extraexp_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_expget",
		name = "",
		tips = "tipRoomvalue_hook",
	},
	["tra_extraexp_pp_add"] = 
	{
		id = "tra_extraexp_pp_add",
		type = "star_exp",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加训练室所有设施队员待机exp（百分比）",
		editor_comment3 = "tra_extraexp_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_expget",
		name = "",
		tips = "tipRoomvalue_hook",
	},
	["fit_extraexp_pp_add"] = 
	{
		id = "fit_extraexp_pp_add",
		type = "star_exp",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加健身室所有设施队员待机exp（百分比）",
		editor_comment3 = "fit_extraexp_pp_add",
		unit = "function_unit_pp",
		sign = "plus",
		icon = "Function/function_expget",
		name = "",
		tips = "tipRoomvalue_hook",
	},
	["extraview_re_pp_add"] = 
	{
		id = "extraview_re_pp_add",
		type = "star_add",
		editor_comment1 = "roomPos",
		editor_comment2 = "增加每分钟进入观众（百分比）",
		editor_comment3 = "extraview_re_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_tourist",
		name = "",
		tips = "tipRoomvalue_people",
	},
	["cleanliness_num"] = 
	{
		id = "cleanliness_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加保洁房房间值--清洁度",
		editor_comment3 = "cleanliness_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_RoomBuff0002",
		name = "",
		tips = "Roomvalue_name_cleanliness",
	},
	["safety_num"] = 
	{
		id = "safety_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加保安房房间值--安全度",
		editor_comment3 = "safety_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_RoomBuff0001",
		name = "",
		tips = "Roomvalue_name_safety",
	},
	["SQI_num"] = 
	{
		id = "SQI_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加服务员房房间值--服务质量",
		editor_comment3 = "SQI_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_RoomBuff0003",
		name = "",
		tips = "Roomvalue_name_SQI",
	},
	["consume_num"] = 
	{
		id = "consume_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加收银员房房间值--消费体验",
		editor_comment3 = "consume_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_RoomBuff0005",
		name = "",
		tips = "Roomvalue_name_ardor",
	},
	["upkeep_num"] = 
	{
		id = "upkeep_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加修理工房房间值--保养度",
		editor_comment3 = "upkeep_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_RoomBuff0004",
		name = "",
		tips = "Roomvalue_name_upkeep",
	},
	["ardor_num"] = 
	{
		id = "ardor_num",
		type = "",
		editor_comment1 = "facility",
		editor_comment2 = "增加销售员房房间值--热情度",
		editor_comment3 = "ardor_num_add",
		unit = "function_unit_none",
		sign = "plus",
		icon = "Function/function_RoomBuff0006",
		name = "",
		tips = "Roomvalue_name_consume",
	},
	["waiter"] = 
	{
		id = "waiter",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "服务员",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_waiter",
		name = "fun_name_waiter",
		tips = "fun_des_waiter",
	},
	["manager"] = 
	{
		id = "manager",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "经理",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_manager",
		name = "fun_name_manager",
		tips = "fun_des_coach",
	},
	["coach"] = 
	{
		id = "coach",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "教练",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_CourseCoach",
		name = "fun_name_coach",
		tips = "fun_des_guard",
	},
	["guard"] = 
	{
		id = "guard",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "保安",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_securityStaff",
		name = "fun_name_guard",
		tips = "fun_des_cleaner",
	},
	["repairman"] = 
	{
		id = "repairman",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "修理工",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_repairman",
		name = "fun_name_repairman",
		tips = "fun_des_cashier",
	},
	["cleaner"] = 
	{
		id = "cleaner",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "清洁工",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_cleaner",
		name = "fun_name_cleaner",
		tips = "fun_des_cheerleader",
	},
	["cashier"] = 
	{
		id = "cashier",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "收银员",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_cashier",
		name = "fun_name_cashier",
		tips = "fun_des_manager",
	},
	["cheerleader"] = 
	{
		id = "cheerleader",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "啦啦队",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_Cheerleading",
		name = "fun_name_cheerleader",
		tips = "fun_des_repairman",
	},
	["salesman"] = 
	{
		id = "salesman",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "销售员",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_sale",
		name = "fun_name_salesman",
		tips = "fun_des_salesman",
	},
	["admin"] = 
	{
		id = "admin",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "管理员",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_administrators",
		name = "fun_name_admin",
		tips = "fun_des_admin",
	},
	["secretary"] = 
	{
		id = "secretary",
		type = "",
		editor_comment1 = "employee",
		editor_comment2 = "秘书",
		editor_comment3 = "",
		unit = "",
		sign = "none",
		icon = "Build/att_secretary",
		name = "fun_name_secretary",
		tips = "fun_des_secretary",
	},
}