LuaConfig["GiftPackConfig"] = 
{
	[22001] = 
	{
		id = 22001,
		name = "每日礼包",
		title = "title_yellow",
		mode = "daily",
		type = 3,
		desc = "这是一个每日礼包",
		buymode = "ADS",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="always",
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Currency",
			[2]="leaflet2",
			[3]=5,
		},
		},
		iterate = {
			[1]=1,
			[2]=1,
			[3]=1,
			[4]=1,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 1,
		originalprice = 30,
		discount = "500%",
		order = 1,
	},
	[22002] = 
	{
		id = 22002,
		name = "每日礼包",
		title = "title_green",
		mode = "daily",
		type = 3,
		desc = "这又是个每日礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="always",
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Currency",
			[2]="leaflet2",
			[3]=10,
		},
			[2]={
			[1]="Currency",
			[2]="leaflet3",
			[3]=2,
		},
		},
		iterate = {
			[1]=1,
			[2]=1,
			[3]=2,
			[4]=3,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 1,
		originalprice = 30,
		discount = "500%",
		order = 2,
	},
	[22003] = 
	{
		id = 22003,
		name = "每日礼包",
		title = "title_purple",
		mode = "daily",
		type = 3,
		desc = "这是另一个每日礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="always",
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Currency",
			[2]="leaflet2",
			[3]=15,
		},
			[2]={
			[1]="Currency",
			[2]="leaflet3",
			[3]=5,
		},
		},
		iterate = {
			[1]=1,
			[2]=1,
			[3]=2,
			[4]=3,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 5,
		originalprice = 168,
		discount = "560%",
		order = 3,
	},
	[22004] = 
	{
		id = 22004,
		name = "每日礼包",
		title = "title_green",
		mode = "daily",
		type = 3,
		desc = "这还是一个每日礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="user_layering",
			[2]=2,
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Item",
			[2]=2001,
			[3]=10,
		},
			[2]={
			[1]="Item",
			[2]=2002,
			[3]=5,
		},
			[3]={
			[1]="Item",
			[2]=2003,
			[3]=1,
		},
		},
		iterate = {
			[1]=0,
			[2]=0,
			[3]=1,
			[4]=2,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 10,
		originalprice = 428,
		discount = "630%",
		order = 4,
	},
	[22005] = 
	{
		id = 22005,
		name = "每日礼包",
		title = "title_green",
		mode = "daily",
		type = 3,
		desc = "这就是一个每日礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="user_layering",
			[2]=2,
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Item",
			[2]=2001,
			[3]=15,
		},
			[2]={
			[1]="Item",
			[2]=2002,
			[3]=10,
		},
			[3]={
			[1]="Item",
			[2]=2003,
			[3]=5,
		},
		},
		iterate = {
			[1]=0,
			[2]=0,
			[3]=1,
			[4]=2,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 15,
		originalprice = 648,
		discount = "660%",
		order = 5,
	},
	[22006] = 
	{
		id = 22006,
		name = "每日礼包",
		title = "title_purple",
		mode = "daily",
		type = 3,
		desc = "这个礼包是个每日礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="user_layering",
			[2]=2,
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Item",
			[2]=2001,
			[3]=30,
		},
			[2]={
			[1]="Item",
			[2]=2002,
			[3]=20,
		},
			[3]={
			[1]="Item",
			[2]=2003,
			[3]=10,
		},
		},
		iterate = {
			[1]=0,
			[2]=0,
			[3]=1,
			[4]=2,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 20,
		originalprice = 898,
		discount = "700%",
		order = 6,
	},
	[23001] = 
	{
		id = 23001,
		name = "每周礼包",
		title = "title_blue",
		mode = "weekly",
		type = 3,
		desc = "这是一个每周礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="always",
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Item",
			[2]=2001,
			[3]=15,
		},
			[2]={
			[1]="Item",
			[2]=2002,
			[3]=10,
		},
			[3]={
			[1]="Item",
			[2]=2003,
			[3]=5,
		},
		},
		iterate = {
			[1]=0,
			[2]=1,
			[3]=2,
			[4]=3,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 5,
		originalprice = 198,
		discount = "660%",
		order = 7,
	},
	[23002] = 
	{
		id = 23002,
		name = "每周礼包",
		title = "title_blue",
		mode = "weekly",
		type = 3,
		desc = "这又是个每周礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="always",
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Item",
			[2]=2001,
			[3]=30,
		},
			[2]={
			[1]="Item",
			[2]=2002,
			[3]=20,
		},
			[3]={
			[1]="Item",
			[2]=2003,
			[3]=10,
		},
		},
		iterate = {
			[1]=0,
			[2]=1,
			[3]=2,
			[4]=3,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 10,
		originalprice = 448,
		discount = "660%",
		order = 8,
	},
	[23003] = 
	{
		id = 23003,
		name = "每周礼包",
		title = "title_red",
		mode = "weekly",
		type = 3,
		desc = "这是另一个每周礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="always",
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Item",
			[2]=2001,
			[3]=50,
		},
			[2]={
			[1]="Item",
			[2]=2002,
			[3]=30,
		},
			[3]={
			[1]="Item",
			[2]=2003,
			[3]=20,
		},
		},
		iterate = {
			[1]=0,
			[2]=1,
			[3]=2,
			[4]=3,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 15,
		originalprice = 698,
		discount = "712%",
		order = 9,
	},
	[23004] = 
	{
		id = 23004,
		name = "每周礼包",
		title = "title_blue",
		mode = "weekly",
		type = 3,
		desc = "这还是一个每周礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="user_layering",
			[2]=2,
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Item",
			[2]=2001,
			[3]=30,
		},
			[2]={
			[1]="Item",
			[2]=2002,
			[3]=20,
		},
			[3]={
			[1]="Item",
			[2]=2003,
			[3]=10,
		},
		},
		iterate = {
			[1]=0,
			[2]=0,
			[3]=1,
			[4]=2,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 20,
		originalprice = 998,
		discount = "780%",
		order = 10,
	},
	[23005] = 
	{
		id = 23005,
		name = "每周礼包",
		title = "title_blue",
		mode = "weekly",
		type = 3,
		desc = "这就是一个每周礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="user_layering",
			[2]=2,
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Item",
			[2]=2001,
			[3]=50,
		},
			[2]={
			[1]="Item",
			[2]=2002,
			[3]=30,
		},
			[3]={
			[1]="Item",
			[2]=2003,
			[3]=20,
		},
		},
		iterate = {
			[1]=0,
			[2]=0,
			[3]=1,
			[4]=2,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 50,
		originalprice = 2598,
		discount = "800%",
		order = 11,
	},
	[23006] = 
	{
		id = 23006,
		name = "每周礼包",
		title = "title_red",
		mode = "weekly",
		type = 3,
		desc = "这个礼包是个每周礼包",
		buymode = "DirectPay",
		timingmode = 1,
		buydisappear = false,
		unlock = {
			[1]={
			[1]="user_layering",
			[2]=2,
		},
		},
		correlation = false,
		popup = "none",
		repetition = "loop",
		resetcycle = -1,
		duration = -1,
		Interval = "0",
		endPrompt = false,
		showlocation = "shop",
		commodity = {
			[1]={
			[1]="Item",
			[2]=2001,
			[3]=100,
		},
			[2]={
			[1]="Item",
			[2]=2002,
			[3]=50,
		},
			[3]={
			[1]="Item",
			[2]=2003,
			[3]=25,
		},
		},
		iterate = {
			[1]=0,
			[2]=0,
			[3]=1,
			[4]=2,
		},
		banner = "",
		originalpicture = "",
		icon = "",
		price = 60,
		originalprice = 5898,
		discount = "910%",
		order = 12,
	},
}