LuaConfig["ShopModuleConfig"] = 
{
	[1001] = 
	{
		id = 1001,
		name = "月卡",
		icon = "",
		title = "",
		des_condition = "task;10030",
		page = "monthlycard",
		order = 1,
		content = nil,
		reset = "",
		duration = "-1",
	},
	[2001] = 
	{
		id = 2001,
		name = "成长基金",
		icon = "",
		title = "",
		des_condition = "always",
		page = "fund",
		order = 1,
		content = nil,
		reset = "",
		duration = "-1",
	},
	[3001] = 
	{
		id = 3001,
		name = "测试战令",
		icon = "",
		title = "",
		des_condition = "vpcard_count;999999999",
		page = "battle_pass",
		order = 1,
		content = nil,
		reset = "",
		duration = "-1",
	},
	[4001] = 
	{
		id = 4001,
		name = "每日礼包",
		icon = "Shop01/tag01gift",
		title = "Shop01/title_todaybuy",
		des_condition = "always",
		page = "gift_package",
		order = 1,
		content = {
			[1]=22001,
			[2]=22002,
			[3]=22003,
			[4]=22004,
			[5]=22005,
			[6]=22006,
		},
		reset = "daily",
		duration = "",
	},
	[4002] = 
	{
		id = 4002,
		name = "每周礼包",
		icon = "Shop01/tag01gift_01",
		title = "Shop01/title_onlyweek",
		des_condition = "user_layering;1",
		page = "gift_package",
		order = 2,
		content = {
			[1]=23001,
			[2]=23002,
			[3]=23003,
			[4]=23004,
			[5]=23005,
			[6]=23006,
		},
		reset = "weekly",
		duration = "",
	},
	[5001] = 
	{
		id = 5001,
		name = "广告经理",
		icon = "Shop01/tag02crown",
		title = "Shop01/title_BestSale",
		des_condition = "vpcard_count;65",
		page = "assistant",
		order = 4,
		content = {
			[1]=41001,
		},
		reset = "",
		duration = "",
	},
	[5002] = 
	{
		id = 5002,
		name = "管理人员",
		icon = "Shop01/tag02crown",
		title = "Shop01/title_BestSale",
		des_condition = "always",
		page = "assistant",
		order = 1,
		content = {
			[1]=44001,
		},
		reset = "",
		duration = "",
	},
	[5003] = 
	{
		id = 5003,
		name = "扫地机器人",
		icon = "Shop01/tag02crown",
		title = "Shop01/title_BestSale",
		des_condition = "always",
		page = "assistant",
		order = 2,
		content = {
			[1]=47001,
		},
		reset = "",
		duration = "",
	},
	[5004] = 
	{
		id = 5004,
		name = "柴犬",
		icon = "Shop01/tag02crown",
		title = "Shop01/title_BestSale",
		des_condition = "always",
		page = "assistant",
		order = 3,
		content = {
			[1]=45001,
		},
		reset = "",
		duration = "",
	},
	[5005] = 
	{
		id = 5005,
		name = "导游",
		icon = "Shop01/tag02crown",
		title = "Shop01/title_BestSale",
		des_condition = "pay_num;128",
		page = "assistant",
		order = 6,
		content = {
			[1]=43001,
		},
		reset = "",
		duration = "",
	},
	[5006] = 
	{
		id = 5006,
		name = "宣发经理-兔女郎",
		icon = "Shop01/tag02crown",
		title = "Shop01/title_BestSale",
		des_condition = "pay_num;128",
		page = "assistant",
		order = 5,
		content = {
			[1]=46001,
		},
		reset = "",
		duration = "",
	},
	[5007] = 
	{
		id = 5007,
		name = "工匠",
		icon = "Shop01/tag02crown",
		title = "Shop01/title_BestSale",
		des_condition = "pay_num;128/task;1053",
		page = "assistant",
		order = 7,
		content = {
			[1]=48001,
		},
		reset = "",
		duration = "",
	},
	[5008] = 
	{
		id = 5008,
		name = "金牌投资人",
		icon = "Shop01/tag02crown",
		title = "Shop01/title_BestSale",
		des_condition = "pay_num;128",
		page = "assistant",
		order = 8,
		content = {
			[1]=42001,
		},
		reset = "",
		duration = "",
	},
	[6001] = 
	{
		id = 6001,
		name = "卡牌商城",
		icon = "Shop01/tag03card",
		title = "Shop01/title_HotSale",
		des_condition = "always",
		page = "cardshop",
		order = 1,
		content = nil,
		reset = "daily",
		duration = "",
	},
	[7001] = 
	{
		id = 7001,
		name = "时间跳跃",
		icon = "Shop01/title_cash03",
		title = "Shop01/title_cash",
		des_condition = "always",
		page = "time_machine",
		order = 1,
		content = nil,
		reset = "",
		duration = "",
	},
	[8001] = 
	{
		id = 8001,
		name = "钻石商城",
		icon = "Shop01/tag05diamond",
		title = "Shop01/title_Diamonds",
		des_condition = "always",
		page = "diamond_shop",
		order = 1,
		content = nil,
		reset = "",
		duration = "",
	},
	[9001] = 
	{
		id = 9001,
		name = "测试战令",
		icon = "",
		title = "",
		des_condition = "vpcard_count;0",
		page = "battle_pass",
		order = 1,
		content = nil,
		reset = "",
		duration = "",
	},
	[10001] = 
	{
		id = 10001,
		name = "新手礼包",
		icon = "",
		title = "",
		des_condition = "task;10020",
		page = "flash_Sale",
		order = 1,
		content = nil,
		reset = "",
		duration = "28800",
	},
	[10002] = 
	{
		id = 10002,
		name = "联赛礼包",
		icon = "",
		title = "",
		des_condition = "task;10020",
		page = "flash_Sale",
		order = 2,
		content = nil,
		reset = "",
		duration = "28800",
	},
	[10003] = 
	{
		id = 10003,
		name = "超值礼包1",
		icon = "",
		title = "",
		des_condition = "task;10020",
		page = "flash_Sale",
		order = 3,
		content = nil,
		reset = "",
		duration = "28800",
	},
	[10004] = 
	{
		id = 10004,
		name = "超值礼包2",
		icon = "",
		title = "",
		des_condition = "task;10020",
		page = "flash_Sale",
		order = 4,
		content = nil,
		reset = "",
		duration = "28800",
	},
	[10005] = 
	{
		id = 10005,
		name = "赛季礼包",
		icon = "",
		title = "",
		des_condition = "task;10020",
		page = "flash_Sale",
		order = 5,
		content = nil,
		reset = "SeasonStar",
		duration = "28800",
	},
}