
do
local function New(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11)
	return {id=a0,cn=a1,en=a2,jp=a3,tw=a4,de=a5,ru=a6,fr=a7,it=a8,es=a9,pt=a10,kr=a11,}
end
local WordDailyTaskConfig = 
{
["dailytask_task"] = New("dailytask_task","每日任务","Daily Quest","デイリークエスト","每日任務","Tägliche Quest","Ежедневный квест","Quête quotidienne","Missione giornaliera","Búsqueda diaria","Daily Quest",""),
["dailytask_achievement"] = New("dailytask_achievement","成就","Achievement","目標","成就","Errungenschaft","Достижения","Réussite","Realizzazione","Logro","Realização",""),
["dailytask_special"] = New("dailytask_special","特殊","Special","スペシャル","特殊","Spezial","Специальный","Spécial","Speciale","Especial","Especial",""),
["dailytask_tips"] = New("dailytask_tips","每日刷新","Refresh daily","毎日リフレッシュ","每天刷新","Täglich auffrischen","Обновляйте ежедневно","Rafraîchir quotidiennement","Aggiornamenti quotidiani","Actualizar diariamente","Actualizar diariamente",""),
["dailytask_name_10000"] = New("dailytask_name_10000","总任务","Quest List","全クエスト","總任務","Quest-Liste","Список квестов","Liste des quêtes","Lista delle missioni","Lista de misiones","Lista de missões",""),
["dailytask_pointtip"] = New("dailytask_pointtip","完成每日任务获取活跃值，活跃值到达一定数量可领取奖励","Complete daily quests to gain Activity Points  Once your Activity Points reach a certain amount， you can claim rewards ","デイリークエストをクリアすることで活躍値を獲得し、貯めた活躍値でボーナスを獲得します","完成每日任務獲取活躍值，活躍值到達一定數量可領取獎勵","Erfülle tägliche Quests, um Aktivitätspunkte zu erhalten  Sobald deine Aktivitätspunkte eine bestimmte Menge erreichen, kannst du Belohnungen einfordern ","Выполняйте ежедневные задания, чтобы получить очки активности  Когда количество очков активности достигнет определенного уровня, вы сможете получить вознаграждение ","Accomplissez les quêtes quotidiennes pour gagner des points d\'activité  Lorsque vos points d\'activité atteignent un certain montant， vous pouvez réclamer des récompenses ","Completa le missioni giornaliere per guadagnare punti attività  Una volta che i tuoi punti attività raggiungono una certa quantità, puoi richiedere delle ricompense ","Completa las misiones diarias para ganar Puntos de Actividad  Una vez que tus Puntos de Actividad alcancen una cantidad determinada， podrás reclamar recompensas ","Completar as missões diárias para ganhar Pontos de Actividade  Assim que os seus Pontos de Actividade atinjam um certo amount，, poderá reclamar recompensas ",""),
["dailytask_facility_upgrade"] = New("dailytask_facility_upgrade","升级%s次设备 ","Upgrade facilities %s times ","設備を%s回lvアップ","升級%s次設備 ","Verbessere Einrichtungen %s mal ","Улучшайте объекты %s раз ","Améliorez les installations %s fois ","Potenzia le strutture %s volte ","Mejora las instalaciones %s veces ","Actualizar instalações %s vezes ",""),
["dailytask_lesson_upgrade"] = New("dailytask_lesson_upgrade","升级%s次课程 ","Upgrade courses %s times ","コースを%s回lvアップ","升級%s次課程 ","Verbessere Kurse %s Mal ","Улучшите курсы %s раз ","Améliorez les cours %s fois ","Migliora i corsi %s volte ","Mejora los campos %s veces ","Cursos de actualização %s vezes ",""),
["dailytask_defeat_villain"] = New("dailytask_defeat_villain","击退%s次捣蛋鬼","Chase off %s troublemakers ","悪役を%s回追い払う","擊退%s次搗蛋鬼","Verjage %s Störenfriede ","Прогоните %s нарушителей порядка ","Chassez %s des fauteurs de trouble ","Scaccia %s di piantagrane ","Ahuyenta a %s alborotadores ","Perseguir os %s arruaceiros ",""),
["dailytask_clear_rubbish"] = New("dailytask_clear_rubbish","清理%s个垃圾","Clean up trash %s times ","ゴミを%s個清掃","清理%s個垃圾","Säubere den Müll %s Mal ","Убирайте мусор %s раз ","Nettoyer les ordures %s fois ","Pulisci la spazzatura %s volte ","Limpia la basura %s veces ","Limpar o lixo %s vezes ",""),
["dailytask_use_full_speedUp"] = New("dailytask_use_full_speedUp","完整使用时间加速器%s次","Fully use the Time Lapser %s times ","時間加速装置を%s回完全に利用","完整使用時間加速器%s次","Nutze den Time Lapser %s Mal vollständig ","Полностью используйте лапсер времени %s раз ","Utiliser pleinement le Time Lapser %s fois ","Usa completamente il Time Lapser %s volte ","Utilizar completamente el Time Lapser %s veces ","Utilizar totalmente a %s vezes o Time Lapser ",""),
["dailytask_stimulate_tourist"] = New("dailytask_stimulate_tourist","帮助%s次出现疲惫状态的顾客","Help %s exhausted customers ","疲れた状態に陥ったお客を%s回ヘルプする","幫助%s次出現疲憊狀態的顧客","Hilf %s erschöpften Kunden ","Помогите %s измученным клиентам ","Aidez %s clients épuisés ","Aiuta %s clienti esausti ","Ayuda a %s clientes agotados ","Ajuda a %s clientes exaustos ",""),
["dailytask_passenger_multiple"] = New("dailytask_passenger_multiple","使用%s次人山人海","Use Flocking Customers %s times ","千客万来を%s回利用","使用%s次人山人海","Benutze %s mal Flocking Customers ","Используйте \"Слетающихся клиентов\" %s раз ","Utiliser Flocking Customers %s fois ","Usare Flocking Customers %s volte ","Utiliza el Flocking Customers %s veces ","Usar o Flocking Customers %s vezes ",""),
["dailytask_lamborghini"] = New("dailytask_lamborghini","获得%s次投资人的的赞助","Obtain %s investments from the Investor ","投資者からの投資を%s回受け取る","獲得%s次投資人的的讚助","Erhalte %s Investitionen vom Investor ","Получите %s инвестиций от Инвестора ","Obtenir %s investissements de l\'Investisseur ","Ottieni %s investimenti dall\'Investitore ","Obtén %s inversiones del Inversor ","Obter %s de investimentos do Investidor ",""),
["dailytask_hand_leaflets"] = New("dailytask_hand_leaflets","使用%s次喇叭宣传","Promote your club using loudspeakers %s times ","メガホンを%s回利用","使用%s次喇叭宣傳","Bewirb deinen Club über Lautsprecher %s Mal ","Рекламируйте свой клуб с помощью громкоговорителей %s раз ","Promouvoir votre club à l\'aide de haut-parleurs %s fois ","Promuovi il tuo club usando gli altoparlanti %s volte ","Promociona tu club mediante altavoces %s veces ","Promover o seu clube usando altifalantes %s vezes ",""),
["dailytask_hand_leaflets2"] = New("dailytask_hand_leaflets2","使用%s次报纸宣传","Promote your club via newspaper %s times ","新聞を%s回利用","使用%s次報紙宣傳","Bewirb deinen Club über die Zeitung %s mal ","Рекламируйте свой клуб через газету %s раз ","Promouvoir votre club via les journaux %s fois ","Promuovi il tuo club tramite i giornali %s volte ","Promociona tu club a través del periódico %s veces ","Promova o seu clube através de %s vezes do jornal ",""),
["dailytask_hand_leaflets3"] = New("dailytask_hand_leaflets3","使用%s次广播宣传","Promote your club via broadcast %s times ","ラジオを%s回利用","使用%s次廣播宣傳","Bewirb deinen Verein über den Rundfunk %s mal ","Продвигайте свой клуб по радио %s раз ","Promouvoir votre club par le biais de la radio %s fois ","Promuovi il tuo club tramite trasmissioni %s volte ","Promociona tu club a través de la radiodifusión %s veces ","Promova o seu clube através de %s vezes de emissão ",""),
["dailytask_win_league"] = New("dailytask_win_league","获得%s场联赛胜利","Win %s league games ","チャンプ戦で%s回勝利","獲得%s場聯賽勝利","Gewinne %s Ligaspiele ","Выиграть %s игр в лиге ","Gagner %s de matchs de ligue ","Vincere %s partite di campionato ","Ganar %s partidos de liga ","Ganhe %s jogos da liga ",""),
["dailytask_join_league"] = New("dailytask_join_league","进行%s次联赛","Play league game %s times ","チャンプ戦を%s回参加","進行%s次聯賽","Spiele %s mal ein Ligaspiel ","Сыграть %s игр в лиге ","Jouer des matchs de ligue %s fois ","Giocare le partite di campionato %s volte","Jugar un partido de liga %s veces","Jogue o jogo da liga %s vezes",""),
["dailytask_train_player"] = New("dailytask_train_player","训练%s次球员","Train your players %s times ","選手を%s回練習させる","訓練%s次球員","Trainiere deine Spieler %s mal ","Тренируйте своих игроков %s раз ","Entraîner vos joueurs %s fois ","Allenare i tuoi giocatori %s volte ","Entrenar a tus jugadores %s veces ","Treine os seus jogadores %s vezes ",""),
["dailytask_plarer_upgrade"] = New("dailytask_plarer_upgrade","升级%s次球员","Upgrade your players %s times ","選手を%s回lvアップ","升級%s次球員","Verbessere deine Spieler %s mal ","Улучшить своих игроков %s раз ","Améliorer vos joueurs %s fois ","Potenziare i tuoi giocatori %s volte ","Mejora a tus jugadores %s veces ","Actualize os seus jogadores em %s vezes ",""),
["dailytask_win_Champingship"] = New("dailytask_win_Champingship","获得%s场锦标赛胜利","Win tournaments %s times","トーナメントで%s回勝利","獲得%s場錦標賽勝利","Gewinne Turniere %s mal","Выиграть турниры %s раз","Gagner des tournois %s fois","Vinci tornei %s volte","Ganar torneos %s veces","Ganhar torneios %s vezes",""),
["dailytask_make_equip"] = New("dailytask_make_equip","制造%s件装备","Manufacture equipment %s times","装備を%s点製造","製造%s件裝備","Ausrüstung herstellen %s mal","Производить оборудование %s раз","Fabriquer des équipements %s fois","Produrre equipaggiamento %s volte","Fabricar equipo %s veces","Equipamento de fabrico %s vezes",""),
["dailytask_sell_equip"] = New("dailytask_sell_equip","出售%s件装备","Sell equipment %s times","装備を%s点売り出す","出售%s件裝備","Verkaufe Ausrüstung %s mal","Продать оборудование %s раз","Vendre des équipements %s fois","Vendere equipaggiamento %s volte","Vender equipo %s veces","Venda de equipamento %s vezes",""),
}
TableMerge(WordConfig,WordDailyTaskConfig)
end