
do
local function New(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11)
	return {id=a0,cn=a1,en=a2,jp=a3,tw=a4,de=a5,ru=a6,fr=a7,it=a8,es=a9,pt=a10,kr=a11,}
end
local WordStageNameConfig = 
{
["team_100001"] = New("team_100001","豆豆熊","Bean Bear","ビーンベア","豆豆熊","Bohnenbär","Бобовый медведь","Ourson","Orso di fagioli","Oso de la judía","Urso de feijão",""),
["team_100002"] = New("team_100002","双子","Gemini","ジェミニ","雙子","Zwillinge","Близнецы","Gemini","Gemini","Géminis","Gêmeos",""),
["team_100003"] = New("team_100003","耐克森英","Nike Senying","ナイキ セニング","耐克森英","Nike Senying","Найк Сенинг","Nike Senying","Nike Senying","Nike Senying","Nike Senying",""),
["team_110001"] = New("team_110001","斯克威弗","Skwifer","スキューバダイビング","斯克威弗","Skwifer","Сквифер","Skwifer","Skwifer","Skwifer","Skwifer",""),
["team_110002"] = New("team_110002","恐龙队","Dinosaur team","恐竜チーム","恐龍隊","Dinosaurier-Team","Команда динозавров","Équipe de dinosaures","Dinosauro squadra","Equipo de dinosaurios","Equipa de dinossauros",""),
["team_110003"] = New("team_110003","狮子","lion","ライオン","獅子","Löwe","лев","lion","leone","león","leão",""),
["team_110004"] = New("team_110004","爱人尼艾","Lover Nie","ラバーニー","愛人尼艾","Liebhaber Nie","Влюбленный Ни","Lover Nie","Amante Nie","Amante Nie","Lover Nie",""),
["team_120001"] = New("team_120001","社区棒球团","Community team","コミュニティチーム","社區棒球團","Gemeinschaftliches Team","Команда сообщества","Équipe communautaire","Squadra della comunità","Equipo de la comunidad","Equipa comunitária",""),
["team_120002"] = New("team_120002","绮丽虎","Beautiful tiger","美しい虎","綺麗虎","Schöner Tiger","Красивый тигр","Beau tigre","Bella tigre","Hermoso tigre","Lindo tigre",""),
["team_120003"] = New("team_120003","你好联盟","Hello Alliance","ハローアライアンス","你好聯盟","Hallo Allianz","Привет Альянс","Bonjour Alliance","Ciao Alleanza","Hola Alianza","Olá Aliança",""),
["team_120004"] = New("team_120004","麦精巨人","Maguin Giant","マグワンの巨人","麥精巨人","Maguinischer Riese","Гигант Магуин","Géant des Magouins","Gigante Maguino","Gigante de Maguin","Gigante de Maguin",""),
["team_120005"] = New("team_120005","燕子南飞","Swallows fly","ツバメが飛ぶ","燕子南飛","Schwalben fliegen","Ласточки летают","Vol d'hirondelles","Le rondini volano","Las golondrinas vuelan","As andorinhas voam",""),
["team_130001"] = New("team_130001","海港之星","Harbour Star","ハーバー・スター","海港之星","Hafen-Stern","Звезда гавани","Étoile de port","Stella del porto","Estrella del puerto","Estrela do porto",""),
["team_130002"] = New("team_130002","龙山","Longshan","龍山","龍山","Longshan","Лонгшан","Longshan","Longshan","Longshan","Longshan",""),
["team_130003"] = New("team_130003","南天珊瑚","Sky coral","スカイコーラル","南天珊瑚","Himmelskoralle","Небесный коралл","Corail du ciel","Corallo del cielo","Coral del cielo","Coral do céu",""),
["team_130004"] = New("team_130004","南北冰鱼","Ice fish","氷の魚","南北冰魚","Eisfisch","Ледяная рыба","Poisson de glace","Pesce di ghiaccio","Peces de hielo","Peixes de gelo",""),
["team_130005"] = New("team_130005","西北大洋联盟","Northwest Ocea","北西海域","西北大洋聯盟","Nordwest-Ozean","Северо-западный океан","Océanie du Nord-Ouest","Ocea nord-ovest","Océano del Noroeste","Oceano Noroeste",""),
["team_130006"] = New("team_130006","火腿鸡蛋","Ham eggs","ハムエッグ","火腿雞蛋","Schinkeneier","Яйца ветчины","Œufs de jambon","Uova di prosciutto","Huevos de jamón","Ovos de presunto",""),
["team_140001"] = New("team_140001","黑鹰天牛","Black Hawk","ブラックホーク","黑鷹天牛","Schwarzer Falke","Черный ястреб","Faucon noir","Falco nero","Halcón negro","Falcão Negro",""),
["team_140002"] = New("team_140002","陆地空神","Land god","陸の神様","陸地空神","Landgott","Бог земли","Dieu de la terre","Dio della terra","Dios de la tierra","Deus da terra",""),
["team_140003"] = New("team_140003","狮子怒吼","Lion roared","獅子の咆哮","獅子怒吼","Löwe gebrüllt","Львиный рык","Rugissement de lion","Leone ruggito","León que ruge","O leão rugiu",""),
["team_140004"] = New("team_140004","南溪牛","Stream cattle","渓流牛","南溪牛","Strom Rinder","Потоковый скот","Bétail de ruisseau","Bestiame del ruscello","Ganado del arroyo","Bovinos de córrego",""),
["team_140005"] = New("team_140005","摩羯飞鹰","Capricorn Eagle","カプリコーンイーグル","摩羯飛鷹","Steinbock-Adler","Козерог Орел","Aigle du Capricorne","Aquila del Capricorno","Águila de Capricornio","Águia de Capricórnio",""),
["team_140006"] = New("team_140006","逢山火","Mountain fire","山の火","逢山火","Bergfeuer","Горный огонь","Feu de la montagne","Fuoco di montagna","Fuego de la montaña","Incêndio na montanha",""),
["team_140007"] = New("team_140007","三土飞升","Three earths","三大地","三土飛升","Drei Erden","Три земли","Trois terres","Tre terre","Tres tierras","Três terras",""),
["team_150001"] = New("team_150001","蓝灵鸟","Blue bird","青い鳥","藍靈鳥","Blauer Vogel","Синяя птица","Oiseau bleu","Uccello blu","Pájaro azul","Pássaro azul",""),
["team_150002"] = New("team_150002","死亡圣光","Death light","デスライト","死亡聖光","Todeslicht","Свет смерти","Lumière de la mort","Luce della morte","Luz de la muerte","Luz da morte",""),
["team_150003"] = New("team_150003","天男降临","Heavenly man","天上人","天男降臨","Himmlischer Mann","Небесный человек","Homme céleste","Uomo celeste","Hombre celestial","Homem celestial",""),
["team_150004"] = New("team_150004","零零杀","Zero kill","ゼロ・キリング","零零殺","Null töten","Нулевая смерть","Zéro meurtre","Zero uccidere","Cero muerte","Morte zero",""),
["team_150005"] = New("team_150005","蛇形金属","Serpentine","サーペンタイン","蛇形金屬","Serpentine","Серпантин","Serpentin","Serpentina","Serpentina","Serpentina",""),
["team_150006"] = New("team_150006","青草地","Green grass","グリーングラス","青草地","Grünes Gras","Зеленая трава","Herbe verte","Erba verde","Hierba verde","Relva verde",""),
["team_150007"] = New("team_150007","皇家战地","Royal field","ロイヤルフィールド","皇家戰地","Königliches Feld","Королевское поле","Champ royal","Campo reale","Campo real","Campo real",""),
["team_150008"] = New("team_150008","太空人","Astronaut","宇宙飛行士","太空人","Astronaut","Космонавт","Astronaute","Astronauta","Astronauta","Astronauta",""),
["team_160001"] = New("team_160001","运动家","Sports people","スポーツ関係者","運動家","Sportliche Menschen","Спортивные люди","Sportifs","Gente di sport","Deportistas","Gente do desporto",""),
["team_160002"] = New("team_160002","天使小韩","Angel Han","エンジェル・ハン","天使小韓","Engel Han","Ангел Хань","Ange Han","Angelo Han","Ángel Han","Anjo Han",""),
["team_160003"] = New("team_160003","流浪天地","Wandering world","彷徨える世界","流浪天地","Wandernde Welt","Блуждающий мир","Le monde vagabond","Mondo errante","Mundo errante","Mundo errante",""),
["team_160004"] = New("team_160004","水手翻浪","The sailor","船乗り","水手翻浪","Der Seemann","Моряк","Le marin","Il marinaio","El marinero","O marinheiro",""),
["team_160005"] = New("team_160005","勇士弹跳","Warrior bounces","戦士が跳ねる","勇士彈跳","Krieger hüpft","Воин подпрыгивает","Le guerrier rebondit","Il guerriero rimbalza","El guerrero rebota","O guerreiro salta",""),
["team_160006"] = New("team_160006","城市翻涌","Tumbled city","転倒した街","城市翻湧","Gestrauchelte Stadt","Разбитый город","Ville dégringolée","Città burattata","La ciudad volcada","Cidade tombada",""),
["team_160007"] = New("team_160007","大都会","Metropolis","メトロポリス","大都會","Großstadt","Метрополис","Métropole","Metropoli","Metrópolis","Metropolis",""),
["team_160008"] = New("team_160008","盛世名城","Famous city","有名な都市","盛世名城","Berühmte Stadt","Знаменитый город","Ville célèbre","Città famosa","Ciudad famosa","Cidade famosa",""),
["team_160009"] = New("team_160009","海洋渔民","Marine fisher","マリンフィッシャー","海洋漁民","Meeresfischer","Морской рыбак","Pêcheur marin","Pescatore marino","Pescador marino","Pescador marinho",""),
["team_170001"] = New("team_170001","飘忽色彩","Drifting colors","漂う色","飄忽色彩","Treibende Farben","Дрейфующие цвета","Couleurs à la dérive","Colori alla deriva","Colores a la deriva","Cores à deriva",""),
["team_170002"] = New("team_170002","小熊沉重","Heavy bear","ヘビーベア","小熊沉重","Schwerer Bär","Тяжелый медведь","Ours lourd","Orso pesante","Oso pesado","Urso pesado",""),
["team_170003"] = New("team_170003","红衣主教","Cardinal","カーディナル","紅衣主教","Kardinal","Кардинал","Cardinal","Cardinale","Cardenal","Cardeal",""),
["team_170004"] = New("team_170004","海盗队","Pirates","海賊","海盜隊","Piraten","Пираты","Pirates","Pirati","Piratas","Piratas",""),
["team_170005"] = New("team_170005","啤酒花队","Hops","ホップ","啤酒花隊","Hopfen","Хмель","Houblon","Luppolo","Lúpulo","Lúpulo",""),
["team_170006"] = New("team_170006","机关飞翼","Organ wings","オルガン翼","機關飛翼","Orgel-Flügel","Органные крылья","Ailes d'orgue","Ali d'organo","Alas de órgano","Asas de órgão",""),
["team_170007"] = New("team_170007","矩形巨人","Rectangular giant","長方形の巨人","矩形巨人","Rechteckiger Riese","Прямоугольный гигант","Géant rectangulaire","Gigante rettangolare","Gigante rectangular","Gigante rectangular",""),
["team_170008"] = New("team_170008","教习矩阵","Learning matrix","ラーニングマトリックス","教習矩陣","Lernende Matrix","Учебная матрица","Matrice d'apprentissage","Matrice di apprendimento","Matriz de aprendizaje","Matriz de aprendizagem",""),
["team_170009"] = New("team_170009","堕落尼亚","Depraved Nia","堕落したニア","墮落尼亞","Verderbte Nia","Развращенная Ния","Nia dépravée","Nia depravata","Nia depravada","Nia depravada",""),
["team_170010"] = New("team_170010","响尾蛇","rattlesnake","ガラガラヘビ","響尾蛇","Klapperschlange","гремучая змея","Serpent à sonnette","serpente a sonagli","serpiente de cascabel","cascavel",""),
}
TableMerge(WordConfig,WordStageNameConfig)
end