
do
local function New(a0,a1,a2,a3,a4,a5,a6)
	return {id=a0,cn=a1,en=a2,tc=a3,jp=a4,kr=a5,flag=a6,}
end
local WordLessonUiConfig = 
{
["class_unlock"] = New("class_unlock","未解锁","Locked","未解鎖","ロック解除されていません","잠금이 해제되지 않았습니다","wordlessonconfig"),
["class_max"] = New("class_max","课程已升至满级！","Course level MAX！","課程已升至滿級！","コースはフルレベルに上昇しました!","코스가 전체 레벨로 올라갔습니다!","wordlessonconfig"),
["class_title_name_10001"] = New("class_title_name_10001","课程","Course","課程","コース","코스","wordlessonconfig"),
["class_title_name_10002"] = New("class_title_name_10002","投球课程","Pitching Course","投球課程","ピッチングコース","피칭 레슨","wordlessonconfig"),
["class_title_name_10003"] = New("class_title_name_10003","击球课程","Batting Course","擊球課程","バッティングコース","타격 레슨","wordlessonconfig"),
["class_title_name_10004"] = New("class_title_name_10004","接球课程","Catching Course","接球課程","キャッチボールコース","캐치볼 레슨","wordlessonconfig"),
["class_title_name_10005"] = New("class_title_name_10005","速度课程","Speed Course","速度課程","スピードコース","속도 코스","wordlessonconfig"),
["class_title_name_10006"] = New("class_title_name_10006","力量课程","Strength Course","力量課程","パワーコース","파워 코스","wordlessonconfig"),
["class_title_name_10007"] = New("class_title_name_10007","敏捷课程","Balancing Course","敏捷課程","アジャイルコース","애자일 코스","wordlessonconfig"),
["class_title_name_10008"] = New("class_title_name_10008","当前等级","Current Level","當前等級","現在のレベル","현재 등급입니다","wordlessonconfig"),
["class_title_name_10009"] = New("class_title_name_10009","课程时间","Course Time","課程時間","コース時間","코스 시간입니다","wordlessonconfig"),
["class_title_name_10010"] = New("class_title_name_10010","课程收益","Course Income","課程收益","コースの収益","코스 혜택","wordlessonconfig"),
["class_title_name_10011"] = New("class_title_name_10011","升级条件","Upgrade Condition","升級條件","アップグレード条件","업그레이드 조건","wordlessonconfig"),
["class_title_name_10012"] = New("class_title_name_10012","解锁条件","Unlock Condition","解鎖條件","条件のロックを解除します","잠금 해제 조건입니다","wordlessonconfig"),
["class_button_10001"] = New("class_button_10001","引进课程","Develop Course","引進課程","導入コース","커리큘럼을 도입하다","wordlessonconfig"),
["class_button_10002"] = New("class_button_10002","课程升级","Course Upgrade","課程升級","コースのアップグレード","코스 업그레이드","wordlessonconfig"),
["BM_Lesson01"] = New("BM_Lesson01","朴实球棒","Normal Bat","樸實球棒","プレーンバット","소박한 방망이","wordlessonconfig"),
["BM_Lesson02"] = New("BM_Lesson02","甜蜜糖果","Sweet Lollipop","甜蜜糖果","甘いキャンディ","달콤한 사탕","wordlessonconfig"),
["BM_Lesson03"] = New("BM_Lesson03","沉重咸鱼","Salted Fish","沉重鹹魚","重い塩漬けの魚","묵직한 소금에 절인 생선","wordlessonconfig"),
["BM_Lesson04"] = New("BM_Lesson04","冰冷水管","Icy Pipe","冰冷水管","氷と冷水管","차가운 수도관","wordlessonconfig"),
["BM_Lesson05"] = New("BM_Lesson05","摇滚吉他","Rock Guitar","搖滾吉他","ロックギター","록 기타","wordlessonconfig"),
["BM_Lesson06"] = New("BM_Lesson06","潇洒折扇","Chic Folding Fan","瀟灑摺扇","扇風機をこぼす","멋지고 접힌 부채","wordlessonconfig"),
["PM_Lesson01"] = New("PM_Lesson01","轻巧棒球","Smart Ball","輕巧棒球","軽量野球","가벼운 야구","wordlessonconfig"),
["PM_Lesson02"] = New("PM_Lesson02","可口西瓜","Yummy Watermelon","可口西瓜","おいしいスイカ","맛있는 수박","wordlessonconfig"),
["PM_Lesson03"] = New("PM_Lesson03","无限卷纸","Infinite Paper Roll","無限卷紙","無制限のロール紙","무한 롤 용지","wordlessonconfig"),
["PM_Lesson04"] = New("PM_Lesson04","魅力玩偶","Charm Doll","魅力玩偶","グラマー人形","글래머 인형","wordlessonconfig"),
["PM_Lesson05"] = New("PM_Lesson05","黏黏史莱姆","Sticky Slime","黏黏史萊姆","スティッキースライム","끈적끈적한 슬라임","wordlessonconfig"),
["PM_Lesson06"] = New("PM_Lesson06","剧毒河豚","Toxic Puffer","劇毒河豚","非常に有毒なフグ","독이 많은 복어","wordlessonconfig"),
["TM_Lesson01"] = New("TM_Lesson01","慢跑","Jogging","慢跑","ジョギング","조깅","wordlessonconfig"),
["TM_Lesson02"] = New("TM_Lesson02","障碍跑","Steeplechase","障礙跑","障害物が実行されます","장애물 달리기","wordlessonconfig"),
["TM_Lesson03"] = New("TM_Lesson03","坡度跑","Trail Running","坡度跑","スロープラン","경사로 달리다","wordlessonconfig"),
["TM_Lesson04"] = New("TM_Lesson04","冲刺","Sprint Dashing","衝刺","スプリント","질주","wordlessonconfig"),
["TM_Lesson05"] = New("TM_Lesson05","舞步跑","Dancing Step","舞步跑","ステップを踊る","춤을 추며 달리다","wordlessonconfig"),
["TM_Lesson06"] = New("TM_Lesson06","竞速跑","Racing","競速跑","レース","경주를 하다","wordlessonconfig"),
["CM_Lesson01"] = New("CM_Lesson01","平凡棒球","Common Ball","平凡棒球","平凡な野球","평범한 야구","wordlessonconfig"),
["CM_Lesson02"] = New("CM_Lesson02","水嫩苹果","Fresh Apple","水嫩蘋果","水柔らかいリンゴ","부드러운 사과","wordlessonconfig"),
["CM_Lesson03"] = New("CM_Lesson03","活泼幼鸟","Lively Chick","活潑幼鳥","活発な若い鳥","활기차고 어린 새","wordlessonconfig"),
["CM_Lesson04"] = New("CM_Lesson04","即爆炸弹","Explosive Bomb","即爆炸彈","爆発爆弾だ","즉, 폭발 폭탄입니다","wordlessonconfig"),
["CM_Lesson05"] = New("CM_Lesson05","龟派气功","Kamehameha","龜派氣功","亀派気功","거북파 기공","wordlessonconfig"),
["CM_Lesson06"] = New("CM_Lesson06","旋风火球","Hurricane Fireball","旋風火球","サイクロン火災ボール","회오리바람 불덩어리","wordlessonconfig"),
["FM_Lesson01"] = New("FM_Lesson01","垂直起飞","Vertical Takeoff","垂直起飛","垂直離陸","수직 이륙","wordlessonconfig"),
["FM_Lesson02"] = New("FM_Lesson02","悬空漂浮","Hoovering","懸空漂浮","浮いているぶら下がっている","공중에 떠 있다","wordlessonconfig"),
["FM_Lesson03"] = New("FM_Lesson03","随风飘荡","Wandering by the Wind","隨風飄蕩","風になびいた","바람에 펄럭인다","wordlessonconfig"),
["FM_Lesson04"] = New("FM_Lesson04","空中旋转","Air Spin","空中旋轉","空気中の回転","공중에서 회전합니다","wordlessonconfig"),
["FM_Lesson05"] = New("FM_Lesson05","空中漫步","Sky Walker","空中漫步","空中散歩","공중 산책","wordlessonconfig"),
["FM_Lesson06"] = New("FM_Lesson06","空中飞人","Superman","空中飛人","空飛ぶ男","공중에서 사람을 날다","wordlessonconfig"),
["SM_Lesson01"] = New("SM_Lesson01","蓄力回击","Charge and Hit","蓄力回擊","反撃する","힘을 모아 반격하다","wordlessonconfig"),
["SM_Lesson02"] = New("SM_Lesson02","转身回击","Turn Round Hit","轉身回擊","バックショットに背を向けた","돌아서서 반격하다","wordlessonconfig"),
["SM_Lesson03"] = New("SM_Lesson03","旋风回击","Swing Hit","旋風回擊","サイクロンが反撃した","회오리바람이 반격하다","wordlessonconfig"),
["SM_Lesson04"] = New("SM_Lesson04","雷霆回击","Thunder Hit","雷霆回擊","サンダーは反撃した","천둥이 반격했다","wordlessonconfig"),
["SM_Lesson05"] = New("SM_Lesson05","蛮力回击","Wild Hit","蠻力回擊","ブルートフォースバック","무력으로 반격하다","wordlessonconfig"),
["SM_Lesson06"] = New("SM_Lesson06","重力回击","Gravity Hit","重力回擊","重力の反撃","중력 리턴","wordlessonconfig"),
}
TableMerge(WordConfig,WordLessonUiConfig)
end