
do
local function New(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11)
	return {id=a0,cn=a1,en=a2,jp=a3,tw=a4,de=a5,ru=a6,fr=a7,it=a8,es=a9,pt=a10,kr=a11,}
end
local WordLessonUiConfig = 
{
["class_unlock"] = New("class_unlock","未解锁","Locked","未開放","未解鎖","Gesperrt","Заблокировано","Verrouillé","Bloccato","Bloqueado","Bloqueado",""),
["class_max"] = New("class_max","课程已升至满级！","Course level maxed!","コース最大lv","課程已升至滿級！","Kursstufe maximiert!","Уровень курса достиг максимума!","Niveau du cours atteint !","Livello del corso al massimo!","¡Nivel del curso al máximo!","Nível máximo do curso!",""),
["class_title_name_10001"] = New("class_title_name_10001","课程","Course","コース最大lv","課程","Kurs","Курс","Cours","Corso","Curso","Curso",""),
["class_title_name_10002"] = New("class_title_name_10002","投球课程","Pitching Course","ピッチング","投球課程","Pitching-Kurs","Курс по подаче","Cours Lancer","Corso di lancio","Curso de lanzamiento","Curso de Lancetamento",""),
["class_title_name_10003"] = New("class_title_name_10003","击球课程","Batting Course","バッティング","擊球課程","Schlagen-Kurs","Курс бэттинга","Cours de frappe","Corso di battuta","Curso de bateo","Curso de Batting",""),
["class_title_name_10004"] = New("class_title_name_10004","接球课程","Catching Course","キャッチング","接球課程","Fangen-Kurs","Курс по ловле мяча","Cours Catching","Corso di presa","Curso de captura","Curso de Captura",""),
["class_title_name_10005"] = New("class_title_name_10005","速度课程","Speed Course","スピード","速度課程","Schnelligkeits-Kurs","Курс скорости","Cours de vitesse","Corso di velocità","Curso de velocidad","Curso de Velocidade",""),
["class_title_name_10006"] = New("class_title_name_10006","力量课程","Strength Course","筋力","力量課程","Kraft-Kurs","Курс силы","Cours de force","Corso di forza","Curso de fuerza","Curso de Força",""),
["class_title_name_10007"] = New("class_title_name_10007","敏捷课程","Balancing Course","素早さ","敏捷課程","Balancier-Kurs","Курс балансировки","Cours d\'équilibrage","Corso di bilanciamento","Curso de equilibrio","Curso de Equilíbrio",""),
["class_title_name_10008"] = New("class_title_name_10008","当前等级","Current Level","現在のlv","當前等級","Aktuelles Niveau","Текущий уровень","Niveau actuel","Livello corrente","Nivel actual","Nível actual",""),
["class_title_name_10009"] = New("class_title_name_10009","课程时间","Course Time","所要時間","課程時間","Kurs Zeit","Время курса","Temps de parcours","Tempo del corso","Tiempo del curso","Tempo do curso",""),
["class_title_name_10010"] = New("class_title_name_10010","课程收益","Course Revenue","収益","課程收益","Kurs-Einnahmen","Доход от курса","Revenus du cours","Reddito del corso","Ingresos del curso","Receitas do Curso",""),
["class_title_name_10011"] = New("class_title_name_10011","升级条件","Upgrade Requirement","lvアップ条件","升級條件","Upgrade-Anforderung","Требование к обновлению","Besoin de mise à niveau","Requisito di aggiornamento","Requisito de actualización","Requisito de actualização",""),
["class_title_name_10012"] = New("class_title_name_10012","解锁条件","Unlocking Requirement","開放条件","解鎖條件","Bedarf freischalten","Требование разблокировки","Besoin de déblocage","Sbloccare il requisito","Requisito de desbloqueo","Requisito de desbloqueio",""),
["class_button_10001"] = New("class_button_10001","引进课程","Develop Course","コース導入","引進課程","Kurs entwickeln","Разработка курса","Développer le cours","Sviluppare il corso","Desarrollar curso","Desenvolver o Curso",""),
["class_button_10002"] = New("class_button_10002","课程升级","Upgrade Course","コースlvアップ","課程升級","Kurs aufwerten","Обновление курса","Mise à niveau du cours","Aggiornare il corso","Actualizar curso","Curso de Actualização",""),
["BM_Lesson01"] = New("BM_Lesson01","朴实球棒","Baseball Basics","普通バッティング","樸實球棒","Baseball-Grundlagen","Основы бейсбола","Baseball Basics","Nozioni di base del baseball","Fundamentos del béisbol","Bases do basebol",""),
["BM_Lesson02"] = New("BM_Lesson02","甜蜜糖果","Sweet Lollipop","甘いロリポップ","甜蜜糖果","Süßer Lollipop","Сладкий леденец","Sweet Lollipop","Lecca lecca dolce","Piruleta dulce","Chupa-chupa doce",""),
["BM_Lesson03"] = New("BM_Lesson03","沉重咸鱼","Salted Fish","硬い干し魚","沉重鹹魚","Gesalzener Fisch","Соленая рыба","Poisson salé","Pesce salato","Pescado salado","Peixe salgado",""),
["BM_Lesson04"] = New("BM_Lesson04","冰冷水管","Icy Pipe","冷たいパイプ","冰冷水管","Eiskalte Pfeife","Ледяная труба","Pipe glacée","Tubo ghiacciato","Pipa helada","Tubo Gelo",""),
["BM_Lesson05"] = New("BM_Lesson05","摇滚吉他","Rock Guitar","ロックギター","搖滾吉他","Rock-Gitarre","Рок-гитара","Guitare Rock","Chitarra rock","Guitarra Rock","Guitarra de Rocha",""),
["BM_Lesson06"] = New("BM_Lesson06","潇洒折扇","Appealing Fan","素早い扇子","瀟灑折扇","Ansprechender Fan","Привлекательный веер","Fan séduisant","Ventaglio attraente","Abanico atractivo","Ventilador apelativo",""),
["PM_Lesson01"] = New("PM_Lesson01","轻巧棒球","Smart Ball","賢いボール","輕巧棒球","Schlauer Ball","Умный шарик","Boule intelligente","Palla intelligente","Bola inteligente","Bola inteligente",""),
["PM_Lesson02"] = New("PM_Lesson02","可口西瓜","Juicy Watermelon","美味しいスイカ","可口西瓜","Saftige Wassermelone","Сочный арбуз","Pastèque juteuse","Anguria succosa","Sandía jugosa","Melancia suculenta",""),
["PM_Lesson03"] = New("PM_Lesson03","无限卷纸","Infinite Toilet Paper","無限なトイレペーパー","無限捲紙","Unendliches Toilettenpapier","Бесконечная туалетная бумага","Papier hygiénique infini","Carta igienica infinita","Papel higiénico infinito","Papel Higiénico Infinito",""),
["PM_Lesson04"] = New("PM_Lesson04","魅力玩偶","Lovely Doll","魅了の人形","魅力玩偶","Hübsche Puppe","Милая кукла","Poupée adorable","Bambola adorabile","Muñeca encantadora","Boneca adorável",""),
["PM_Lesson05"] = New("PM_Lesson05","黏黏史莱姆","Sticky Slime","粘るスライム","黏黏史萊姆","Klebriger Schleim","Липкая слизь","Sticky Slime","Melma appiccicosa","Baba pegajosa","Lodo pegajoso",""),
["PM_Lesson06"] = New("PM_Lesson06","剧毒河豚","Toxic Puffer","猛毒のフグ","劇毒河豚","Giftiger Puffer","Токсичный пуховичок","Puffer toxique","Puffer tossico","Puffer tóxico","Toxic Puffer",""),
["TM_Lesson01"] = New("TM_Lesson01","慢跑","Jogging","ジョギング","慢跑","Joggen","Бег трусцой","Jogging","Jogging","Jogging","Jogging",""),
["TM_Lesson02"] = New("TM_Lesson02","障碍跑","Steeplechase","障害競走","障礙跑","Steeplechase","Steeplechase","Steeplechase","Steeplechase","Carrera de obstáculos","Steeplechase",""),
["TM_Lesson03"] = New("TM_Lesson03","坡度跑","Trail Running","坂走り","坡度跑","Trailrunning","Бег по тропе","Course sur piste","Corsa su pista","Carrera de fondo","Percurso de pista",""),
["TM_Lesson04"] = New("TM_Lesson04","冲刺","Sprinting","ダッシュ","衝刺","Sprinten","Спринтерский бег","Sprint","Sprint","Sprinting","Sprinting",""),
["TM_Lesson05"] = New("TM_Lesson05","舞步跑","Dancing Step","踊り走り","舞步跑","Tanzender Schritt","Танцевальный шаг","Pas de danse","Passo di danza","Paso de baile","Passo de Dança",""),
["TM_Lesson06"] = New("TM_Lesson06","竞速跑","Racing","スピードレース","競速跑","Rennen","Скачки","Course","Corsa","Carreras","Corrida",""),
["CM_Lesson01"] = New("CM_Lesson01","平凡棒球","Common Ball","普通ボール","平凡棒球","Gemeinsamer Ball","Общий мяч","Balle commune","Palla comune","Bola común","Bola comum",""),
["CM_Lesson02"] = New("CM_Lesson02","水嫩苹果","Fresh Apple","爽やかなリンゴ","水嫩蘋果","Frischer Apfel","Свежее яблоко","Pomme fraîche","Mela fresca","Manzana fresca","Maçã Fresca",""),
["CM_Lesson03"] = New("CM_Lesson03","活泼幼鸟","Vivacious Fledging","活気な小鳥","活潑幼鳥","Lebhaftes Fliegen","Жизнерадостный птенец","Vivacité de l\'envol","Vivace fuggitivo","Volantín Vivaz","Vivacious Fledging",""),
["CM_Lesson04"] = New("CM_Lesson04","即爆炸弹","Immediate Bomb","即時爆弾","即爆炸彈","Sofortige Bombe","Мгновенный взрыв","Bombe Immédiate","Bomba immediata","Bomba Inmediata","Bomba Imediata",""),
["CM_Lesson05"] = New("CM_Lesson05","龟派气功","Kamehameha","カメカメハ","龜派氣功","Kamehameha","Камехамеха","Kamehameha","Kamehameha","Kamehameha","Kamehameha",""),
["CM_Lesson06"] = New("CM_Lesson06","旋风火球","Hurricane Fireball","ファイアボール","旋風火球","Hurricane Feuerball","Ураганный огненный шар","Boule de feu Hurricane","Palla di fuoco uragano","Bola de Fuego Huracán","Furacão Bola de Fogo",""),
["FM_Lesson01"] = New("FM_Lesson01","垂直起飞","Vertical Takeoff","垂直着陸","垂直起飛","Senkrechtstart","Вертикальный взлет","Décollage vertical","Decollo verticale","Despegue vertical","Descolagem Vertical",""),
["FM_Lesson02"] = New("FM_Lesson02","悬空漂浮","Hovering","浮遊カーブ","懸空漂浮","Schwebend","Парящий","Vol stationnaire","Hovering","Sobrevolando","A pairar",""),
["FM_Lesson03"] = New("FM_Lesson03","随风飘荡","Aerial Drifting","ウインドワンダー","隨風飄蕩","Driften in der Luft","Дрейф в воздухе","Dérive aérienne","Deriva aerea","Deriva aérea","Derivação aérea",""),
["FM_Lesson04"] = New("FM_Lesson04","空中旋转","Aerial Spinning","ハイスピニング","空中旋轉","Drehen in der Luft","Вращение в воздухе","Spinning aérien","Rotazione aerea","Giro aéreo","Fiação Aérea",""),
["FM_Lesson05"] = New("FM_Lesson05","空中漫步","Aerial Waking","スカイウォーク","空中漫步","Aufwachen aus der Luft","Пробуждение самолета","Réveil aérien","Risveglio aereo","Despertar aéreo","Despertar Aéreo",""),
["FM_Lesson06"] = New("FM_Lesson06","空中飞人","Aerial Dashing","スーパーマン","空中飛人","Aerial Dashing","Воздушный рывок","Dashing aérien","Sciabordio aereo","Salto aéreo","Destruição Aérea",""),
["SM_Lesson01"] = New("SM_Lesson01","蓄力回击","Charged Strike","溜め打ち","蓄力回擊","Aufgeladener Schlag","Заряженный удар","Frappe chargée","Colpo caricato","Golpe cargado","Greve Carregada",""),
["SM_Lesson02"] = New("SM_Lesson02","转身回击","Spinning Strike","回し打ち","轉身回擊","Wirbelnder Schlag","Вращающийся удар","Spinning Strike","Colpo rotante","Golpe giratorio","Greve de fiação",""),
["SM_Lesson03"] = New("SM_Lesson03","旋风回击","Tempest Strike","旋風打ち","旋風回擊","Sturmangriff","Удар бури","Coup de tempête","Colpo della tempesta","Golpe de tempestad","Greve de Tempestade",""),
["SM_Lesson04"] = New("SM_Lesson04","雷霆回击","Thunder Strike","雷打ち","雷霆回擊","Donnerschlag","Удар грома","Coup de tonnerre","Colpo di tuono","Golpe de Trueno","Thunder Strike",""),
["SM_Lesson05"] = New("SM_Lesson05","蛮力回击","Brutal Strike","怪力打ち","蠻力回擊","Brutaler Schlag","Жестокий удар","Coup de poing brutal","Colpo brutale","Golpe Brutal","Greve brutal",""),
["SM_Lesson06"] = New("SM_Lesson06","重力回击","Gravity Strike","重力打ち","重力回擊","Schwerkraft-Schlag","Гравитационный удар","Coup de gravité","Colpo di gravità","Golpe de gravedad","Greve gravitacional",""),
}
TableMerge(WordConfig,WordLessonUiConfig)
end