
do
local function New(a0,a1,a2,a3,a4,a5)
	return {id=a0,cn=a1,en=a2,tc=a3,jp=a4,kr=a5,}
end
local WordShopConfig = 
{
["SPFunction_describe_41001"] = New("SPFunction_describe_41001","为你去除游戏中的广告，直接获取广告奖励。","Removes Ads in the game. You can acquire all the Ad bonuses without watching them.","为你去除游戏中的广告，直接获取广告奖励。","ゲーム中の広告を削除します。","게임 광고 제거"),
["SPFunction_describe_41002"] = New("SPFunction_describe_41002","去除游戏中的广告，直接获取广告奖励。","Removes Ads.Acquire all the Ad bonus without watching them.","去除游戏中的广告，直接获取广告奖励。","ゲーム中の広告を削除します。","게임 광고 제거"),
["SPFunction_describe_42001"] = New("SPFunction_describe_42001","钱老板会为你带来比特币投资。                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ","MR Bucker will invest you with Byte Coins.","解鎖金牌投資人","ロールス・ロイスのロック解除","로 슬 레 스 사장"),
["SPFunction_describe_43001"] = New("SPFunction_describe_43001","每分钟进入竞技场的观众人数增加%s。","The audience entering the stadium increases by %s every minute.","顧客使用課程時間減少%s","お客様のレッスン時間が減少しました。%s","고객 이용 시간 감소% s"),
["SPFunction_describe_44001"] = New("SPFunction_describe_44001","俱乐部持续运营时间上限增加%s小时。","The upper limit of the club's continuous operation time is increased by %s hours.","掛機收益時間上限增加%s小時","保留中の収益時間の上限は%s時間増加しました。","자동 사냥 수익 시간 상한 선 증가% s 시간"),
["SPFunction_describe_45001"] = New("SPFunction_describe_45001","辅助你消灭视线内的捣蛋鬼。","Helps you to drive out “Pests” in vision.","廣告翻倍倍數增加%s","広告倍数増加%s","광고 배율 증가% s"),
["SPFunction_describe_46001"] = New("SPFunction_describe_46001","自动使用喇叭宣传。","Use Loudspeakers to tout automatically.","自動獲客效率增加%s","自動顧客獲得効率の増加%s","자동 수령 효율 증가% s"),
["SPFunction_describe_47001"] = New("SPFunction_describe_47001","帮助你清除俱乐部的垃圾。","Cleans up the trash in your Club.","解鎖自動收集機器人","ロック解除自動収集ロボット","잠 금 해제 자동 수집 로봇"),
["SPFunction_describe_48001"] = New("SPFunction_describe_48001","装备制造时间减少%s。","Reduce equipment crafting time by %s.","裝備製造時間減少%s","装備製造時間減少%s","장비 제조 시간 감소% s"),
["SPFunction_describe_49001"] = New("SPFunction_describe_49001","喇叭上限提升至{0}，喇叭生效范围扩大{1}。","Maximum Loudspeakers increase to {0}. The effective range of loudspeaker increases by {1}.","喇叭上限提升至{0}，喇叭生效範圍擴大{1}。","ホーンの上限を{0}に引き上げ、ホーンの有効範囲を拡大{1}。","경적의 상한이 {0} 증가하고 경적의 적용 범위가 {1} 확대됩니다."),
["name_41001"] = New("name_41001","广告商","Agent Sly","廣告經理","広告マネージャー","광고 매니저"),
["name_42001"] = New("name_42001","钱老板","MR Bucker","金牌投資人","金メダルの投資者","금메달 투자 자"),
["name_43001"] = New("name_43001","资深导游","Senior Guide","職業教練","プロのコーチ","프로 코치"),
["name_44001"] = New("name_44001","总经理","Manager","總經理","社長","총지배인"),
["name_45001"] = New("name_45001","柴犬旺旺","Puppy Woof","財務經理","経理","재무 매니저"),
["name_46001"] = New("name_46001","兔女郎","Bunny Girl","兔女郎","うさぎの女","바니 걸"),
["name_47001"] = New("name_47001","扫地机器人","Robot Cleaner","自動收集機器人","自動収集ロボット","자동 수집 로봇"),
["name_48001"] = New("name_48001","科学怪人","Inventor","資深工匠","ベテランの職人","베테랑 장인"),
["name_49001"] = New("name_49001","萨克斯","Saxophone","薩克斯","サックス","색소폰"),
["dialogue_41001"] = New("dialogue_41001","广告影无踪，经营更轻松。","No Ads. More Fun.","廣告影無蹤，經營更輕鬆。","広告の影が消えて、経営がもっと楽です。","광고 가 자 취 를 감 추고 경영 이 수월 하 다."),
["dialogue_42001"] = New("dialogue_42001","能被我看上，说明你很优秀！接受我的投资吧！","Being scouted by ME means you are excellent. Ready to handle my investment!","shut up and take my money","お金は何ですか？お金には興味がありません。","돈 이 뭐 예요?나 는 돈 에 흥미 가 없다!"),
["dialogue_43001"] = New("dialogue_43001","游客们，跟我来，往这边走！","This way guys, follow me!","不是我跟你吹，當年要不是我膝蓋中了一箭，我就不會在這當教練了","私はあなたと吹いていません。膝の中で矢が当たったのではないと、ここでコーチをしませんでした。","내 가 너 와 부 는 것 이 아니 라, 그때 내 무릎 에 화살 을 맞지 않 았 더 라면, 나 는 여기 서 코치 가 되 지 않 았 을 것 이다."),
["dialogue_44001"] = New("dialogue_44001","非常高兴能为您工作，合作愉快！","It's a pleasure to work for you.","非常高興能為您工作，希望我們能夠彼此成就","お仕事ができてとても嬉しいです。ご協力をお楽しみください。","당신 을 위해 일 할 수 있어 서 매우 기 쁩 니 다. 합작 이 즐 겁 습 니 다!"),
["dialogue_45001"] = New("dialogue_45001","汪！汪汪汪....汪汪！！！","Woof! Woo-wof! Woof!!","專精偷稅漏稅、偷工減料、巧立名目克扣員工工資。","財務経理は手抜きを専門に行い、巧みに名目を立てて社員の給料をカットする。","재무 매니저 는 전문 적 으로 노동력 과 재 료 를 줄 이 고 교묘 하 게 명목 을 세 워 직원 들 의 임금 을 공제 하 는 것 을 알 아 보 았 다."),
["dialogue_46001"] = New("dialogue_46001","欢迎光临！消费满两千就送老板签名照一张哟！","Welcome! You have won the chance to get MR Bucker's photo by paying 2000 dollars!","大爺來玩啊！","いらっしゃいませ9999以上を消費したら社長にサインしてもらいますよ。","어서오세요.9999 가 되면 사장 님 사인 사진 한 장 드 리 겠 습 니 다!"),
["dialogue_47001"] = New("dialogue_47001","！检测%…到…&*垃圾！*&%￥@￥%……&*（）清除#￥%……&*）*&#","！Trash%…is…&*detected！*&%￥@￥%……&*（）Attack#￥%……&*）*&#","嗡嗡！嗡嗡嗡！","滴！前方に散らばった札があることを検出したら、すぐに収集に出発します。","방울!전방 에 흩 어 진 지폐 가 검출 되 었 으 니 즉시 수집 하 러 출발 하 세 요!!"),
["dialogue_48001"] = New("dialogue_48001","科技才是制造装备的终点！","Only technology is the terminal of equipment crafting!","別逼逼，要造啥，趕緊說！","私が作ったものはだめなものがない。","내 가 만 든 건 안 되 는 게 없어."),
["dialogue_49001"] = New("dialogue_49001","没有人能拒绝我的音乐！","My music is unrefusable!","沒有人能拒絕我的音樂！","誰も私の音楽を拒否することができます!","아무도 내 음악을 거부 할 수 없습니다!"),
["mode_name_privilege"] = New("mode_name_privilege","特权商店","Privilege Shop","特權商店","プリビレッジストア","권한 스토어"),
["tip_bossunlock"] = New("tip_bossunlock","需要解锁钱老板，是否前往商城获取？","Need to unlock MR Bucker, jump to shop and purchase?","需要解鎖錢老闆，是否前往商城獲取？","お金のロックを解除したいですが、商店街に行ってもらえますか？","자 물 쇠 를 풀 어야 합 니 다, 사장 님. 상점 에 가서 구 하 시 겠 습 니까?"),
["tip_limit"] = New("tip_limit","限量","Limited","限量","数量を限定する","한정 하 다"),
["tip_refresh"] = New("tip_refresh","刷新倒计时","Refresh after","刷新倒計時","カウントダウンを更新","리 셋 초읽기"),
["shop_name_4001"] = New("shop_name_4001","每日礼包","Daily Box","每日禮包","毎日の贈り物","일 일 선물"),
["shop_name_4002"] = New("shop_name_4002","每周礼包","Weekly Box","每週禮包","毎週の贈り物","매주 선물"),
["shop_name_6001"] = New("shop_name_6001","卡牌商城","Card Shop","卡牌商城","カードショップ","카드 상점"),
["shop_name_7001"] = New("shop_name_7001","钞票商城","Bill Shop","鈔票商城","紙幣モール","지폐 쇼핑몰"),
["shop_name_8001"] = New("shop_name_8001","钻石商城","Diamond Shop","鑽石商城","ダイヤモンド","다이아몬드 상점"),
["shop_name_10001"] = New("shop_name_10001","新手礼包","Rookie Box","新手禮包","新米のプレゼント","신 입 선물"),
["shop_name_10002"] = New("shop_name_10002","联赛礼包","League Box","聯賽禮包","リーグ戦のギフトバッグ","리그 선물"),
["shop_name_10003"] = New("shop_name_10003","超值礼包","Valuable Box","超值禮包","スーパーパッケージ1","특급 선물 1"),
["shop_name_10004"] = New("shop_name_10004","热销礼包","Hot Box","熱銷禮包","スーパーパッケージ2","특급 선물 2"),
["shop_name_10005"] = New("shop_name_10005","赛季礼包","Season Box","賽季禮包","シーズンパッケージ","시즌 선물"),
["shop_name_10006"] = New("shop_name_10006","首充礼包","Charging Box","首充禮包","最初のパック","첫 번째 충전 선물 팩"),
["tip_firstgift"] = New("tip_firstgift","充值任意金额赠送大礼包！","Charge any price to win a Box!","充值任意金額贈送大禮包！","任意の金額で大きなパッケージをプレゼント!","어떤 금액으로든 큰 선물 꾸러미를 선물하십시오!"),
["tip_charge"] = New("tip_charge","充值","Charge","充值","リチャージ","충전"),
["tip_success0"] = New("tip_success0","购买成功","Successful purchase","购买成功","購入の成功","성공적인 구매"),
}
TableMerge(WordConfig,WordShopConfig)
end