
do
local function New(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11)
	return {id=a0,cn=a1,en=a2,jp=a3,tw=a4,de=a5,ru=a6,fr=a7,it=a8,es=a9,pt=a10,kr=a11,}
end
local WordBigTaskConfig = 
{
["BigTask_title001"] = New("BigTask_title001","建造职业棒球场重返大联盟","Build a Baseball Stadium and return to the Major League.","プロ球場を建ててリーグに戻りましょう","建造職業棒球場重返大聯盟","Bauen Sie ein Baseballstadion und kehren Sie in die Major League zurück.","Постройте бейсбольный стадион и вернитесь в Высшую лигу.","Construisez un stade de baseball et retournez dans la Major League.","Costruisci uno stadio di baseball e torna nella Major League.","Construye un estadio de béisbol y vuelve a la Liga Mayor.","Construir um Estádio de Basebol e regressar à Liga Principal.",""),
["BigTask_title002"] = New("BigTask_title002","通关第1赛季资格赛","Clear the preliminaries in season 1.","シーズン1の予選試合を通ります","通關第1賽季資格賽","Schließe die Vorrunden in Saison 1 ab.","Пройдите предварительный отборочный этап в 1-м сезоне.","Terminez les préliminaires de la saison 1.","Cancella i preliminari della stagione 1.","Supera los preliminares de la temporada 1.","Limpar os preliminares na época 1.",""),
["BigTask_title003"] = New("BigTask_title003","9个球员达到15级","Upgrade 9 players to level 15.","9人の選手がlv15に到達","9個球員達到15級","Rüste 9 Spieler auf Stufe 15 auf.","Улучшите 9 игроков до 15 уровня.","Améliorez 9 joueurs jusqu\'au niveau 15.","Aggiorna 9 giocatori al livello 15.","Sube a 9 jugadores al nivel 15.","Aumentar 9 jogadores para o nível 15.",""),
["BigTask_title004"] = New("BigTask_title004","开启跑步房","Build a Speed Practice Room.","ランニングルームを開放します","開啟跑步房","Baue einen Trainingsraum für Geschwindigkeit.","Постройте комнату для тренировки скорости.","Construire une salle d\'entraînement de vitesse.","Costruisci una Sala prove di velocità.","Construye una sala de entrenamiento de velocidad.","Construir uma Sala de Treinos de Velocidade.",""),
["BigTask_title005"] = New("BigTask_title005","建造装备商店","Build a Gear Shop.","装備ショップを作ります","建造裝備商店","Baue einen Ausrüstungsladen.","Постройте магазин снаряжения.","Construire un magasin d\'équipement.","Costruisci un negozio di attrezzi.","Construye una tienda de equipamiento.","Construir uma Loja de Equipamento.",""),
["BigTask_title006"] = New("BigTask_title006","制作一件3阶装备","Craft a piece of rank-3 gear.","ランク3装備を1点製造","製作一件3階裝備","Stelle ein Stück Rang-3-Ausrüstung her.","Создайте снаряжение 3-го ранга.","Fabriquer une pièce d\'équipement de rang 3.","Crea un pezzo di equipaggiamento di livello 3.","Fabrica una pieza de equipo de rango 3.","Construir uma peça de equipamento de nível 3.",""),
["BigTask_title007"] = New("BigTask_title007","建造3阶竞技场","Build a rank-3 Baseball Stadium.","ランク3球場を建造","建造3階競技場","Baue ein Rang-3-Baseball-Stadion.","Постройте бейсбольный стадион 3-го ранга.","Construire un stade de baseball de rang 3.","Costruisci uno stadio di baseball di livello 3.","Construye un estadio de béisbol de rango 3.","Construir um estádio de basebol de nível 3.",""),
["BigTask_title008"] = New("BigTask_title008","9个球员达到35级","Upgrade 9 players to level 35.","9人の選手がlv35に到達","9個球員達到35級","Rüste 9 Spieler auf Stufe 35 auf.","Улучшите 9 игроков до 35 уровня.","Améliorer 9 joueurs au niveau 35.","Aggiorna 9 giocatori al livello 35.","Sube a 9 jugadores al nivel 35.","Aumentar 9 jogadores para o nível 35.",""),
["BigTask_title009"] = New("BigTask_title009","第1季世界大赛通关","Clear the World Championship in season 1.","シーズン1ワールド戦を通ります","第1季世界大賽通關","Schaffe die Weltmeisterschaft in Saison 1.","Пройдите чемпионат мира в 1-м сезоне.","Terminez le championnat du monde de la saison 1.","Cancella il Campionato del Mondo nella stagione 1.","Supera el Campeonato Mundial en la temporada 1.","Desmarcar o Campeonato do Mundo na época 1.",""),
["BigTask_title010"] = New("BigTask_title010","建造敏捷训练房","Build a Balance Practice Room.","俊敏練習ルームを建造","建造敏捷訓練房","Baue einen Balance-Übungsraum.","Постройте тренировочный зал для баланса.","Construire une salle d\'entraînement d\'équilibre.","Costruisci una Sala prove di equilibrio.","Construye una sala de entrenamiento de equilibrio.","Construir uma Sala de Prática de Equilíbrio.",""),
["BigTask_title011"] = New("BigTask_title011","第2季世界大赛通关","Clear the World Championship in season 2.","シーズン2ワールド戦を通ります","第2季世界大賽通關","Schaffe die Weltmeisterschaft in Saison 2.","Очистите чемпионат мира во втором сезоне.","Termine le championnat du monde de la saison 2.","Cancellare il Campionato del Mondo nella stagione 2.","Supera el Campeonato Mundial en la temporada 2.","Desobstruir o Campeonato do Mundo na época 2.",""),
["BigTask_title012"] = New("BigTask_title012","建造力量训练房","Build a Strength Practice Room.","筋力練習ルームを建造","建造力量訓練房","Baue einen Trainingsraum für Stärke.","Постройте комнату для тренировок силы.","Construire une salle d\'entraînement de force.","Costruisci una Stanza di pratica della forza.","Construye una sala de entrenamiento de fuerza.","Construir uma Sala de Prática de Força.",""),
["BigTask_title013"] = New("BigTask_title013","第3季世界大赛通关","Clear the World Championship in season 3.","シーズン3ワールド戦を通ります","第3季世界大賽通關","Schaffe die Weltmeisterschaft in Saison 3.","Завершите чемпионат мира в третьем сезоне.","Termine le championnat du monde de la saison 3.","Cancellare il Campionato del Mondo nella stagione 3.","Supera el Campeonato Mundial en la temporada 3.","Desobstruir o Campeonato do Mundo na época 3.",""),
["BigTask_title014"] = New("BigTask_title014","建造5阶竞技场","Build a rank-5 Baseball Stadium.","ランク5球場を建造","建造5階競技場","Baue ein Rang-5-Baseball-Stadion.","Постройте бейсбольный стадион ранга 5.","Construisez un stade de baseball de rang 5.","Costruire uno stadio di baseball di grado 5.","Construye un estadio de béisbol de rango 5.","Construir um Estádio de Basebol de categoria 5.",""),
["BigTask_title015"] = New("BigTask_title015","第4季世界大赛通关","Clear the World Championship in season 4.","シーズン4ワールド戦を通ります","第4季世界大賽通關","Schaffe die Weltmeisterschaft in Saison 4.","Очистите чемпионат мира в четвертом сезоне.","Termine le championnat du monde de la saison 4.","Cancella il Campionato del Mondo nella stagione 4.","Consigue el Campeonato Mundial en la temporada 4.","Desobstruir o Campeonato do Mundo na temporada 4.",""),
}
TableMerge(WordConfig,WordBigTaskConfig)
end