
do
local function New(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11)
	return {id=a0,cn=a1,en=a2,jp=a3,tw=a4,de=a5,ru=a6,fr=a7,it=a8,es=a9,pt=a10,kr=a11,}
end
local WordBattlePassConfig = 
{
["battlepass_goldpass"] = New("battlepass_goldpass","黄金通行证","Gold Pass","ゴールドパス","黃金通行證","Gold-Pass","Золотой пропуск","Gold Pass","Pass d\'oro","Pase de oro","Passe de Ouro",""),
["battlepass_goldtoken"] = New("battlepass_goldtoken","黄金令牌","Gold Token","ゴールドトークン","黃金令牌","Goldmünze","Золотой жетон","Jeton d\'or","Gettone d\'oro","Ficha de oro","Ficha Ouro",""),
["battlepass_tokenshop"] = New("battlepass_tokenshop","令牌商店","token shop","トークンショップ","令牌商店","Token-Shop","магазин жетонов","boutique de jetons","negozio di gettoni","tienda de fichas","loja de fichas",""),
["battlepass_unlockreward"] = New("battlepass_unlockreward","解锁后即可获得","After unlocking you can get","開放後に獲得できます","解鎖後即可獲得","Nach dem Freischalten können Sie Folgendes erhalten","После разблокировки вы можете получить","Après le déverrouillage, vous pouvez obtenir","Dopo lo sblocco puoi ottenere","Después de desbloquearlo puedes conseguir","Depois de desbloquear, pode obter",""),
["battlepass_exp"] = New("battlepass_exp","黄金通行证经验","Gold Pass Experience","ゴールドパス経験値","黃金通行證經驗","Gold Pass Erfahrung","Опыт Золотого пропуска","Expérience du Gold Pass","Esperienza Gold Pass","Experiencia del Pase Dorado","Experiência Gold Pass",""),
["battlepass_close"] = New("battlepass_close","离通行证结束还有","There is still time until the end of the pass","パスの期限切れまであと","離通行證結束還有","Es ist noch Zeit bis zum Ende des Passes","До конца действия пропуска еще есть время","Il reste encore du temps jusqu\'à la fin du pass.","C\'è ancora tempo fino alla fine del pass","Todavía hay tiempo hasta el final del pase","Ainda há tempo até ao fim do passe",""),
["battlepass_getexp"] = New("battlepass_getexp","获取经验","Get experience","経験値獲得","獲取經驗","Erfahrung erhalten","Получить опыт","Obtenir de l\'expérience","Ottieni esperienza","Conseguir experiencia","Adquira experiência",""),
["battlepass_buyexp"] = New("battlepass_buyexp","购买等级","Buy Level","購入lv","購買等級","Level kaufen","купить уровень","acheter un niveau","comprare il livello","comprar nivel","nível de compra",""),
["battlepass_free"] = New("battlepass_free","免费","Free","無料","免費","Kostenlos","Бесплатно","Gratuit","Gratis","Gratis","Grátis",""),
["battlepass_exclusive"] = New("battlepass_exclusive","专属","Exclusive","専用","專屬","Exklusiv","Эксклюзив","Exclusif","Esclusivo","Exclusivo","Exclusivo",""),
["battlepass_unlock"] = New("battlepass_unlock","解锁","Unlock","開放後に獲得できます","解鎖","freischalten","Разблокировать","Déverrouiller","Sblocca","Desbloquea","Desbloquear",""),
["battlepass_tips"] = New("battlepass_tips","解锁专属黄金通行证达到%s级，免费获得下赛季专属黄金通行证","Unlock the exclusive gold pass and reach the %s level, and get the exclusive gold pass for the next season for free","ゴールドパスを開放してlv%sに到達したら、次期のゴールドパスを獲得できます。","解鎖專屬黃金通行證達到%s級，免費獲得下賽季專屬黃金通行證","Schalte den exklusiven Goldpass frei und erreiche die %s-Stufe, um den exklusiven Goldpass für die nächste Saison kostenlos zu erhalten.","Разблокируйте эксклюзивный золотой пропуск и достигните %s уровня, получите эксклюзивный золотой пропуск на следующий сезон бесплатно.","Déverrouillez le gold pass exclusif et atteignez le niveau %s, et obtenez gratuitement le gold pass exclusif pour la saison suivante.","Sblocca il pass oro esclusivo e raggiungi il livello %s, e ottieni gratuitamente il pass oro esclusivo per la prossima stagione","Desbloquea el pase de oro exclusivo y alcanza el nivel %s, y obtén el pase de oro exclusivo para la siguiente temporada de forma gratuita","Desbloquear o passe de ouro exclusivo e atingir o nível das %s, e obter o passe de ouro exclusivo para a próxima estação gratuitamente",""),
["battlepass_Lvgoldtoken"] = New("battlepass_Lvgoldtoken","黄金通行证等级达到%s级后，继续升级可获得黄金令牌奖励","Continuing upgrades will get gold token rewards after reaching %s level in gold pass.","ゴールドパスがlv%sに到達したら、継続lvアップすることでゴールドトークンが獲得できます。","黃金通行證等級達到%s級後，繼續升級可獲得黃金令牌獎勵","Fortlaufende Upgrades werden nach Erreichen der %s-Stufe im Goldpass mit Goldmünzen belohnt.","После достижения %s уровня в золотом пропуске вы будете получать награды в виде золотых жетонов.","Les mises à niveau continues obtiendront des récompenses en jetons d\'or après avoir atteint le niveau %s du gold pass.","Continuando gli aggiornamenti si otterranno ricompense in gettoni d\'oro dopo aver raggiunto il livello %s del gold pass.","Al seguir subiendo de nivel obtendrás recompensas de tokens de oro después de alcanzar el nivel de %s en el pase de oro.","As actualizações contínuas receberão recompensas em fichas de ouro depois de atingir o nível de %s no passe de ouro.",""),
["battlepass_getexp_tips"] = New("battlepass_getexp_tips","用于提升黄金通行证等级","Used to level up the Gold Pass","ゴールドパスのlvアップに使います。","用於提升黃金通行證等級","Wird verwendet, um den Goldpass aufzuleveln","Используются для повышения уровня золотого пропуска","Utilisé pour augmenter le niveau du Gold Pass","Usato per far salire di livello il Gold Pass","Se utiliza para subir de nivel el pase de oro","Utilizada para nivelar o Passe de Ouro",""),
["battlepass_goldtoken_tips"] = New("battlepass_goldtoken_tips","用于在黄金通行证令牌商店内兑换商品","Used to redeem items in the token store","ゴールドパスのトークンショップで商品と交換に使います。","用於在黃金通行證令牌商店內兌換商品","Zum Einlösen von Gegenständen im Token-Shop","Используются для выкупа предметов в магазине жетонов","Utilisés pour échanger des articles dans le magasin de jetons.","Usato per riscattare oggetti nel negozio di gettoni","Se utiliza para canjear artículos en la tienda de fichas","Utilizado para resgatar itens na loja de fichas",""),
["battlepass_unlockexchange"] = New("battlepass_unlockexchange","解锁后即可兑换","After unlocking you can exchange","ロック解除後、交換することができます。","解鎖後即可兌換","Nach der Freischaltung können Sie tauschen","После разблокировки вы можете обменивать","Après le déverrouillage, vous pouvez échanger","Dopo lo sblocco è possibile scambiare","Tras el desbloqueo puedes intercambiar","Depois de desbloquear, pode trocar",""),
["battlepass_limit"] = New("battlepass_limit","限购","Limit","限度額","限購","Limit","Лимит","Limite","Limite","Límite","Limite",""),
["tip_buyPassCoin"] = New("tip_buyPassCoin","是否确认花费黄金令牌购买","Spend Gold Token to buy it now?","ゴールドトークンを使って今すぐ購入？","是否確認花費黃金令牌購買","Gold-Token ausgeben, um es jetzt zu kaufen?","Потратить Золотой Жетон, чтобы купить его сейчас?","Dépenser des jetons d\'or pour l\'acheter maintenant ?","Spendere gettoni d\'oro per comprarlo ora?","¿Gastar fichas de oro para comprarlo ahora?","Gastar o Token de Ouro para o comprar agora?",""),
["battlepass_ended"] = New("battlepass_ended","本期活动已结束","This event has ended","このイベントは終了しました","本期活動已結束","Dieses Ereignis ist beendet","Это событие закончилось","Cet événement est terminé","Questo evento è terminato","Este evento ha terminado","Este evento terminou",""),
["battlepass_nextfree"] = New("battlepass_nextfree","免费获得下赛季专属通行证","Get the exclusive gold pass for the next season for free","次シーズンの限定ゴールドパスを無料プレゼント","免費獲得下賽季專屬通行證","Erhalte den exklusiven Goldpass für die nächste Saison kostenlos","Получите эксклюзивный золотой пропуск на следующий сезон бесплатно","Obtenez gratuitement le laissez-passer Gold exclusif pour la prochaine saison.","Ottieni gratuitamente l\'esclusivo gold pass per la prossima stagione","Consigue gratis el pase de oro exclusivo para la próxima temporada","Obtenha o passe de ouro exclusivo para a próxima época gratuitamente",""),
["next_battlepass"] = New("next_battlepass","下个赛季的专属通行证","Next season exclusive pass","次シーズン専用パス","下個賽季的專屬通行證","Exklusiver Pass für die nächste Saison","Эксклюзивный пропуск на следующий сезон","Pass exclusif pour la saison prochaine","Pass esclusivo per la prossima stagione","Pase exclusivo de la próxima temporada","Passe exclusivo para a próxima estação",""),
}
TableMerge(WordConfig,WordBattlePassConfig)
end