
do
local function New(a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11)
	return {id=a0,cn=a1,en=a2,jp=a3,tw=a4,de=a5,ru=a6,fr=a7,it=a8,es=a9,pt=a10,kr=a11,}
end
local WordErrorConfig = 
{
[1100] = New(1100,"无法连接服务器，请稍后再试","Unable to connect to server. Please try again later.","ただいまサーバーに繋がることができません。しばらくお待ちになってからもう一度お試しください。","無法連接服務器，請稍後再試","Die Verbindung zum Server kann nicht hergestellt werden. Bitte versuchen Sie es später erneut.","Невозможно подключиться к серверу. Пожалуйста, повторите попытку позже.","Impossible de se connecter au serveur. Veuillez réessayer plus tard.","Impossibile connettersi al server. Si prega di riprovare più tardi.","No se ha podido conectar con el servidor. Por favor, inténtelo más tarde.","Incapaz de se ligar ao servidor. Por favor, tente novamente mais tarde.",""),
[1101] = New(1101,"版本过低，请前往下载最新版本。","Client outdated. Please install the latest update patch.","バージョンが低いようです。ストアで最新版に更新アップデートしてください。","版本過低，請前往下載最新版本。","Der Client ist veraltet. Bitte installieren Sie den neuesten Update-Patch.","Клиент устарел. Пожалуйста, установите последний патч обновления.","Le client est périmé. Veuillez installer le dernier patch de mise à jour.","Client obsoleto. Si prega di installare l\'ultima patch di aggiornamento.","El cliente no está actualizado. Por favor, instale el último parche de actualización.","Cliente desactualizado. Por favor instalar o último patch de actualização.",""),
[1102] = New(1102,"账号或密码错误","Incorrect username or password.","アカウントかパスワードが間違っています。","賬號或密碼錯誤","Falscher Benutzername oder falsches Passwort.","Неверное имя пользователя или пароль.","Nom d\'utilisateur ou mot de passe incorrect.","Nome utente o password errati.","Nombre de usuario o contraseña incorrectos.","Nome de utilizador ou palavra-passe incorrectos.",""),
[1103] = New(1103,"注册账号失败，已经有账号","Account registration failed. This account already exists.","アカウント登録失敗しました。すでにアカウント持っているようです。","註冊賬號失敗，已經有賬號","Kontoregistrierung fehlgeschlagen. Dieses Konto existiert bereits.","Регистрация учетной записи не удалась. Такая учетная запись уже существует.","L\'enregistrement du compte a échoué. Ce compte existe déjà.","Registrazione dell\'account non riuscita. Questo account esiste già.","El registro de la cuenta ha fallado. Esta cuenta ya existe.","O registo da conta falhou. Esta conta já existe.",""),
[1104] = New(1104,"注册账号失败，没有创建id","Account registration failed. No ID created.","アカウント登録失敗しました。IDが作れませんでした。","註冊賬號失敗，沒有創建id","Kontoregistrierung fehlgeschlagen. Keine ID erstellt.","Регистрация учетной записи не удалась. Идентификатор не создан.","L\'enregistrement du compte a échoué. Aucun identifiant n\'a été créé.","Registrazione dell\'account non riuscita. Nessun ID creato.","Error en el registro de la cuenta. No se ha creado ningún ID.","O registo da conta falhou. Não foi criada nenhuma identificação.",""),
[1105] = New(1105,"注册账号失败，账号id错误","Account registration failed. Invalid account ID.","アカウント登録失敗しました。アカウントIDエラーです。","註冊賬號失敗，賬號id錯誤","Kontoregistrierung fehlgeschlagen. Ungültige Konto-ID.","Регистрация учетной записи не удалась. Неверный идентификатор учетной записи.","L\'enregistrement du compte a échoué. ID de compte non valide.","Registrazione dell\'account non riuscita. ID account non valido.","Error en el registro de la cuenta. El ID de la cuenta no es válido.","O registo da conta falhou. ID da conta inválido.",""),
[1106] = New(1106,"服务器繁忙，请稍后登陆","Server is busy. Please try again later.","ただいまサーバーがビジー状態のようです。しばらくお待ちになってからもう一度ログインしてみてください。","服務器繁忙，請稍後登陸","Server ist beschäftigt. Bitte versuchen Sie es später erneut.","Сервер занят. Повторите попытку позже.","Le serveur est occupé. Veuillez réessayer plus tard.","Il server è occupato. Riprova più tardi.","El servidor está ocupado. Vuelva a intentarlo más tarde.","O servidor está ocupado. Por favor, tente novamente mais tarde.",""),
[1107] = New(1107,"账号非法字符","Illegal characters contained.","アカウントに不正文字が入っています。","賬號非法字符","Unzulässige Zeichen enthalten.","Содержатся недопустимые символы.","Caractères illégaux contenus.","Caratteri illegali contenuti.","Se han introducido caracteres ilegales.","Caracteres ilegais contidos.",""),
[1108] = New(1108,"未到开服时间","Server is not open yet.","サーバー開放時間になっていません。","未到開服時間","Der Server ist noch nicht geöffnet.","Сервер еще не открыт.","Le serveur n\'est pas encore ouvert.","Il server non è ancora aperto.","El servidor no está abierto todavía.","O servidor ainda não está aberto.",""),
[1109] = New(1109,"账号长度错误","Invalid username length.","アカウント長さエラー。","賬號長度錯誤","Ungültige Länge des Benutzernamens.","Неверная длина имени пользователя.","Longueur du nom d\'utilisateur non valide.","Lunghezza del nome utente non valida.","Longitud del nombre de usuario no válida.","Comprimento do nome de utilizador inválido.",""),
[1110] = New(1110,"平台SDK验证失败，请稍后再试","SDK verification failed. Please try again later.","プラットフォームSDK検証失敗。しばらくお待ちになってからもう一度お試しください。","平台SDK驗證失敗，請稍後再試","SDK-Verifizierung fehlgeschlagen. Bitte versuchen Sie es später noch einmal.","Проверка SDK не удалась. Повторите попытку позже.","La vérification du SDK a échoué. Veuillez réessayer plus tard.","Verifica SDK non riuscita. Riprova più tardi.","La verificación del SDK ha fallado. Por favor, inténtelo de nuevo más tarde.","A verificação SDK falhou. Por favor tente de novo mais tarde.",""),
[1111] = New(1111,"平台ID错误","Invalid platform ID.","プラットフォームIDエラー。","平台ID錯誤","Ungültige Plattform-ID.","Неверный идентификатор платформы.","ID de plate-forme non valide.","ID piattaforma non valido.","ID de plataforma no válida.","ID da plataforma inválida.",""),
[1112] = New(1112,"已经在登录队列","You are already in the login queue.","ログイン列中です。","已經在登錄隊列","Sie befinden sich bereits in der Anmeldewarteschlange.","Вы уже находитесь в очереди на вход.","Vous êtes déjà dans la file d\'attente de connexion.","Sei già nella coda di accesso.","Ya está en la cola de acceso.","Já se encontra na fila de login.",""),
[1113] = New(1113,"找不到网关服务器，请稍后再试","Gateway server not found. Please try again later.","ポータルサーバーが見つかりませんでした。もう一度お試しください。","找不到網關服務器，請稍後再試","Gateway-Server nicht gefunden. Bitte versuchen Sie es später noch einmal.","Не найден сервер шлюза. Повторите попытку позже.","Le serveur de la passerelle n\'a pas été trouvé. Veuillez réessayer plus tard.","Server gateway non trovato. Riprova più tardi.","No se ha encontrado el servidor de la pasarela. Vuelva a intentarlo más tarde.","Servidor de porta de entrada não encontrado. Por favor, tente novamente mais tarde.",""),
[1114] = New(1114,"找不到网关服务器PID，请稍后再试","Gateway server PID not found. Please try again later.","ポータルサーバーのPIDが見つかりませんでした。もう一度お試しください。","找不到網關服務器PID，請稍後再試","Gateway-Server-PID nicht gefunden. Bitte versuchen Sie es später noch einmal.","PID шлюзового сервера не найден. Повторите попытку позже.","PID du serveur de la passerelle non trouvé. Veuillez réessayer plus tard.","PID del server gateway non trovato. Riprova più tardi.","No se ha encontrado el PID del servidor de puerta de enlace. Vuelva a intentarlo más tarde.","Servidor de gateway PID não encontrado. Por favor, tente novamente mais tarde.",""),
[1115] = New(1115,"找不到网关服务器端口，请稍后再试","Gateway server port not found. Please try again later.","ポータルサーバーのポートが見つかりませんでした。もう一度お試しください。","找不到網關服務器端口，請稍後再試","Gateway-Server-Port nicht gefunden. Bitte versuchen Sie es später noch einmal.","Порт сервера шлюза не найден. Пожалуйста, повторите попытку позже.","Port du serveur de la passerelle non trouvé. Veuillez réessayer plus tard.","Porta del server gateway non trovata. Riprova più tardi.","No se ha encontrado el puerto del servidor de puerta de enlace. Vuelve a intentarlo más tarde.","Porta do servidor de portal não encontrada. Por favor, tente novamente mais tarde.",""),
[1116] = New(1116,"已经被封号","This account has been banned.","アカウントがバンされているようです。","已經被封號","Dieses Konto wurde gesperrt.","Эта учетная запись была запрещена.","Ce compte a été interdit.","Questo account è stato bannato.","Esta cuenta ha sido prohibida.","Esta conta foi banida.",""),
[1117] = New(1117,"你的账号在其他设备使用中","Your account is being used on another device.","このアカウントが別端末で使用中です。","你的賬號在其他設備使用中","Ihr Konto wird auf einem anderen Gerät verwendet.","Ваша учетная запись используется на другом устройстве.","Votre compte est utilisé sur un autre appareil.","Il tuo account è utilizzato su un altro dispositivo.","Su cuenta está siendo utilizada en otro dispositivo.","A sua conta está a ser utilizada num outro dispositivo.",""),
[1118] = New(1118,"服务器维护中，请稍后再试","Server is under maintenance. Please come back later.","サーバーメンテナンス中です。しばらくお待ちになってからもう一度お試しください。","服務器維護中，請稍後再試","Der Server wird gerade gewartet. Bitte kommen Sie später wieder.","Сервер находится на техническом обслуживании. Пожалуйста, вернитесь позже.","Le serveur est en cours de maintenance. Veuillez revenir plus tard.","Il server è in manutenzione. Si prega di tornare più tardi.","El servidor está en mantenimiento. Por favor, vuelva más tarde.","O servidor está em manutenção. Por favor, volte mais tarde.",""),
[1119] = New(1119,"登录网关验证失败，请稍后再试","Login gateway verification failed. Please try again later.","ログインポータル検証失敗。もう一度お試しください。","登錄網關驗證失敗，請稍後再試","Überprüfung des Login-Gateways fehlgeschlagen. Bitte versuchen Sie es später erneut.","Проверка шлюза входа не удалась. Пожалуйста, повторите попытку позже.","La vérification de la passerelle de connexion a échoué. Veuillez réessayer plus tard.","La verifica del gateway di accesso non è riuscita. Si prega di riprovare più tardi.","Ha fallado la verificación de la puerta de acceso. Por favor, inténtelo de nuevo más tarde.","A verificação da gateway de login falhou. Por favor, tente novamente mais tarde.",""),
[1120] = New(1120,"登录网关账号错误","Gateway account login failed.","ログインポータルアカウントエラー","登錄網關賬號錯誤","Gateway-Kontoanmeldung fehlgeschlagen.","Вход в учетную запись шлюза не удался.","La connexion au compte de la passerelle a échoué.","Login account gateway fallito.","Error en el inicio de sesión de la cuenta de la puerta de enlace.","O login da conta gateway falhou.",""),
[1121] = New(1121,"登录网关角色错误","Login gateway character error.","ログインポータルキャラエラー","登錄網關角色錯誤","Login-Gateway-Zeichenfehler.","Ошибка символа входа в шлюз.","Erreur de caractère de la passerelle de connexion.","Errore di carattere del gateway di accesso.","Error de caracteres de la puerta de enlace de inicio de sesión.","Erro no login de caracteres da porta de acesso.",""),
[1201] = New(1201,"未找到配置","Configuration not found.","配置ファイルが見つかりません","未找到配置","Konfiguration nicht gefunden.","Конфигурация не найдена.","Configuration non trouvée.","Configurazione non trovata.","Configuración no encontrada.","Configuração não encontrada.",""),
[1202] = New(1202,"钻石不足","Insufficient Diamonds.","ダイヤ不足","鑽石不足","Nicht genügend Diamanten.","Недостаточно алмазов.","Diamants insuffisants.","Diamanti insufficienti.","Diamantes insuficientes.","Diamantes insuficientes.",""),
[1203] = New(1203,"道具不足","Insufficient items.","アイテム不足","道具不足","Ungenügend Gegenstände.","Недостаточно предметов.","Articles insuffisants.","Oggetti insufficienti.","Artículos insuficientes.","Itens insuficientes.",""),
[1204] = New(1204,"次数已满","Limit reached.","回数切れ","次數已滿","Limit erreicht.","Достигнут лимит.","Limite atteinte.","Limite raggiunto.","Límite alcanzado.","Limite atingido.",""),
[1205] = New(1205,"数量不足","Insufficient quantity.","数量不足","數量不足","Unzureichende Menge.","Недостаточное количество.","Quantité insuffisante.","Quantità insufficiente.","Cantidad insuficiente.","Quantidade insuficiente.",""),
[1206] = New(1206,"冷却时间未到","Target is on cooldown.","回復中","冷卻時間未到","Ziel ist abgekühlt.","Цель находится в режиме ожидания.","La cible est en attente.","Obiettivo in fase di raffreddamento.","El objetivo está en fase de enfriamiento.","O alvo está em arrefecimento.",""),
[1207] = New(1207,"领取条件不足","Requirements unmet.","受領条件不足","領取條件不足","Anforderungen nicht erfüllt.","Требования не выполнены.","Exigences non satisfaites.","Requisiti non soddisfatti.","Requisitos no cumplidos.","Requisitos não satisfeitos.",""),
[1208] = New(1208,"已经领取","You have already claimed it.","受領済み","已經領取","Sie haben es bereits beansprucht.","Вы уже заявили об этом.","Vous l\'avez déjà réclamé.","L\'hai già rivendicato.","Ya lo has reclamado.","Já o reclamou.",""),
[1209] = New(1209,"已经解锁","You have already unlocked it.","開放済み","已經解鎖","Sie haben es bereits freigeschaltet.","Вы уже разблокировали его.","Vous l\'avez déjà débloqué.","L\'hai già sbloccato.","Ya lo has desbloqueado.","Já o desbloqueou.",""),
[1210] = New(1210,"抽卡错误","Invalid card drawing.","ガチャエラー","抽卡錯誤","Ungültige Karte gezogen.","Неверный рисунок карты.","Tirage de carte invalide.","Disegno della carta non valido.","Extracción de carta inválida.","Desenho de cartão inválido.",""),
[1211] = New(1211,"已经购买","You have already purchased it.","購入済み","已經購買","Sie haben es bereits gekauft.","Вы уже приобрели его.","Vous l\'avez déjà acheté.","L\'hai già acquistato.","Ya lo has comprado.","Já o comprou.",""),
[1212] = New(1212,"没有购买","You have not purchased it yet.","未購入","沒有購買","Sie haben die Karte noch nicht gekauft.","Вы еще не приобрели ее.","Vous ne l\'avez pas encore achetée.","Non l\'hai ancora acquistato.","Todavía no lo has comprado.","Ainda não o comprou.",""),
[1213] = New(1213,"卡牌信息错误","Card information error.","カード情報エラー","卡牌信息錯誤","Fehler bei den Karteninformationen.","Ошибка информации о карте.","Erreur d\'information sur la carte.","Errore nelle informazioni della carta.","Error en la información de la tarjeta.","Erro de informação do cartão.",""),
[1214] = New(1214,"商品解锁条件错误","Unlock requirement error.","商品開放条件エラー","商品解鎖條件錯誤","Fehler bei der Freischaltbedingung.","Ошибка требования разблокировки.","Erreur de condition de déverrouillage.","Errore nel requisito di sblocco.","Error en los requisitos de desbloqueo.","Erro de desbloqueio do requisito de desbloqueio.",""),
[1215] = New(1215,"礼包信息错误","Pack information error.","パック情報エラー","禮包信息錯誤","Fehler bei den Packinformationen.","Ошибка информации о пакете.","Erreur d\'information sur le pack.","Errore nelle informazioni del pacchetto.","Error de información del paquete.","Erro de informação de embalagem.",""),
[1300] = New(1300,"权限不足","Insufficient permissions.","権限不足","權限不足","Unzureichende Berechtigungen.","Недостаточно разрешений.","Autorisations insuffisantes.","Permessi insufficienti.","Permisos insuficientes.","Permissões insuficientes.",""),
[1301] = New(1301,"存档上传失败","Data upload failed.","データアップロード失敗","存檔上傳失敗","Daten-Upload fehlgeschlagen.","Не удалось загрузить данные.","Échec du téléchargement des données.","Caricamento dati non riuscito.","Error en la carga de datos.","Carregamento de dados falhado.",""),
[1305] = New(1305,"存档下载失败","Data download failed.","データダウンロード失敗","存檔下載失敗","Datendownload fehlgeschlagen.","Не удалось загрузить данные.","Échec du téléchargement de données.","Download dei dati non riuscito.","Error en la descarga de datos.","Falha no carregamento dos dados.",""),
[1122] = New(1122,"服务器即将关闭维护，您将会被强制下线。","The server is about to shut down for maintenance. You will be disconnected from the server.","まもなくサーバーがメンテナンスに入ります。強制ログオフされます。","服務器即將關閉維護，您將會被強制下線。","Der Server wird in Kürze wegen Wartungsarbeiten heruntergefahren. Die Verbindung zum Server wird unterbrochen.","Сервер скоро отключится для технического обслуживания. Вы будете отключены от сервера.","Le serveur est sur le point de s\'arrêter pour maintenance. Vous allez être déconnecté du serveur.","Il server sta per chiudersi per manutenzione. Sarai disconnesso dal server.","El servidor está a punto de cerrarse por mantenimiento. Se desconectará del servidor.","O servidor está prestes a desligar-se para manutenção. Será desconectado do servidor.",""),
[1123] = New(1123,"数据异常，请重新登录","Invalid data. Please log in again.","データ異常。もう一度ログインし直してください。","數據異常，請重新登錄","Ungültige Daten. Bitte melden Sie sich erneut an.","Неверные данные. Пожалуйста, войдите в систему снова.","Données non valides. Veuillez vous reconnecter.","Dati non validi. Per favore, accedi di nuovo.","Datos no válidos. Por favor, conéctese de nuevo.","Dados inválidos. Por favor, inicie novamente a sessão.",""),
}
TableMerge(WordConfig,WordErrorConfig)
end